Repository acterglobal/a3, pull requests merged in 2022-10, with the labels that each got.

#271 Fix panic bug on ephemeral event
  native/effektio/src/api/receipt.rs
Labels: bug, rust

#272 Improve code
  native/effektio/src/api/auth.rs
  native/effektio/src/api/receipt.rs
Labels: bug, rust

#275 Fix bug that waiting not finished when other device started sas verification
  app/lib/widgets/CrossSigning.dart
Labels: bug, flutter

#278 ci: upload apk and publish it on PR
  .github/workflows/app.yml
  .github/workflows/artifacts.yml
Labels: infrastructure, t-android

#292 Fetch rooms after first sync
  native/effektio/src/api/client.rs
  native/effektio/src/api/conversation.rs
Labels: bug, rust

#280 invitation route managment and state
  app/lib/controllers/chat_list_controller.dart
  app/lib/controllers/chat_room_controller.dart
  app/lib/controllers/receipt_controller.dart
  app/lib/screens/HomeScreens/chat/ChatProfile.dart
  app/lib/screens/HomeScreens/chat/ChatScreen.dart
  app/lib/screens/HomeScreens/chat/EditGroupInfo.dart
  app/lib/screens/HomeScreens/chat/Overview.dart
  app/lib/screens/HomeScreens/chat/RoomLinkSetting.dart
  app/lib/screens/UserScreens/SocialProfile.dart
  app/lib/widgets/AppCommon.dart
  app/lib/widgets/ChatListItem.dart
  app/lib/widgets/CustomAvatar.dart
  app/lib/widgets/InviteInfoWidget.dart
  app/lib/widgets/SideMenu.dart
  effektio_flutter_sdk/lib/effektio_flutter_sdk_ffi.dart
  native/effektio/api.rsh
  native/effektio/src/api.rs
  native/effektio/src/api/client.rs
  native/effektio/src/api/invitation.rs
  native/effektio/src/api/profile.rs
  native/effektio/src/api/room.rs
Labels: s-chat

#293 Issue230 status info for room message
  app/lib/controllers/chat_room_controller.dart
  app/lib/controllers/receipt_controller.dart
  native/effektio/src/api/receipt.rs
Labels: bug, flutter, rust, s-chat

#294 Issue198 cleanup code periodically
  app/lib/controllers/chat_list_controller.dart
  app/lib/controllers/chat_room_controller.dart
  app/lib/screens/HomeScreens/chat/ChatProfile.dart
  app/lib/screens/HomeScreens/chat/ChatScreen.dart
  app/lib/screens/HomeScreens/chat/EditGroupInfo.dart
  app/lib/widgets/AppCommon.dart
  app/lib/widgets/ChatListItem.dart
  app/lib/widgets/CrossSigning.dart
  app/lib/widgets/InviteInfoWidget.dart
  app/lib/widgets/SideMenu.dart
  effektio_flutter_sdk/lib/effektio_flutter_sdk_ffi.dart
  native/cli/src/action/post_news.rs
  native/core/src/events/labels.rs
  native/effektio-test/src/formatted_body.rs
  native/effektio-test/src/invitation.rs
  native/effektio/api.rsh
  native/effektio/src/api/conversation.rs
  native/effektio/src/api/device.rs
  native/effektio/src/api/group.rs
  native/effektio/src/api/invitation.rs
  native/effektio/src/api/message.rs
  native/effektio/src/api/news.rs
Labels: bug, flutter, rust

#295 Issue291 logout
  app/lib/main.dart
  app/lib/widgets/SideMenu.dart
  effektio_flutter_sdk/lib/effektio_flutter_sdk.dart
  effektio_flutter_sdk/lib/effektio_flutter_sdk_ffi.dart
  native/effektio-test/src/invitation.rs
  native/effektio/api.rsh
  native/effektio/src/api/auth.rs
  native/effektio/src/api/client.rs
  native/effektio/src/api/conversation.rs
  native/effektio/src/api/invitation.rs
  native/effektio/src/api/receipt.rs
  native/effektio/src/api/typing.rs
  native/effektio/src/platform/native.rs
Labels: flutter, rust

#301 After logout, user should go to home screen
  app/lib/widgets/SideMenu.dart
Labels: bug, flutter

#277 mentioning room members
  app/lib/controllers/chat_room_controller.dart
  app/lib/main.dart
  app/lib/screens/HomeScreens/chat/ChatScreen.dart
  app/lib/widgets/CustomChatInput.dart
  app/pubspec.lock
  app/pubspec.yaml
Labels: s-chat

#174 adding synapse for macos flutter integration tests
  .github/workflows/integration_testing.yml
  app/lib/main.dart
  app/pubspec.lock
Labels: infrastructure

#320 Issue198 cleanup code periodically
  app/lib/screens/HomeScreens/chat/Overview.dart
  app/lib/screens/HomeScreens/faq/Editor.dart
  app/lib/screens/HomeScreens/faq/Item.dart
  app/lib/widgets/ChatListItem.dart
  app/lib/widgets/CustomChatInput.dart
  app/lib/widgets/EmptyHistoryPlaceholder.dart
  app/lib/widgets/SideMenu.dart
  app/lib/widgets/ToDoListView.dart
  app/lib/widgets/ToDoTaskItem.dart
  app/lib/widgets/TypeIndicator.dart
  native/cli/src/action/fetch_news.rs
  native/cli/src/main.rs
  native/effektio/src/api/auth.rs
  native/effektio/src/api/verification.rs
Labels: bug, rust
