Repository acterglobal/a3, pull requests merged in 2022-11, with the labels that each got.

#323 Restructure bottom bar, clean up tasks and pins
  app/lib/common/store/themes/AppTheme.dart
  app/lib/common/store/themes/SeperatedThemes.dart
  app/lib/l10n/app_de.arb
  app/lib/l10n/app_en.arb
  app/lib/main.dart
  app/lib/screens/HomeScreens/faq/Editor.dart
  app/lib/screens/HomeScreens/faq/Item.dart
  app/lib/screens/HomeScreens/faq/Overview.dart
  app/lib/screens/SideMenuScreens/ToDo.dart
  app/lib/widgets/AppCommon.dart
  app/lib/widgets/NewsSideBar.dart
  app/lib/widgets/SideMenu.dart
  app/pubspec.lock
  app/pubspec.yaml
Labels: flutter, infrastructure, s-tasks, s-pins, s-news

#324 ci: trying to fix macos build
  .github/workflows/nightly.yml
Labels: build, infrastructure

#328 Replace pulldown-cmark with builtin markdown of matrix
  Cargo.lock
  native/effektio/Cargo.toml
  native/effektio/src/api/room.rs
Labels: rust

#299 Issue287 members avatars and names display in chat group description
  app/lib/controllers/chat_room_controller.dart
  app/lib/screens/HomeScreens/chat/ChatProfile.dart
  app/lib/screens/HomeScreens/chat/ChatScreen.dart
  app/lib/widgets/ChatListItem.dart
  app/lib/widgets/CustomAvatar.dart
  app/lib/widgets/CustomChatInput.dart
  app/lib/widgets/GroupMember.dart
Labels: s-chat

#300 Upgrade timeline
  Cargo.lock
  app/lib/controllers/chat_list_controller.dart
  app/lib/controllers/chat_room_controller.dart
  app/lib/screens/HomeScreens/chat/ChatScreen.dart
  app/lib/widgets/ChatListItem.dart
  app/linux/.gitignore
  app/linux/flutter/generated_plugin_registrant.cc
  app/linux/flutter/generated_plugin_registrant.h
  app/linux/flutter/generated_plugins.cmake
  app/macos/.gitignore
  app/macos/Flutter/GeneratedPluginRegistrant.swift
  app/macos/Runner.xcworkspace/xcsharedata/IDEWorkspaceChecks.plist
  app/packages/rust_sdk/lib/effektio_flutter_sdk.dart
  app/packages/rust_sdk/lib/effektio_flutter_sdk_ffi.dart
  native/effektio/Cargo.toml
  native/effektio/api.rsh
  native/effektio/src/api/client.rs
  native/effektio/src/api/conversation.rs
  native/effektio/src/api/group.rs
  native/effektio/src/api/message.rs
  native/effektio/src/api/room.rs
  native/effektio/src/api/stream.rs
  native/effektio/src/api/verification.rs
  native/effektio/src/platform/native.rs
Labels: s-chat

#298 improve avatars render
  app/lib/screens/HomeScreens/chat/ChatProfile.dart
  app/lib/screens/HomeScreens/chat/ChatScreen.dart
  app/lib/screens/HomeScreens/chat/EditGroupInfo.dart
  app/lib/screens/HomeScreens/chat/Overview.dart
  app/lib/screens/UserScreens/SocialProfile.dart
  app/lib/widgets/ChatListItem.dart
  app/lib/widgets/CustomAvatar.dart
  app/lib/widgets/CustomChatInput.dart
  app/lib/widgets/GroupMember.dart
  app/lib/widgets/InviteInfoWidget.dart
  app/lib/widgets/NewsItem.dart
  app/lib/widgets/SideMenu.dart
Labels: bug, flutter

#343 Tasks Demo preparations
  app/lib/common/store/themes/SeperatedThemes.dart
  app/lib/controllers/todo_controller.dart
  app/lib/screens/SideMenuScreens/ToDo.dart
  app/lib/widgets/ToDoListView.dart
  app/lib/widgets/ToDoTaskItem.dart
Labels: flutter

#347 Upgrade verification to v0.6
  app/lib/common/store/MockData.dart
  app/lib/screens/SideMenuScreens/ToDo.dart
  app/lib/widgets/CrossSigning.dart
  app/packages/rust_sdk/lib/effektio_flutter_sdk_ffi.dart
  native/effektio/api.rsh
  native/effektio/src/api/client.rs
  native/effektio/src/api/verification.rs
Labels: rust

#355 Fix bug that flutter doesn't accept some keyboard input
  app/lib/widgets/CustomChatInput.dart
Labels: flutter, s-chat

#346 Idenitfy Effektio via device_name
  .github/workflows/nightly.yml
  app/packages/rust_sdk/lib/effektio_flutter_sdk.dart
  app/packages/rust_sdk/lib/effektio_flutter_sdk_ffi.dart
  native/effektio/api.rsh
  native/effektio/src/api/auth.rs
Labels: build, infrastructure

#349 News demo data
  app/assets/images/feed1.jpg
  app/assets/images/feed2.jpg
  app/assets/images/feed3.jpg
  app/assets/images/feed4.jpg
  app/assets/images/feed5.jpg
  app/lib/common/store/MockData.dart
  app/lib/screens/HomeScreens/news/News.dart
  app/lib/widgets/NewsItem.dart
  app/packages/rust_sdk/lib/effektio_flutter_sdk_ffi.dart
  native/core/src/models/faq.rs
  native/core/src/models/mocks/images/charlies-trip.png
  native/core/src/models/mocks/images/jacksbirthday.png
  native/core/src/models/mocks/images/party-recap.jpg
  native/core/src/models/mocks/images/party.png
  native/core/src/models/mocks/images/sporting-invite.png
  native/core/src/models/news.rs
  native/effektio-test/src/invitation.rs
  native/effektio/api.rsh
Labels: flutter, s-news

#339 Issue312 fetch users out of current room
  app/lib/controllers/chat_room_controller.dart
  app/lib/screens/HomeScreens/chat/ChatProfile.dart
  app/lib/screens/HomeScreens/chat/ChatScreen.dart
  app/lib/screens/HomeScreens/chat/Overview.dart
  app/lib/screens/HomeScreens/chat/ReqAndInvites.dart
  app/lib/screens/HomeScreens/faq/Overview.dart
  app/lib/widgets/AppCommon.dart
  app/lib/widgets/ChatListItem.dart
  app/lib/widgets/InviteInfoWidget.dart
  app/lib/widgets/PendingReqListView.dart
  app/packages/rust_sdk/lib/effektio_flutter_sdk_ffi.dart
  native/effektio/api.rsh
  native/effektio/src/api/client.rs
  native/effektio/src/api/invitation.rs
  native/effektio/src/api/profile.rs
  native/effektio/src/api/room.rs
  native/effektio/src/api/stream.rs
Labels: rust

#372 Issue359 read receipt in chat
  app/lib/controllers/chat_room_controller.dart
  app/lib/controllers/receipt_controller.dart
Labels: bug, flutter, s-chat

#379 Simplify reply body for latest message
  Cargo.lock
  native/effektio/Cargo.toml
  native/effektio/src/api/conversation.rs
  native/effektio/src/api/message.rs
Labels: rust

#381 Internet State Management #337
  app/assets/images/no_internet.png
  app/lib/controllers/network_controller.dart
  app/lib/screens/HomeScreens/chat/ChatScreen.dart
  app/lib/screens/HomeScreens/chat/Overview.dart
  app/lib/screens/HomeScreens/faq/Overview.dart
  app/lib/screens/HomeScreens/news/News.dart
  app/lib/screens/OnboardingScreens/LogIn.dart
  app/lib/screens/OnboardingScreens/Signup.dart
  app/lib/screens/SideMenuScreens/ToDo.dart
  app/lib/widgets/AppCommon.dart
  app/pubspec.lock
  app/pubspec.yaml
Labels: bug, flutter

#388 Replace expect with context to avoid panic
  native/effektio/src/api/account.rs
  native/effektio/src/api/client.rs
  native/effektio/src/api/device.rs
  native/effektio/src/api/group.rs
  native/effektio/src/api/invitation.rs
  native/effektio/src/api/profile.rs
  native/effektio/src/api/room.rs
  native/effektio/src/api/verification.rs
Labels: rust

#384 prevent sending message event twice
  app/lib/controllers/chat_room_controller.dart
  app/lib/screens/HomeScreens/chat/ChatScreen.dart
Labels: bug, flutter

#389 add notification overlay for new session alert
  app/lib/common/store/themes/SeperatedThemes.dart
  app/lib/main.dart
  app/lib/widgets/CrossSigning.dart
  app/pubspec.lock
  app/pubspec.yaml
Labels: bug, flutter, rust

#391 Fix bug in event handler
  native/effektio/src/api/conversation.rs
Labels: bug, rust

#392 Improve code
  native/effektio/src/api/invitation.rs
  native/effektio/src/api/message.rs
  native/effektio/src/api/room.rs
Labels: rust
