Repository acterglobal/a3, pull requests merged in 2023-08, with the labels that each got.

#816 Upgrade sdk
  .changes/0816-upgrade-sdk.md
  .config/nextest.toml
  Cargo.lock
  Cargo.toml
  app/lib/features/chat/providers/notifiers/chat_room_notifier.dart
  app/lib/features/chat/widgets/bubble_builder.dart
  app/packages/rust_sdk/lib/acter_flutter_sdk_ffi.dart
  native/acter/Cargo.toml
  native/acter/api.rsh
  native/acter/src/api.rs
  native/acter/src/api/attachments.rs
  native/acter/src/api/auth.rs
  native/acter/src/api/client.rs
  native/acter/src/api/common.rs
  native/acter/src/api/convo.rs
  native/acter/src/api/message.rs
  native/acter/src/api/news.rs
  native/acter/src/api/notifications.rs
  native/acter/src/api/profile.rs
  native/acter/src/api/room.rs
  native/acter/src/api/search.rs
  native/acter/src/api/spaces.rs
  native/acter/src/api/stream.rs
  native/acter/src/platform/android.rs
  native/acter/src/platform/desktop.rs
  native/acter/src/platform/ios.rs
  native/acter/src/platform/native.rs
  native/acter/src/testing.rs
  native/cli/src/action/mock.rs
  native/core/src/events/news.rs
  native/core/src/lib.rs
  native/core/src/spaces.rs
  native/core/src/support.rs
  native/test/src/tests/news.rs
  native/test/src/tests/reply.rs
  native/test/src/tests/spaces.rs
  native/test/src/tests/templates.rs
Labels: rust

#848 fix missing type association problem
  app/lib/features/chat/widgets/bubble_builder.dart
Labels: bug, s-chat

#882 Add cli to acter for non-ui state management
  .changes/0882-cli.md
  app/lib/features/cli/commands/backup-and-reset.dart
  app/lib/features/cli/commands/info.dart
  app/lib/features/cli/main.dart
  app/lib/features/cli/util.dart
  app/lib/main.dart
  app/pubspec.lock
  app/pubspec.yaml
  docs/content/user/getting-started/cli.md
Labels: infrastructure

#895 User deactivation
  .changes/0895-user-deactivation.md
  app/lib/common/dialogs/deactivation_confirmation.dart
  app/lib/common/themes/app_theme.dart
  app/lib/features/activities/widgets/session_card.dart
  app/lib/features/profile/pages/my_profile_page.dart
  app/packages/rust_sdk/lib/acter_flutter_sdk.dart
  app/packages/rust_sdk/lib/acter_flutter_sdk_ffi.dart
  native/acter/api.rsh
  native/acter/src/api.rs
  native/acter/src/api/auth.rs
  native/acter/src/platform/android.rs
  native/acter/src/platform/desktop.rs
  native/acter/src/platform/ios.rs
  native/acter/src/platform/native.rs
  native/test/src/tests/auth.rs
  native/test/src/utils.rs
Labels: infrastructure

#900 Enforce Platform Emojis
  app/lib/common/themes/app_theme.dart
  app/lib/common/themes/chat_theme.dart
  app/lib/common/widgets/emoji_picker_widget.dart
  app/lib/features/chat/widgets/emoji_row.dart
  app/lib/features/chat/widgets/text_message_builder.dart
Labels: bug, flutter

#902 Fix chat sidebar
  app/lib/common/widgets/chat/convo_card.dart
  app/lib/common/widgets/with_sidebar.dart
  app/lib/features/chat/pages/chat_page.dart
  app/lib/features/chat/pages/room_page.dart
  app/lib/features/chat/providers/notifiers/chat_list_notifier.dart
  app/lib/features/chat/widgets/in_chat.dart
  app/lib/features/chat/widgets/rooms_list.dart
  app/lib/features/home/pages/dashboard.dart
  app/lib/router/router.dart
Labels: bug, flutter
