Repository acterglobal/a3, pull requests merged in 2023-09, with the labels that each got.

#948 switch default homeserver to staging environment
  .github/workflows/nightly.yml
  app/packages/rust_sdk/lib/acter_flutter_sdk.dart
Labels: infrastructure

#971 Fix parsing error from rust analyzer
  native/core/src/models.rs
Labels: rust

#976 Add the + for spaces->chats again. Not sure where it went
  app/lib/features/space/pages/chats_page.dart
Labels: flutter

#977 limit the sized box in height to to prevent overflowing of parent-space avatar
  app/lib/common/widgets/spaces/space_parent_badge.dart
Labels: flutter

#956 Reworking tasks
  Cargo.lock
  app/lib/common/themes/app_theme.dart
  app/lib/common/utils/routes.dart
  app/lib/features/bug_report/providers/notifiers/bug_report_notifier.dart
  app/lib/features/search/widgets/quick_actions_builder.dart
  app/lib/features/settings/pages/labs_page.dart
  app/lib/features/space/pages/tasks_page.dart
  app/lib/features/space/providers/space_navbar_provider.dart
  app/lib/features/space/settings/pages/apps_settings_page.dart
  app/lib/features/tasks/dialogs/create_task_list_sheet.dart
  app/lib/features/tasks/models/tasks.dart
  app/lib/features/tasks/pages/tasks_page.dart
  app/lib/features/tasks/providers/notifiers.dart
  app/lib/features/tasks/providers/tasklists.dart
  app/lib/features/tasks/providers/tasks.dart
  app/lib/features/tasks/widgets/all_tasks_done.dart
  app/lib/features/tasks/widgets/task_entry.dart
  app/lib/features/tasks/widgets/task_list_card.dart
  app/lib/features/todo/controllers/todo_controller.dart
  app/lib/features/todo/pages/assignments_page.dart
  app/lib/features/todo/pages/bookmarks_page.dart
  app/lib/features/todo/pages/create_task_sidesheet.dart
  app/lib/features/todo/pages/create_todo_page.dart
  app/lib/features/todo/pages/recent_activity_page.dart
  app/lib/features/todo/pages/subscriber_page.dart
  app/lib/features/todo/pages/task_assign_page.dart
  app/lib/features/todo/pages/task_comments_page.dart
  app/lib/features/todo/pages/task_detail_page.dart
  app/lib/features/todo/pages/todo_mine_page.dart
  app/lib/features/todo/pages/todo_page.dart
  app/lib/features/todo/widgets/add_task_dialog.dart
  app/lib/features/todo/widgets/comment_input.dart
  app/lib/features/todo/widgets/create_task_side_sheet.dart
  app/lib/features/todo/widgets/task_card.dart
  app/lib/features/todo/widgets/todo_card.dart
  app/lib/features/todo/widgets/todo_comment_view.dart
  app/lib/features/todo/widgets/todo_list_view.dart
  app/lib/features/todo/widgets/todo_task_view.dart
  app/lib/router/router.dart
  app/packages/rust_sdk/lib/acter_flutter_sdk_ffi.dart
  app/pubspec.lock
  app/pubspec.yaml
  native/acter/Cargo.toml
  native/acter/api.rsh
  native/acter/src/api.rs
  native/acter/src/api/common.rs
  native/acter/src/api/room.rs
  native/acter/src/api/settings.rs
  native/acter/src/api/tasks.rs
  native/core/src/events/settings.rs
  native/core/src/models/tasks/task.rs
  native/test/src/tests/tasks.rs
  native/tui/src/ui.rs
Labels: s-tasks

#1012 directly invite if the full username is given
  .changes/1012-directly-invite.md
  app/lib/common/dialogs/invite_to_room_dialog.dart
  app/lib/common/widgets/invite_result_card.dart
  app/lib/features/chat/widgets/invite_user_dialog.dart
Labels: flutter

#1011 convo with retry for more reliable convo lookup at creation
  Cargo.lock
  app/lib/features/chat/dialogs/create_chat_sheet.dart
  app/packages/rust_sdk/lib/acter_flutter_sdk_ffi.dart
  native/acter/Cargo.toml
  native/acter/api.rsh
  native/acter/src/api/convo.rs
Labels: bug
