Repository acterglobal/a3, pull requests merged in 2023-03, with the labels that each got.

#463 Real world Desktop integration smoke tests
  .github/effektio-synapse-ci/ci-start.sh
  .github/workflows/app.yml
  .github/workflows/docs.yml
  .github/workflows/integration_testing.yml
  .github/workflows/native.yml
  .github/workflows/styles.yml
  .vscode/launch.json
  Cargo.lock
  app/.gitignore
  app/analysis_options.yaml
  app/build.yaml
  app/integration_test/features/login_smoketest.feature
  app/integration_test/gherkin_suite_test.dart
  app/integration_test/gherkin_suite_test.g.dart
  app/integration_test/smoketest.dart
  app/integration_test/steps/given_login.dart
  app/lib/common/controllers/network_controller.dart
  app/lib/common/utils/constants.dart
  app/lib/features/home/controllers/home_controller.dart
  app/lib/features/home/pages/home_page.dart
  app/lib/features/home/widgets/side_drawer.dart
  app/lib/features/news/pages/news_page.dart
  app/lib/features/onboarding/controllers/auth_controller.dart
  app/lib/features/onboarding/controllers/login_controller.dart
  app/lib/features/onboarding/controllers/signup_controller.dart
  app/lib/features/onboarding/pages/login_page.dart
  app/lib/features/onboarding/pages/sign_up_page.dart
  app/lib/main.dart
  app/packages/rust_sdk/lib/effektio_flutter_sdk.dart
  app/packages/rust_sdk/lib/effektio_flutter_sdk_ffi.dart
  app/packages/rust_sdk/pubspec.yaml
  app/pubspec.lock
  app/pubspec.yaml
  app/test_driver/integration_test.dart
  docker-compose.yml
  docs/content/docs/dev/testing.md
  docs/static/images/integration-tests-debug-vscode-example.png
  native/cli/Cargo.toml
  native/cli/src/action.rs
  native/cli/src/action/fetch_news.rs
  native/cli/src/action/mock.rs
  native/cli/src/action/post_news.rs
  native/cli/src/config.rs
  native/effektio-test/src/tests/auth.rs
  native/effektio-test/src/tests/tasks.rs
  native/effektio-tui/Cargo.toml
  native/effektio-tui/src/config.rs
  native/effektio/api.rsh
  native/effektio/src/api/auth.rs
  util/cucumber_reporter/.gitignore
  util/cucumber_reporter/index.js
  util/cucumber_reporter/package.json
Labels: flutter, infrastructure

#445 Refactor Executor
  .github/workflows/integration_testing.yml
  .github/workflows/native.yml
  Cargo.lock
  app/lib/common/widgets/custom_avatar.dart
  native/core/Cargo.toml
  native/core/src/executor.rs
  native/core/src/lib.rs
  native/core/src/models.rs
  native/core/src/models/comments.rs
  native/core/src/models/tasks.rs
  native/core/src/models/test.rs
  native/core/src/store.rs
  native/effektio/src/api/profile.rs
Labels: rust

#505 Adaptive layout.
  app/android/app/build.gradle
  app/lib/common/themes/app_theme.dart
  app/lib/features/home/pages/home_page.dart
  app/lib/features/home/widgets/home_widget.dart
  app/lib/features/home/widgets/side_drawer.dart
  app/lib/features/home/widgets/user_avatar.dart
  app/lib/features/news/pages/news_page.dart
  app/pubspec.lock
  app/pubspec.yaml
Labels: flutter, infrastructure

#514 Fix bug that console log doesn't work with riverpod
  app/lib/features/home/controllers/home_controller.dart
Labels: bug, flutter, rust

#522 Fix bug that screenshot for bug report doesn't work
  app/lib/features/home/pages/home_page.dart
  app/lib/main.dart
Labels: bug, flutter

#549 Improve code
  app/android/app/src/main/kotlin/global/acter/app/MainActivity.kt
  native/acter/src/api/client.rs
  native/acter/src/api/comments.rs
  native/acter/src/api/conversation.rs
  native/acter/src/api/group.rs
  native/acter/src/api/invitation.rs
  native/acter/src/api/message.rs
  native/acter/src/api/news.rs
  native/acter/src/api/pins.rs
  native/acter/src/api/profile.rs
  native/acter/src/api/receipt.rs
  native/acter/src/api/room.rs
  native/acter/src/api/tasks.rs
  native/acter/src/platform/native.rs
  native/cli/src/action.rs
  native/cli/src/action/execute.rs
  native/cli/src/action/fetch_news.rs
  native/cli/src/action/mock.rs
  native/cli/src/action/post_news.rs
  native/cli/src/config.rs
  native/cli/src/main.rs
  native/core/src/client.rs
  native/core/src/events/comments.rs
  native/core/src/events/common.rs
  native/core/src/events/labels.rs
  native/core/src/events/news.rs
  native/core/src/events/pins.rs
  native/core/src/events/tasks.rs
  native/core/src/executor.rs
  native/core/src/models/color.rs
  native/core/src/models/comments.rs
  native/core/src/models/news.rs
  native/core/src/models/tag.rs
  native/core/src/templates.rs
  native/core/src/templates/functions.rs
  native/core/src/templates/values.rs
  native/test/src/tests/onboarding.rs
  native/test/src/tests/pins.rs
  native/test/src/tests/redact.rs
  native/test/src/tests/tasks.rs
  native/test/src/tests/templates.rs
  native/tui/src/config.rs
  native/tui/src/main.rs
  native/tui/src/ui.rs
Labels: rust

#562 Bugfix - too many logs
  Cargo.lock
  app/ios/Podfile.lock
  app/packages/rust_sdk/lib/acter_flutter_sdk_ffi.dart
  native/acter/Cargo.toml
  native/acter/api.rsh
  native/acter/src/api.rs
  native/acter/src/platform/android.rs
  native/acter/src/platform/desktop.rs
  native/acter/src/platform/ios.rs
  native/acter/src/platform/native.rs
Labels: bug, rust

#571 Improve room operation under latest matrix
  .vscode/launch.json
  app/lib/features/chat/controllers/chat_room_controller.dart
  app/lib/features/chat/controllers/receipt_controller.dart
  app/lib/main.dart
  app/packages/rust_sdk/lib/acter_flutter_sdk.dart
  app/packages/rust_sdk/lib/acter_flutter_sdk_ffi.dart
  native/acter/api.rsh
  native/acter/src/api/client.rs
  native/acter/src/api/conversation.rs
  native/acter/src/api/group.rs
  native/acter/src/api/receipt.rs
  native/acter/src/api/room.rs
  native/test/src/tests/receipt.rs
Labels: flutter, rust
