Repository acterglobal/a3, pull requests merged in 2024-05, with the labels that each got.

#1702 Make space & chat selectors searchable, fix several issues along the way
  app/lib/common/providers/chat_providers.dart
  app/lib/common/providers/room_providers.dart
  app/lib/common/providers/space_providers.dart
  app/lib/common/widgets/chat/chat_selector_drawer.dart
  app/lib/common/widgets/room/brief_room_list_entry.dart
  app/lib/common/widgets/room/select_room_drawer.dart
  app/lib/common/widgets/spaces/space_selector_drawer.dart
  app/lib/features/news/widgets/news_item.dart
  app/lib/features/news/widgets/news_side_bar.dart
  app/lib/features/space/sheets/link_room_sheet.dart
Labels: bug, flutter, c-super-invites

#1699 Room hierarchy join button fixes
  app/lib/common/widgets/chat/convo_hierarchy_card.dart
  app/lib/common/widgets/room/room_hierarchy_join_button.dart
  app/lib/common/widgets/spaces/space_hierarchy_card.dart
  app/lib/features/space/pages/chats_page.dart
  app/lib/features/space/widgets/relatest_spaces.dart
Labels: bug, flutter

#1708 Default invite code information
  app/lib/features/onboarding/pages/register_page.dart
  app/lib/l10n/app_en.arb
Labels: minor

#1668 Leaving room removes room objects
  .vscode/launch.json
  app/integration_test/support/appstart.dart
  app/integration_test/support/login.dart
  app/integration_test/tests/updates.dart
  app/lib/features/space/dialogs/leave_space.dart
  app/lib/features/space/widgets/space_toolbar.dart
  app/lib/main.dart
  app/lib/router/utils.dart
  native/acter/src/api/client.rs
  native/acter/src/api/client/sync.rs
  native/core/src/executor.rs
  native/core/src/models.rs
  native/core/src/models/attachments.rs
  native/core/src/models/calendar/event.rs
  native/core/src/models/comments.rs
  native/core/src/models/news.rs
  native/core/src/models/pins.rs
  native/core/src/models/reactions.rs
  native/core/src/models/rsvp.rs
  native/core/src/models/tasks/task.rs
  native/core/src/models/tasks/task_list.rs
  native/core/src/models/test.rs
  native/core/src/store.rs
  native/test/src/tests/spaces.rs
  native/test/src/tests/templates.rs
  util/conv_test_man/pubspec.lock
Labels: rust, infrastructure

#1719 More expressive information on the permissions we are using
  app/ios/Runner/Info.plist
Labels: t-ios, minor

#1718 Minor navigation fixes for sidebar and quickjump on desktop
  app/integration_test/tests/bug_reporter.dart
  app/lib/features/home/data/models/nav_item.dart
  app/lib/features/home/pages/home_shell.dart
  app/lib/features/home/providers/navigation.dart
  app/lib/features/home/widgets/sidebar_widget.dart
  app/lib/features/search/widgets/spaces_builder.dart
  app/lib/router/router.dart
  app/lib/router/utils.dart
Labels: flutter

#1727 Simplify Space's space list
  app/integration_test/support/login.dart
  app/integration_test/support/spaces.dart
  app/integration_test/support/util.dart
  app/integration_test/tests/sub_spaces.dart
  app/lib/common/toolkit/menu_item_widget.dart
  app/lib/features/settings/widgets/settings_menu.dart
  app/lib/features/space/pages/overview_page.dart
  app/lib/features/space/pages/related_spaces_page.dart
  app/lib/features/space/pages/sub_spaces_page.dart
  app/lib/features/space/widgets/related_spaces/helpers.dart
  app/lib/features/space/widgets/related_spaces/recommended_spaces.dart
  app/lib/features/space/widgets/related_spaces/sub_spaces_card.dart
  app/lib/features/space/widgets/related_spaces_card.dart
  app/lib/features/space/widgets/relatest_spaces.dart
  app/lib/features/space/widgets/top_nav.dart
  app/lib/router/shell_routers/home_shell_router.dart
Labels: flutter

#1736 Fix the integration test for image edit
  native/test/src/tests/msg_edit.rs
Labels: minor

#1671 Refactor permission checking
  app/packages/rust_sdk/lib/acter_flutter_sdk_ffi.dart
  native/acter/api.rsh
  native/acter/src/api/account.rs
  native/acter/src/api/attachments.rs
  native/acter/src/api/backup.rs
  native/acter/src/api/calendar_events.rs
  native/acter/src/api/client.rs
  native/acter/src/api/client/sync.rs
  native/acter/src/api/comments.rs
  native/acter/src/api/convo.rs
  native/acter/src/api/device.rs
  native/acter/src/api/invitation.rs
  native/acter/src/api/news.rs
  native/acter/src/api/pins.rs
  native/acter/src/api/push.rs
  native/acter/src/api/reactions.rs
  native/acter/src/api/receipt.rs
  native/acter/src/api/room.rs
  native/acter/src/api/rsvp.rs
  native/acter/src/api/search.rs
  native/acter/src/api/settings/space.rs
  native/acter/src/api/settings/user.rs
  native/acter/src/api/spaces.rs
  native/acter/src/api/stream.rs
  native/acter/src/api/super_invites.rs
  native/acter/src/api/tasks.rs
  native/acter/src/api/three_pid.rs
  native/acter/src/api/typing.rs
  native/acter/src/api/verification.rs
  native/cli/src/action/history.rs
  native/cli/src/action/manage.rs
  native/core/src/models/comments.rs
  native/core/src/spaces.rs
  native/core/src/statics.rs
  native/test/src/tests/spaces.rs
Labels: rust

#1735 Fix sticky zoom bubble
  app/lib/features/chat/pages/room_page.dart
  app/lib/features/chat/providers/chat_providers.dart
  app/lib/features/chat/widgets/bubble_builder.dart
  app/lib/features/chat/widgets/custom_input.dart
  app/lib/features/chat/widgets/image_message_builder.dart
  app/pubspec.lock
  app/pubspec.yaml
Labels: bug, flutter, s-chat

#1747 Update secure storage
  app/macos/Podfile.lock
  app/macos/Runner.xcodeproj/project.pbxproj
  app/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  app/pubspec.lock
  app/pubspec.yaml
Labels: minor

#1734 Calendar event location apis
  app/packages/rust_sdk/lib/acter_flutter_sdk_ffi.dart
  native/acter/api.rsh
  native/acter/src/api.rs
  native/acter/src/api/calendar_events.rs
  native/core/src/events/calendar.rs
Labels: rust

#1765 Fixing #1750: clone before mutating, simplify news conversion code
  app/lib/features/chat/widgets/custom_input.dart
  app/packages/rust_sdk/lib/acter_flutter_sdk_ffi.dart
  native/acter/api.rsh
  native/acter/src/api/news.rs
  native/acter/src/api/stream/msg_draft.rs
Labels: bug, flutter, s-chat, f-attachments, s-news, minor

#1766 Weblate latest
  app/lib/l10n/app_da.arb
  app/lib/l10n/app_de.arb
  app/lib/l10n/app_en.arb
Labels: minor, translations

#1748 New super invites info system
  app/integration_test/support/spaces.dart
  app/integration_test/support/super_invites.dart
  app/integration_test/tests/super_invites.dart
  app/lib/features/onboarding/pages/register_page.dart
  app/lib/features/settings/super_invites/providers/super_invites_providers.dart
  app/lib/features/settings/widgets/settings_menu.dart
  app/lib/features/super_invites/dialogs/redeem_dialog.dart
  app/lib/features/super_invites/pages/create.dart
  app/lib/features/super_invites/pages/super_invites.dart
  app/lib/features/super_invites/providers/super_invites_providers.dart
  app/lib/features/super_invites/widgets/redeem_token.dart
  app/lib/features/super_invites/widgets/to_join_room.dart
  app/lib/l10n/app_en.arb
  app/lib/router/general_router.dart
  app/lib/router/shell_routers/home_shell_router.dart
  app/packages/rust_sdk/lib/acter_flutter_sdk_ffi.dart
  native/acter/api.rsh
  native/acter/src/api.rs
  native/acter/src/api/super_invites.rs
  native/core/src/super_invites.rs
  util/test_server/.config/acter-synapse-ci/Dockerfile
Labels: c-super-invites

#1769 Better error reporting upon registration and login
  native/acter/src/api/auth.rs
Labels: rust, infrastructure

#1767 Cleaning up the Main shell and main navigation
  app/lib/features/home/pages/home_shell.dart
  app/lib/features/home/providers/navigation.dart
  app/lib/features/home/widgets/activities_icon.dart
  app/lib/features/home/widgets/sidebar_widget.dart
Labels: flutter, infrastructure, tech-debt

#1771 Chat room fixes
  .changes/1771-fix-typing-notifications.md
  Cargo.lock
  Cargo.toml
  app/lib/common/widgets/chat/convo_card.dart
  app/lib/features/chat/pages/room_page.dart
  app/lib/features/chat/providers/chat_providers.dart
  app/packages/rust_sdk/lib/acter_flutter_sdk_ffi.dart
  native/acter/Cargo.toml
  native/acter/api.rsh
  native/acter/src/api/typing.rs
  native/core/Cargo.toml
  native/test/src/tests/typing.rs
Labels: bug, s-chat

#1773 Improving Chat design: more muted states design, show topic at the beginning of the history
  Cargo.lock
  Cargo.toml
  app/lib/common/models/attachment_media_state/attachment_media_state.freezed.dart
  app/lib/common/models/sync_state/sync_state.freezed.dart
  app/lib/features/chat/dialogs/encryption_info_drawer.dart
  app/lib/features/chat/models/chat_input_state/chat_input_state.freezed.dart
  app/lib/features/chat/models/chat_list_state/chat_list_state.freezed.dart
  app/lib/features/chat/models/chat_room_state/chat_room_state.dart
  app/lib/features/chat/models/chat_room_state/chat_room_state.freezed.dart
  app/lib/features/chat/models/room_list_filter_state/room_list_filter_state.freezed.dart
  app/lib/features/chat/pages/room_page.dart
  app/lib/features/chat/pages/room_profile_page.dart
  app/lib/features/chat/providers/chat_providers.dart
  app/lib/features/chat/providers/notifiers/chat_room_notifier.dart
  app/lib/features/chat/utils.dart
  app/lib/features/chat/widgets/custom_message_builder.dart
  app/lib/features/chat/widgets/messages/encrypted_info.dart
  app/lib/features/chat/widgets/messages/encrypted_message.dart
  app/lib/features/chat/widgets/messages/location_message.dart
  app/lib/features/chat/widgets/messages/membership_update.dart
  app/lib/features/chat/widgets/messages/poll_start_message.dart
  app/lib/features/chat/widgets/messages/redacted_message.dart
  app/lib/features/chat/widgets/messages/simple_state_update.dart
  app/lib/features/chat/widgets/messages/sticker_message.dart
  app/lib/features/chat/widgets/messages/topic.dart
  app/lib/features/news/model/news_post_state.freezed.dart
  app/lib/features/pins/models/pin_edit_state/pin_edit_state.freezed.dart
  app/lib/features/public_room_search/models/public_search_filters.freezed.dart
  app/lib/l10n/app_en.arb
  app/packages/rust_sdk/lib/acter_flutter_sdk_ffi.dart
  native/acter/api.rsh
  native/acter/src/api/convo.rs
  native/acter/src/api/profile.rs
  native/acter/src/api/push.rs
  native/acter/src/api/stream.rs
  native/acter/src/api/stream/msg_draft.rs
  native/cli/src/action/list.rs
Labels: s-chat

#1775 make event location api fields optional
  app/packages/rust_sdk/lib/acter_flutter_sdk_ffi.dart
  native/acter/api.rsh
  native/acter/src/api/calendar_events.rs
Labels: rust, minor

#1776 Translated using Weblate (German)
  app/lib/l10n/app_de.arb
Labels: minor, translations

#1780 Fix notifications upon registration
  .changes/1780-notifications.md
  app/lib/features/home/pages/home_shell.dart
  native/test/src/tests/news.rs
Labels: minor

#1786 remove faulty download nightly.yml
  .github/workflows/nightly.yml
Labels: build, minor

#1784 Chat emoji design fixes
  .changes/1784-emoji-fixes.md
  app/lib/features/chat/widgets/bubble_builder.dart
  app/lib/features/chat/widgets/chat_layout_builder.dart
  app/lib/features/chat/widgets/emoji/emoji_container.dart
  app/lib/features/chat/widgets/emoji/emoji_reaction_item.dart
  app/lib/features/chat/widgets/emoji/emoji_row.dart
Labels: flutter, s-chat

#1795 Update to latest matrix rust SDK
  Cargo.lock
  Cargo.toml
Labels: bug, rust, minor

#1794 fix publishing aur
  .github/workflows/nightly.yml
Labels: build, minor, t-linux

#1796 Updating to latest weblate for english and german
  app/lib/l10n/app_de.arb
  app/lib/l10n/app_en.arb
Labels: minor, translations

#1800 fix subsition pattern for version of aur
  .github/workflows/nightly.yml
Labels: build, infrastructure, minor

#1802 Better sharing facitilies
  app/lib/common/widgets/download_button.dart
  app/lib/common/widgets/image_dialog.dart
  app/lib/common/widgets/video_dialog.dart
  app/lib/features/attachments/widgets/views/file_view.dart
  app/lib/features/chat/widgets/file_message_builder.dart
  app/lib/features/events/pages/event_details_page.dart
  app/lib/l10n/app_en.arb
  app/pubspec.lock
  app/pubspec.yaml
Labels: flutter, s-calendar, f-attachments

#1804 Fixing NoClientException at startup
  app/lib/features/home/pages/home_shell.dart
Labels: bug, flutter, minor
