Repository acterglobal/a3, pull requests merged in 2024-06, with the labels that each got.

#1805 use a local path to fix nightly build to aur
  .github/workflows/nightly.yml
Labels: bug, build, minor, t-linux

#1799 Allow admins to redact space items
  app/lib/common/providers/common_providers.dart
  app/lib/common/widgets/redact_content.dart
  app/lib/features/events/pages/event_details_page.dart
  app/lib/features/news/widgets/news_side_bar.dart
  app/lib/features/pins/pages/pin_page.dart
  app/packages/rust_sdk/lib/acter_flutter_sdk_ffi.dart
  native/acter/api.rsh
  native/acter/src/api/attachments.rs
  native/acter/src/api/calendar_events.rs
  native/acter/src/api/comments.rs
  native/acter/src/api/news.rs
  native/acter/src/api/pins.rs
  native/acter/src/api/room.rs
  native/acter/src/api/tasks.rs
  native/core/src/models.rs
  native/core/src/models/tasks/task.rs
  native/core/src/models/tasks/task_list.rs
Labels: infrastructure, s-space

#1810 Upgrading go_router
  app/pubspec.lock
  app/pubspec.yaml
Labels: bug, dependencies, minor

#1811 Revive Backup and Reset for new secure storage
  app/lib/features/cli/commands/backup-and-reset.dart
  app/lib/features/cli/util.dart
  app/packages/rust_sdk/lib/acter_flutter_sdk.dart
Labels: bug, minor

#1812 Bookmarking spaces
  app/lib/common/providers/space_providers.dart
  app/lib/features/chat/models/room_list_filter_state/room_list_filter_state.dart
  app/lib/features/chat/pages/room_profile_page.dart
  app/lib/features/home/widgets/my_spaces_section.dart
  app/lib/features/space/widgets/space_toolbar.dart
  app/lib/features/spaces/pages/spaces_page.dart
  app/lib/l10n/app_en.arb
  app/packages/rust_sdk/lib/acter_flutter_sdk_ffi.dart
  native/acter/api.rsh
  native/acter/src/api/convo.rs
  native/acter/src/api/spaces.rs
Labels: s-space

#1814 replace all matches in aur, add aur it to release
  .github/workflows/nightly.yml
  .github/workflows/publish.yml
Labels: build, minor

#1819 Adding changelogs for a bunch of PRs we forgot to make them for/with
  .changes/1799-space-admin-redactions.md
  .changes/1802-sharing-facilities.md
  .changes/1806-access-levels.md
  .changes/1812-space-bookmakrs.md
  .changes/1813-task-lists.md
Labels: documentation, minor

#1820 Better empties for chat and subspaces
  .changes/1820-better-empties.md
  app/lib/features/chat/widgets/convo_list.dart
  app/lib/features/space/pages/chats_page.dart
  app/lib/features/space/pages/sub_spaces_page.dart
  app/lib/l10n/app_en.arb
Labels: bug, flutter, minor, s-space

#1821 Update latest german translations from Weblate
  app/lib/l10n/app_de.arb
Labels: translations

#1823 Fixing android build
  .github/workflows/nightly.yml
  .github/workflows/publish.yml
  app/pubspec.lock
  app/pubspec.yaml
Labels: build

#1824 Upgrade flutter dependencies
  .github/workflows/styles.yml
  app/android/app/build.gradle
  app/android/build.gradle
  app/android/settings.gradle
  app/lib/common/dialogs/deactivation_confirmation.dart
  app/lib/common/providers/network_provider.dart
  app/lib/common/themes/acter_theme.dart
  app/lib/common/themes/colors/color_scheme.dart
  app/lib/common/themes/components/button_theme.dart
  app/lib/common/toolkit/buttons/danger_action_button.dart
  app/lib/common/toolkit/buttons/inline_text_button.dart
  app/lib/common/widgets/dotted_border_widget.dart
  app/lib/common/widgets/emoji_picker_widget.dart
  app/lib/common/widgets/search.dart
  app/lib/features/attachments/widgets/attachment_container.dart
  app/lib/features/attachments/widgets/attachment_section.dart
  app/lib/features/attachments/widgets/views/file_view.dart
  app/lib/features/attachments/widgets/views/image_view.dart
  app/lib/features/attachments/widgets/views/video_view.dart
  app/lib/features/chat/pages/room_profile_page.dart
  app/lib/features/chat/providers/chat_providers.dart
  app/lib/features/chat/widgets/custom_input.dart
  app/lib/features/chat/widgets/emoji/emoji_container.dart
  app/lib/features/chat/widgets/emoji/emoji_row.dart
  app/lib/features/chat/widgets/image_message_builder.dart
  app/lib/features/chat/widgets/message_actions.dart
  app/lib/features/chat/widgets/rooms_list.dart
  app/lib/features/chat/widgets/video_message_builder.dart
  app/lib/features/events/pages/create_edit_event_page.dart
  app/lib/features/events/pages/event_details_page.dart
  app/lib/features/events/widgets/calendar_widget.dart
  app/lib/features/news/widgets/news_item.dart
  app/lib/features/news/widgets/news_post_editor/news_slide_options.dart
  app/lib/features/news/widgets/space_item.dart
  app/lib/features/onboarding/pages/save_username_page.dart
  app/lib/features/public_room_search/widgets/public_room_search.dart
  app/lib/features/room/widgets/notifications_settings_tile.dart
  app/lib/features/settings/widgets/options_settings_tile.dart
  app/lib/features/space/widgets/links_card.dart
  app/lib/features/space/widgets/top_nav.dart
  app/packages/rust_sdk/lib/acter_flutter_sdk.dart
  app/pubspec.lock
  app/pubspec.yaml
Labels: dependencies, minor

#1830 Hardening the setup procedures to continue on errors with a fresh session
  app/packages/rust_sdk/lib/acter_flutter_sdk.dart
Labels: bug, build, infrastructure, minor

#1831 Small fix
  native/acter/src/api/account.rs
  native/acter/src/api/attachments.rs
  native/acter/src/api/auth.rs
  native/acter/src/api/backup.rs
  native/acter/src/api/calendar_events.rs
  native/acter/src/api/client.rs
  native/acter/src/api/client/sync.rs
  native/acter/src/api/comments.rs
  native/acter/src/api/convo.rs
  native/acter/src/api/news.rs
  native/acter/src/api/pins.rs
  native/acter/src/api/profile.rs
  native/acter/src/api/push.rs
  native/acter/src/api/reactions.rs
  native/acter/src/api/rsvp.rs
  native/acter/src/api/search.rs
  native/acter/src/api/settings/user.rs
  native/acter/src/api/spaces.rs
  native/acter/src/api/stream.rs
  native/acter/src/api/stream/msg_draft.rs
  native/acter/src/api/super_invites.rs
Labels: rust, minor

#1833 Expose canRedact api about some models
  app/packages/rust_sdk/lib/acter_flutter_sdk_ffi.dart
  native/acter/api.rsh
Labels: rust, minor

#1834 Small fix
  native/acter/src/api/spaces.rs
Labels: rust, minor

#1828 new due date picker via bottom drawer
  app/integration_test/tests/tasks.dart
  app/lib/common/toolkit/menu_item_widget.dart
  app/lib/features/tasks/sheets/create_update_task_item.dart
  app/lib/features/tasks/widgets/due_chip.dart
  app/lib/features/tasks/widgets/due_picker.dart
  app/lib/l10n/app_en.arb
  app/pubspec.lock
  app/pubspec.yaml
Labels: flutter, s-tasks

#1836 replace registration code with `organize`
  app/lib/features/onboarding/pages/register_page.dart
Labels: minor

#1837 Upgrade Firebase SDK to re-enable push notifications token fetching
  .gitignore
  .vscode/launch.json
  app/android/app/build.gradle
  app/android/app/google-services.json
  app/android/settings.gradle
  app/lib/common/notifications/notifications.dart
  app/lib/config/firebase_options.dart
  app/pubspec.lock
  app/pubspec.yaml
Labels: bug, build, t-android, f-push-notifications

#1864 Bump flowyeditor to 3.5
  app/lib/common/widgets/md_editor_with_preview.dart
  app/pubspec.lock
  app/pubspec.yaml
Labels: dependencies, minor

#1866 Manual refresh for manually loaded data: sessions, super_invites
  app/lib/features/settings/pages/sessions_page.dart
  app/lib/features/super_invites/pages/super_invites.dart
Labels: flutter, minor

#1865 Fix chat inviting
  app/lib/features/chat/pages/room_page.dart
  app/lib/features/chat/providers/chat_providers.dart
  app/lib/features/chat/widgets/bubble_builder.dart
  app/lib/features/chat/widgets/messages/encrypted_info.dart
  app/lib/features/chat/widgets/messages/invite.dart
  app/lib/features/chat/widgets/messages/topic.dart
  app/lib/features/invite_members/pages/invite_space_members.dart
Labels: bug, s-chat

#1869 Add changelog ci
  .changes/1869-github-ci-test.md
  .github/workflows/changelog.yml
Labels: build, infrastructure, minor

#1870 Activities screen shows unconfirmed Emails
  .changes/1861-show-unconfirmed-emails.md
  app/integration_test/support/login.dart
  app/integration_test/tests/auth.dart
  app/lib/common/providers/common_providers.dart
  app/lib/features/activities/pages/activities_page.dart
  app/lib/features/activities/providers/activities_providers.dart
  app/lib/features/onboarding/pages/link_email_page.dart
  app/lib/l10n/app_en.arb
Labels: flutter, infrastructure, privacy & security

#1792 multi-parent avatars for spaces
  .changes/1122-multi-parent-avatars.md
  app/lib/common/providers/room_providers.dart
  app/lib/common/providers/space_providers.dart
  app/lib/common/widgets/chat/convo_card.dart
  app/lib/common/widgets/chat/convo_with_profile_card.dart
  app/lib/common/widgets/spaces/space_card.dart
  app/lib/common/widgets/spaces/space_with_profile_card.dart
  app/lib/features/chat/pages/room_page.dart
  app/lib/features/chat/pages/room_profile_page.dart
  app/lib/features/chat/widgets/avatar_builder.dart
  app/lib/features/chat/widgets/room_avatar.dart
  app/lib/features/home/widgets/sidebar_widget.dart
  app/lib/features/invite_members/pages/invite_space_members.dart
  app/lib/features/invite_members/widgets/space_member_invite_card.dart
  app/lib/features/news/widgets/news_side_bar.dart
  app/lib/features/public_room_search/widgets/maybe_direct_room_action_widget.dart
  app/lib/features/space/pages/chats_page.dart
  app/lib/features/space/settings/widgets/space_settings_menu.dart
  app/lib/features/space/widgets/chats_card.dart
  app/lib/features/space/widgets/related_spaces/helpers.dart
  app/lib/features/space/widgets/space_header_profile.dart
  app/lib/features/super_invites/widgets/to_join_room.dart
  app/lib/l10n/app_en.arb
  app/pubspec.lock
  app/pubspec.yaml
Labels: s-space

#1875 Fixing startup error
  Makefile.toml
  app/lib/common/notifications/notifications.dart
  app/lib/common/utils/utils.dart
  app/packages/rust_sdk/android/build.gradle
Labels: bug, build, t-android, minor

#1876 Invite code improvements
  .changes/1874-invitations-fixes.md
  app/lib/common/utils/routes.dart
  app/lib/features/invite_members/pages/invite_page.dart
  app/lib/features/invite_members/widgets/invite_code_ui.dart
  app/lib/features/super_invites/pages/create.dart
  app/lib/features/super_invites/providers/super_invites_providers.dart
  app/lib/l10n/app_en.arb
Labels: c-super-invites

#1889 set macos minimum deployment target
  app/macos/Runner.xcodeproj/project.pbxproj
  app/macos/Runner.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
Labels: t-desktop, t-macos

#1890 Reducing the re-rendering of the chat input
  app/lib/common/providers/room_providers.dart
  app/lib/common/widgets/chat/convo_with_avatar_card.dart
  app/lib/features/chat/pages/room_page.dart
  app/lib/features/chat/widgets/custom_input.dart
  app/lib/features/chat/widgets/room_avatar.dart
Labels: bug, flutter, s-chat

#1894 Upgrade the dependency tree
  app/packages/rust_sdk/pubspec.yaml
  app/pubspec.lock
  app/pubspec.yaml
Labels: flutter

#1897 Missed an upgrade there
  app/packages/rust_sdk/lib/acter_flutter_sdk_ffi.dart
Labels: bug, build, minor
