Repository acterglobal/a3, pull requests merged in 2024-02, with the labels that each got.

#1349 Update dependencies
  Cargo.lock
  native/acter/Cargo.toml
  native/test/src/tests/news.rs
  native/tui/Cargo.toml
Labels: rust, minor

#1351 [small-fix] Improve flutter code
  app/lib/common/providers/common_providers.dart
  app/lib/features/chat/widgets/custom_input.dart
  app/lib/features/cli/commands/backup-and-reset.dart
  app/lib/features/news/news_utils/news_utils.dart
  app/lib/features/news/widgets/news_post_editor/news_slide_options.dart
  app/lib/features/space/sheets/edit_space_sheet.dart
Labels: flutter, minor

#1365 docs have moved to dev.acter.global
  Readme.md
  docs/config.toml
Labels: minor

#1368 [tinyfix] - Replace the missed slash with platform directory separator
  app/lib/features/events/sheets/create_event_sheet.dart
  app/lib/features/news/news_utils/news_utils.dart
  app/lib/features/news/widgets/news_item_slide/video_slide.dart
  app/packages/rust_sdk/lib/acter_flutter_sdk.dart
Labels: flutter, minor

#1373 Revert FfiOption
  app/lib/common/dialogs/invite_to_room_dialog.dart
  app/lib/common/providers/chat_providers.dart
  app/lib/common/providers/common_providers.dart
  app/lib/common/providers/notifiers/space_notifiers.dart
  app/lib/common/providers/room_providers.dart
  app/lib/common/providers/space_providers.dart
  app/lib/common/widgets/user_builder.dart
  app/lib/features/activities/providers/invitations_providers.dart
  app/lib/features/chat/providers/notifiers/media_chat_notifier.dart
  app/lib/features/chat/widgets/create_chat.dart
  app/lib/features/events/pages/event_page.dart
  app/lib/features/events/widgets/events_item.dart
  app/packages/rust_sdk/lib/acter_flutter_sdk_ffi.dart
  native/acter/api.rsh
  native/acter/src/api/common.rs
  native/acter/src/api/rsvp.rs
  native/test/src/tests/rsvp.rs
  native/tui/src/main.rs
Labels: flutter, rust, minor

#1375 Rename 'token' -> 'code' in the UI
  app/lib/common/utils/constants.dart
  app/lib/features/settings/super_invites/pages/create.dart
  app/lib/features/settings/super_invites/pages/super_invites.dart
  app/lib/features/settings/super_invites/widgets/redeem_token.dart
  app/lib/l10n/app_de.arb
  app/lib/l10n/app_en.arb
Labels: flutter, smooth UX, minor

#1381 fix dev-docs path for sari poster
  .github/workflows/nightly.yml
  .github/workflows/publish.yml
  Readme.md
  docs/content/nightly/2023-08-26.md
  docs/static/CNAME
Labels: minor

#1402 Fix conflict in vm_service version of convenient_test_manager_dart
  .github/workflows/demo.yml
  .github/workflows/deploy.yml
  .github/workflows/docs.yml
  .github/workflows/integration_testing.yml
  .github/workflows/native.yml
  .github/workflows/nightly.yml
  .github/workflows/publish.yml
  .github/workflows/styles.yml
Labels: flutter, minor

#1403 forgot the changelog for appflowy in news editor
  .changes/1399-appflowy-in-news-updates.md
Labels: minor

#1418 Fix several state related News Editor bugs
  app/lib/features/news/pages/add_news_page.dart
Labels: flutter, s-news

#1419 Small refactoring on api wrappers
  app/lib/common/providers/chat_providers.dart
  app/lib/common/providers/notifiers/space_notifiers.dart
  app/lib/common/providers/room_providers.dart
  app/lib/common/utils/utils.dart
  app/lib/common/widgets/md_editor_with_preview.dart
  app/lib/features/bug_report/pages/bug_report_page.dart
  app/lib/features/chat/widgets/create_chat.dart
  app/lib/features/events/pages/event_page.dart
  app/lib/features/events/widgets/events_item.dart
  app/lib/features/home/providers/notifiers/client_notifier.dart
  app/lib/features/space/sheets/link_room_sheet.dart
  app/lib/features/spaces/sheets/create_space_sheet.dart
  app/packages/rust_sdk/lib/acter_flutter_sdk.dart
Labels: flutter, minor

#1423 Fix iOS build problem
  Cargo.lock
  Cargo.toml
  Makefile.toml
  app/ios/Podfile
  app/ios/Podfile.lock
  app/ios/Runner.xcodeproj/project.pbxproj
  app/pubspec.lock
Labels: build, t-ios, minor

#1420 Refactoring of ref.watch & ref.read
  app/integration_test/tests/tasks.dart
  app/lib/common/dialogs/invite_to_room_dialog.dart
  app/lib/common/notifications/notifications.dart
  app/lib/common/providers/chat_providers.dart
  app/lib/common/providers/notifiers/space_notifiers.dart
  app/lib/common/providers/room_providers.dart
  app/lib/common/providers/space_providers.dart
  app/lib/features/chat/chat_utils/chat_utils.dart
  app/lib/features/chat/pages/room_page.dart
  app/lib/features/chat/widgets/create_chat.dart
  app/lib/features/events/providers/event_providers.dart
  app/lib/features/events/sheets/create_event_sheet.dart
  app/lib/features/events/sheets/edit_event_sheet.dart
  app/lib/features/events/widgets/calendar_widget.dart
  app/lib/features/news/pages/add_news_page.dart
  app/lib/features/news/widgets/news_post_editor/news_slide_options.dart
  app/lib/features/pins/providers/notifiers/pins_notifiers.dart
  app/lib/features/settings/providers/notifications_mode_provider.dart
  app/lib/features/space/sheets/link_room_sheet.dart
  app/lib/features/space/widgets/non_acter_space_card.dart
  app/lib/features/space/widgets/space_toolbar.dart
Labels: flutter

#1408 (push) Notifications for NewsUpates
  .changes/1408-updates-push.md
  Cargo.lock
  Cargo.toml
  app/android/app/src/main/AndroidManifest.xml
  app/android/app/src/main/drawable-hdpi/logo_notification.png
  app/android/app/src/main/logo_notification.png
  app/android/app/src/main/res/drawable-hdpi/logo_notification.png
  app/android/app/src/main/res/drawable-mdpi/logo_notification.png
  app/android/app/src/main/res/drawable-xhdpi/logo_notification.png
  app/android/app/src/main/res/drawable-xxhdpi/logo_notification.png
  app/android/app/src/main/res/drawable-xxxhdpi/logo_notification.png
  app/android/app/src/main/res/raw/keep.xml
  app/android/app/src/main/res/values/colors.xml
  app/ios/ActerPushServiceExtension/NotificationService.swift
  app/ios/ActerPushServiceExtension/acter.swift
  app/ios/acterFFI/acterFFI.h
  app/lib/common/notifications/notifications.dart
  app/lib/common/providers/common_providers.dart
  app/lib/common/providers/notifiers/notification_settings_notifier.dart
  app/lib/common/utils/routes.dart
  app/lib/features/room/widgets/notifications_settings_tile.dart
  app/lib/features/settings/pages/blocked_users.dart
  app/lib/features/settings/pages/notifications_page.dart
  app/lib/features/settings/providers/settings_providers.dart
  app/lib/features/settings/super_invites/providers/super_invites_providers.dart
  app/lib/features/settings/widgets/app_notifications_settings_tile.dart
  app/lib/features/space/settings/pages/notification_configuration_page.dart
  app/lib/features/space/settings/widgets/space_settings_menu.dart
  app/lib/features/space/widgets/space_toolbar.dart
  app/lib/features/tasks/widgets/task_info.dart
  app/lib/router/router.dart
  app/lib/router/shell_routers/home_shell_router.dart
  app/packages/rust_sdk/lib/acter_flutter_sdk.dart
  app/packages/rust_sdk/lib/acter_flutter_sdk_ffi.dart
  native/acter/Cargo.toml
  native/acter/api.rsh
  native/acter/src/api.rs
  native/acter/src/api/client.rs
  native/acter/src/api/common.rs
  native/acter/src/api/convo.rs
  native/acter/src/api/push.rs
  native/acter/src/api/spaces.rs
  native/acter/src/api/uniffi_api.rs
  native/core/Cargo.toml
  native/core/src/events/news.rs
  native/core/src/lib.rs
  native/core/src/push.rs
  native/media-cache-wrapper/Cargo.toml
  native/test/src/tests.rs
  native/test/src/tests/news.rs
  native/test/src/tests/push.rs
Labels: s-news

#1424 Refactoring of subscription
  app/lib/common/providers/notifiers/chat_notifiers.dart
  app/lib/common/providers/notifiers/room_notifiers.dart
  app/lib/common/providers/notifiers/space_notifiers.dart
  app/lib/common/providers/room_providers.dart
  app/lib/common/providers/space_providers.dart
  app/lib/common/widgets/chat/convo_card.dart
  app/lib/common/widgets/spaces/space_card.dart
  app/lib/features/activities/providers/notifiers/invitation_list_notifier.dart
  app/lib/features/activities/providers/notifiers/notifications_list_notifier.dart
  app/lib/features/chat/pages/room_page.dart
  app/lib/features/chat/providers/notifiers/chat_room_notifier.dart
  app/lib/features/chat/widgets/image_message_builder.dart
  app/lib/features/chat/widgets/video_message_builder.dart
  app/lib/features/events/providers/event_providers.dart
  app/lib/features/home/providers/navigation.dart
  app/lib/features/home/providers/notifiers/sync_notifier.dart
  app/lib/features/home/providers/task_providers.dart
  app/lib/features/news/providers/notifiers/news_list_notifier.dart
  app/lib/features/pins/providers/notifiers/pins_notifiers.dart
  app/lib/features/search/providers/spaces.dart
  app/lib/features/space/pages/chats_page.dart
  app/lib/features/space/pages/related_spaces_page.dart
  app/lib/features/space/sheets/link_room_sheet.dart
  app/lib/features/tasks/providers/notifiers.dart
  app/lib/features/tasks/providers/tasklists.dart
Labels: flutter

#1429 Pick up random element from array
  Makefile.toml
  app/lib/common/providers/room_providers.dart
  app/lib/common/providers/space_providers.dart
  app/lib/common/themes/colors/color_scheme.dart
  app/lib/common/themes/components/card_theme.dart
  app/lib/common/themes/components/list_tile_Theme.dart
  app/lib/common/themes/components/navigationbar_theme.dart
  app/lib/common/utils/utils.dart
  app/lib/features/chat/widgets/member_list.dart
  app/lib/features/cli/commands/backup-and-reset.dart
  app/lib/features/events/pages/events_page.dart
  app/lib/features/home/providers/events.dart
  app/lib/features/home/widgets/my_spaces_section.dart
  app/lib/features/home/widgets/my_tasks.dart
  app/lib/features/news/news_utils/news_utils.dart
  app/lib/features/news/providers/news_post_editor_providers.dart
  app/lib/features/pins/pages/pin_page.dart
  app/lib/features/pins/providers/pins_provider.dart
  app/lib/features/settings/widgets/email_address_card.dart
  app/lib/features/settings/widgets/session_card.dart
  app/lib/features/space/pages/members_page.dart
  app/lib/features/space/pages/pins_page.dart
  app/lib/features/space/pages/related_spaces_page.dart
  app/lib/features/space/pages/tasks_page.dart
  app/lib/features/space/widgets/chats_card.dart
  app/lib/features/space/widgets/links_card.dart
  app/lib/features/space/widgets/related_spaces_card.dart
  app/lib/features/tasks/widgets/task_info.dart
  app/packages/rust_sdk/lib/acter_flutter_sdk.dart
Labels: flutter, minor

#1432 Missed one: tokens -> codes
  app/lib/features/settings/widgets/settings_menu.dart
Labels: minor

#1435 minor UI fixes
  .changes/1435-minor-ui.md
  app/lib/common/providers/room_providers.dart
  app/lib/common/widgets/chat/convo_hierarchy_card.dart
  app/lib/common/widgets/chat/convo_with_profile_card.dart
  app/lib/common/widgets/room/brief_room_list_entry.dart
  app/lib/common/widgets/spaces/select_space_form_field.dart
  app/lib/features/news/widgets/news_post_editor/news_slide_options.dart
  app/lib/features/space/pages/chats_page.dart
Labels: flutter

#1448 Live redaction support for spaces.
  .changes/1448-live-redactions.md
  native/acter/src/api/spaces.rs
  native/core/src/executor.rs
  native/core/src/models.rs
Labels: rust

#1453 Fix ios simulator
  Makefile.toml
  native/media-cache-wrapper/Cargo.toml
Labels: build, t-ios, minor
