Repository acterglobal/a3, pull requests merged in 2024-08, with the labels that each got.

#2013 Ci fixes
  .github/workflows/build-app.yml
  .github/workflows/build-changelog.yml
  .github/workflows/demo.yml
  .github/workflows/docs.yml
  .github/workflows/flutter_integration_testing.yml
  .github/workflows/integration_testing.yml
  .github/workflows/native.yml
  .github/workflows/styles.yml
  .github/workflows/unittest.yml
  app/test/features/auth/pages/login_page_test.dart
  app/test/features/chat/chat_message_test.dart
  app/test/widget_test.dart
Labels: build

#2034 Avatar upload fixes
  .changes/meta-171.md
  app/android/app/src/main/AndroidManifest.xml
  native/acter/src/api/account.rs
Labels: bug, flutter, minor

#2036 Fix scrolling issue in super invites edit
  app/lib/features/super_invites/pages/create.dart
Labels: flutter, minor, c-super-invites

#2039 Quickjump routing fixes
  .changes/meta-449.md
  app/lib/features/search/pages/quick_jump.dart
  app/lib/features/search/pages/search.dart
  app/lib/features/search/widgets/pins_builder.dart
  app/lib/features/search/widgets/quick_actions_builder.dart
  app/lib/features/search/widgets/quick_jump.dart
  app/lib/features/search/widgets/spaces_builder.dart
Labels: flutter

#2035 Bookmarking events and generic features
  app/lib/features/bookmarks/actions/bookmarking.dart
  app/lib/features/bookmarks/providers/bookmarks_provider.dart
  app/lib/features/bookmarks/providers/notifiers.dart
  app/lib/features/bookmarks/types.dart
  app/lib/features/bookmarks/widgets/bookmark_action.dart
  app/lib/features/events/pages/event_details_page.dart
Labels: flutter, infrastructure

#2043 New notifier to plug directly to rsvp status of an event
  app/lib/features/events/providers/event_providers.dart
  app/lib/features/events/providers/notifiers/rsvp_notifier.dart
Labels: bug

#2037 Relations after interactions
  .changes/2037-spaces-relations.md
  app/lib/common/providers/room_providers.dart
  app/lib/common/providers/space_providers.dart
  app/lib/common/widgets/chat/convo_hierarchy_card.dart
  app/lib/common/widgets/room/room_hierarchy_join_button.dart
  app/lib/common/widgets/spaces/space_hierarchy_card.dart
  app/lib/features/chat/actions/create_chat.dart
  app/lib/features/chat/pages/room_profile_page.dart
  app/lib/features/room/actions/join_room.dart
  app/lib/features/space/actions/unlink_child_room.dart
  app/lib/features/space/dialogs/leave_space.dart
  app/lib/features/space/sheets/link_room_sheet.dart
  app/lib/features/spaces/actions/create_space.dart
  native/acter/api.rsh
  native/acter/src/api/client.rs
  native/acter/src/api/convo.rs
  native/acter/src/api/room.rs
  native/acter/src/api/spaces.rs
  native/core/src/spaces.rs
  packages/rust_sdk/lib/acter_flutter_sdk_ffi.dart
Labels: s-chat, s-space

#2038 Enven support
  .github/workflows/build-app.yml
  .github/workflows/demo.yml
  .github/workflows/flutter_integration_testing.yml
  .github/workflows/integration_testing.yml
  .github/workflows/nightly.yml
  .github/workflows/styles.yml
  .github/workflows/unittest.yml
  .gitignore
  Makefile.toml
  app/.env
  app/integration_test/support/mail.dart
  app/lib/common/notifications/notifications.dart
  app/lib/common/utils/constants.dart
  app/lib/config/setup.dart
  app/lib/features/auth/pages/forgot_password.dart
  app/lib/features/bug_report/const.dart
  app/lib/features/bug_report/pages/bug_report_page.dart
  app/lib/features/cli/commands/backup-and-reset.dart
  app/lib/features/cli/commands/info.dart
  app/lib/features/settings/pages/info_page.dart
  app/lib/main.dart
  app/pubspec.lock
  app/pubspec.yaml
  packages/rust_sdk/lib/acter_flutter_sdk.dart
Labels: infrastructure, build-demo, ci-test-ui-android

#2028 Desktop notifications support
  .github/workflows/build-app.yml
  .github/workflows/demo.yml
  Makefile.toml
  app/.env
  app/lib/common/notifications/notifications.dart
  app/lib/common/notifications/util.dart
  app/lib/common/providers/notifiers/chat_notifiers.dart
  app/lib/config/notifications/firebase_options.dart
  app/lib/config/notifications/init.dart
  app/lib/config/notifications/util.dart
  app/lib/features/home/pages/home_shell.dart
  app/lib/features/settings/pages/notifications_page.dart
  app/lib/features/settings/widgets/labs_notifications_settings_tile.dart
  app/lib/main.dart
  app/lib/router/general_router.dart
  app/lib/router/providers/notifiers/router_notifier.dart
  app/lib/router/providers/router_providers.dart
  app/lib/router/router.dart
  app/lib/router/shell_routers/activities_shell_router.dart
  app/lib/router/shell_routers/chat_shell_router.dart
  app/lib/router/shell_routers/home_shell_router.dart
  app/lib/router/shell_routers/search_shell_router.dart
  app/lib/router/shell_routers/update_shell_router.dart
  app/pubspec.lock
  app/pubspec.yaml
  packages/acter_notifify/.flutter-plugins
  packages/acter_notifify/.flutter-plugins-dependencies
  packages/acter_notifify/.gitignore
  packages/acter_notifify/.metadata
  packages/acter_notifify/CHANGELOG.md
  packages/acter_notifify/LICENSE
  packages/acter_notifify/README.md
  packages/acter_notifify/analysis_options.yaml
  packages/acter_notifify/lib/acter_notifify.dart
  packages/acter_notifify/lib/local.dart
  packages/acter_notifify/lib/matrix.dart
  packages/acter_notifify/lib/ntfy.dart
  packages/acter_notifify/lib/platform/android.dart
  packages/acter_notifify/lib/platform/darwin.dart
  packages/acter_notifify/lib/platform/linux.dart
  packages/acter_notifify/lib/platform/windows.dart
  packages/acter_notifify/lib/push.dart
  packages/acter_notifify/lib/util.dart
  packages/acter_notifify/pubspec.yaml
  packages/acter_notifify/test/acter_notifify_test.dart
Labels: bug, f-push-notifications, merge post release only

#2042 Links on attachments
  native/acter/api.rsh
  native/acter/src/api/attachments.rs
  native/acter/src/api/common.rs
  native/core/src/events/attachments.rs
  packages/rust_sdk/lib/acter_flutter_sdk_ffi.dart
Labels: rust, f-attachments

#2052 Upgrade notificiation plugin
  packages/acter_notifify/pubspec.yaml
Labels: dependencies, minor

#2054 Decrease shake sensitivity
  app/lib/features/home/pages/home_shell.dart
Labels: infrastructure, minor

#2046 Replace tasks list providers with id-based providing
  app/lib/common/actions/redact_content.dart
  app/lib/features/events/widgets/change_date_sheet.dart
  app/lib/features/home/widgets/my_tasks.dart
  app/lib/features/space/widgets/space_sections/tasks_section.dart
  app/lib/features/tasks/models/tasks.dart
  app/lib/features/tasks/pages/tasks_list_page.dart
  app/lib/features/tasks/providers/notifiers.dart
  app/lib/features/tasks/providers/tasklists_providers.dart
  app/lib/features/tasks/sheets/create_update_task_item.dart
  app/lib/features/tasks/sheets/create_update_task_list.dart
  app/lib/features/tasks/widgets/task_item.dart
  app/lib/features/tasks/widgets/task_items_list_widget.dart
  app/lib/features/tasks/widgets/task_list_item_card.dart
  app/pubspec.lock
  packages/acter_notifify/.flutter-plugins
  packages/acter_notifify/.flutter-plugins-dependencies
  packages/acter_notifify/.gitignore
Labels: flutter

#2059 Bumping threshold for shake up a bunch
  app/lib/features/home/pages/home_shell.dart
Labels: minor

#2060 Update latest weblate - adds Spanish & Arabic
  .changes/2060-spanish-and-arabic.md
  app/lib/features/settings/model/language_model.dart
  app/lib/l10n/app_ar.arb
  app/lib/l10n/app_en.arb
Labels: translations

#2061 Add severe log for error cases of all try-catch statements
  packages/acter_notifify/lib/platform/android.dart
  packages/rust_sdk/lib/acter_flutter_sdk.dart
Labels: flutter, minor

#2065 Workflow fixes
  .github/workflows/build-docs.yml
  .github/workflows/deploy-nightly.yml
  .github/workflows/deploy-release.yml
Labels: build, infrastructure

#2070 Rename process from app to acter
  .changes/2070-windows-process-name
  app/windows/runner/Runner.rc
Labels: t-windows

#2029 Desktop backgrounding support
  .changes/2029-backgrounding-and-tray-icon.md
  app/assets/icon/comment.svg
  app/assets/icon/tray_icon.ico
  app/assets/icon/tray_icon.png
  app/assets/icon/tray_icon.svg
  app/assets/images/forgot_password.svg
  app/assets/images/intro.png
  app/assets/videos/.gitkeep
  app/assets/videos/video.mp4
  app/lib/config/desktop.dart
  app/lib/features/auth/pages/forgot_password.dart
  app/lib/features/intro/pages/intro_page.dart
  app/lib/main.dart
  app/linux/my_application.cc
  app/macos/Podfile.lock
  app/macos/Runner/AppDelegate.swift
  app/pubspec.lock
  app/pubspec.yaml
  app/windows/runner/main.cpp
Labels: t-desktop, merge post release only

#2053 [Rust SDK] Switch to Display System
  native/acter/api.rsh
  native/acter/src/api.rs
  native/acter/src/api/common.rs
  native/acter/src/api/pins.rs
  native/acter/src/api/tasks.rs
  native/core/src/events/calendar.rs
  native/core/src/events/common.rs
  native/core/src/events/common/categories.rs
  native/core/src/events/common/display.rs
  native/core/src/events/pins.rs
  native/core/src/events/tasks.rs
  packages/rust_sdk/lib/acter_flutter_sdk_ffi.dart
Labels: rust

#2067 Refactoring : Pin Details and Attachments
  .changes/2067-refactor-pin-details.md
  app/integration_test/tests/pins.dart
  app/lib/common/themes/acter_theme.dart
  app/lib/common/widgets/edit_link_sheet.dart
  app/lib/common/widgets/space_name_widget.dart
  app/lib/features/attachments/actions/add_edit_link_bottom_sheet.dart
  app/lib/features/attachments/actions/handle_selected_attachments.dart
  app/lib/features/attachments/widgets/attachment_item.dart
  app/lib/features/attachments/widgets/attachment_selection_options.dart
  app/lib/features/events/pages/event_list_page.dart
  app/lib/features/home/widgets/space_chip.dart
  app/lib/features/pins/Utils/pins_utils.dart
  app/lib/features/pins/actions/edit_pin_actions.dart
  app/lib/features/pins/actions/reduct_pin_action.dart
  app/lib/features/pins/actions/report_pin_action.dart
  app/lib/features/pins/actions/set_pin_links.dart
  app/lib/features/pins/pages/create_pin_page.dart
  app/lib/features/pins/pages/pin_details_page.dart
  app/lib/features/pins/pages/pin_page.dart
  app/lib/features/pins/pages/pins_list_page.dart
  app/lib/features/pins/widgets/fake_link_attachment_item.dart
  app/lib/features/pins/widgets/pin_item.dart
  app/lib/features/tasks/pages/tasks_list_page.dart
  app/lib/l10n/app_en.arb
  app/lib/router/general_router.dart
  app/lib/router/shell_routers/home_shell_router.dart
Labels: s-pins

#2076 Add tray-icon-support for linux build
  .github/workflows/build-app.yml
  .github/workflows/deploy-demo.yml
Labels: build, build-demo, minor

#2072 Device Calendar Sync
  .changes/2072-calendar-sync.md
  app/android/app/src/main/AndroidManifest.xml
  app/integration_test/tests/bug_reporter.dart
  app/ios/Podfile.lock
  app/ios/Runner/AppDelegate.swift
  app/ios/Runner/Info.plist
  app/lib/common/utils/feature_flagger.dart
  app/lib/common/utils/utils.dart
  app/lib/config/app_shell.dart
  app/lib/features/auth/pages/logged_out_screen.dart
  app/lib/features/calendar_sync/calendar_sync.dart
  app/lib/features/calendar_sync/providers/events_to_sync_provider.dart
  app/lib/features/home/widgets/sidebar_widget.dart
  app/lib/features/search/widgets/quick_actions_builder.dart
  app/lib/features/settings/pages/labs_page.dart
  app/lib/features/settings/providers/notifiers/labs_features.dart
  app/lib/features/settings/providers/settings_providers.dart
  app/lib/features/settings/widgets/labs_notifications_settings_tile.dart
  app/lib/l10n/app_en.arb
  app/lib/router/router.dart
  app/lib/router/utils.dart
  app/pubspec.lock
  app/pubspec.yaml
Labels: infrastructure, s-calendar, s-integration, merge post release only

#2099 Releasing v1.24.8220
  .changes/2029-backgrounding-and-tray-icon.md
  .changes/2067-refactor-pin-details.md
  .changes/2072-calendar-sync.md
  .changes/2078-fix-chat-search.md
  .changes/2086-limited-spaces-list.md
  .changes/chat-input-fixes.md
Labels: infrastructure, minor

#2077 load and save composer draft for chat room input text
  .changes/chat-compose-draft.md
  app/lib/features/chat/providers/chat_providers.dart
  app/lib/features/chat/utils.dart
  app/lib/features/chat/widgets/custom_input.dart
  app/test/features/chat/custom_input_test.dart
  app/test/helpers/mock_sdk.dart
  app/test/helpers/mocks.dart
  app/test/helpers/room_test_wrapper.dart
  app/test/helpers/utils.dart
Labels: flutter, merge post release only

#2107 Upgrade labs, new dev-default-on-labs
  app/integration_test/tests/tasks.dart
  app/lib/common/utils/utils.dart
  app/lib/features/comments/widgets/comments_section.dart
  app/lib/features/settings/pages/labs_page.dart
Labels: infrastructure, minor

#2108 Upgrading the flutter dependencies
  .github/workflows/build-app.yml
  .github/workflows/build-docs.yml
  .github/workflows/check-flutter-integration-tests.yml
  .github/workflows/check-native.yml
  .github/workflows/check-styles.yml
  app/lib/common/pages/fatal_fail.dart
  app/lib/common/pages/not_found.dart
  app/lib/common/widgets/emoji_picker_widget.dart
  app/lib/config/app_shell.dart
  app/lib/features/chat/providers/notifiers/media_chat_notifier.dart
  app/lib/features/cross_signing/widgets/cross_signing.dart
  app/lib/features/news/news_utils/news_utils.dart
  app/lib/features/super_invites/pages/create.dart
  app/pubspec.lock
  app/pubspec.yaml
Labels: minor

#2098 Reduce accepting timeout to 10 seconds or show an error
  native/acter/src/api/invitation.rs
Labels: bug, rust, infrastructure

#2089 Showing better Error messages
  app/.env
  app/integration_test/tests/bug_reporter.dart
  app/lib/common/providers/common_providers.dart
  app/lib/common/providers/space_providers.dart
  app/lib/common/toolkit/errors/error_dialog.dart
  app/lib/common/toolkit/errors/error_page.dart
  app/lib/common/toolkit/errors/util.dart
  app/lib/common/widgets/spaces/select_space_form_field.dart
  app/lib/common/widgets/spaces/space_info.dart
  app/lib/config/app_shell.dart
  app/lib/features/attachments/widgets/attachment_section.dart
  app/lib/features/bug_report/actions/open_bug_report.dart
  app/lib/features/bug_report/actions/submit_bug_report.dart
  app/lib/features/bug_report/pages/bug_report_page.dart
  app/lib/features/bug_report/providers/bug_report_providers.dart
  app/lib/features/comments/widgets/comments_section.dart
  app/lib/features/home/widgets/sidebar_widget.dart
  app/lib/features/home/widgets/space_chip.dart
  app/lib/features/pins/pages/pin_details_page.dart
  app/lib/features/pins/pages/pins_list_page.dart
  app/lib/features/search/widgets/quick_actions_builder.dart
  app/lib/features/space/pages/space_details_page.dart
  app/lib/features/space/sheets/link_room_sheet.dart
  app/lib/features/space/widgets/space_toolbar.dart
  app/lib/l10n/app_en.arb
  app/lib/router/general_router.dart
  app/pubspec.lock
  app/pubspec.yaml
  app/test/features/pins/error_pages_test.dart
  app/test/features/spaces/error_pages_test.dart
  app/test/helpers/error_helpers.dart
  app/test/helpers/mock_pins_providers.dart
  app/test/helpers/mock_space_providers.dart
  app/test/helpers/test_util.dart
Labels: infrastructure, smooth UX

#2109 Improve the emoji UX
  .changes/2109-emoji-ux.md
  app/lib/common/widgets/emoji_picker_widget.dart
  app/lib/features/chat/widgets/custom_input.dart
  app/lib/features/chat/widgets/emoji/emoji_row.dart
Labels: s-chat

#2096 Fixing calendar action in news creation
  .changes/2996-proper-calendar-event-types.md
  app/lib/features/news/actions/submit_news.dart
  app/lib/features/news/model/news_references_model.dart
  app/lib/features/news/pages/add_news_page.dart
  app/lib/features/news/providers/news_post_editor_providers.dart
  app/lib/features/news/widgets/news_item.dart
Labels: smooth UX, s-news

#2114 Latest Weblate update
  app/lib/l10n/app_de.arb
  app/lib/l10n/app_en.arb
  app/lib/l10n/app_pt.arb
  app/lib/l10n/app_sw.arb
Labels: translations

#2123 Add logger name to log on flutter side
  app/lib/common/utils/logging.dart
Labels: flutter, minor

#2124 Fix timezone bug in some occurrences of timestamp
  app/lib/features/comments/widgets/comment.dart
  app/lib/features/settings/widgets/session_card.dart
Labels: bug, flutter, minor

#2110 Autoactivate Space Features
  .changes/autoactivate-space-features.md
  app/integration_test/support/spaces.dart
  app/integration_test/tests/tasks.dart
  app/lib/common/widgets/scrollable_list_tab_scroller.dart
  app/lib/features/space/actions/activate_feature.dart
  app/lib/features/space/actions/set_acter_feature.dart
  app/lib/features/space/actions/update_feature_power_level.dart
  app/lib/features/space/pages/space_details_page.dart
  app/lib/features/space/providers/space_navbar_provider.dart
  app/lib/features/space/settings/pages/apps_settings_page.dart
  app/lib/features/space/widgets/space_sections/space_actions_section.dart
  app/lib/l10n/app_en.arb
  native/acter/api.rsh
  native/acter/src/api.rs
  native/acter/src/api/settings.rs
  native/acter/src/api/settings/space.rs
  native/core/src/events/settings.rs
  native/core/src/events/settings/space.rs
  packages/rust_sdk/lib/acter_flutter_sdk_ffi.dart
Labels: s-space, merge post release only

#2128 Add Help Center Entry in Settings Page
  app/.env
  app/lib/common/toolkit/menu_item_widget.dart
  app/lib/features/settings/widgets/settings_menu.dart
  app/lib/l10n/app_en.arb
Labels: minor

#2129 disable push message cancelling on linux
  packages/acter_notifify/lib/util.dart
Labels: bug, minor, t-linux, f-push-notifications
