Repository acterglobal/a3, pull requests merged in 2024-10, with the labels that each got.

#2212 Ensure bug reporter only open once
  app/lib/features/bug_report/actions/open_bug_report.dart
  app/pubspec.lock
Labels: bug, flutter, minor

#2213 fix html editor bug on empty document
  app/lib/common/widgets/edit_html_description_sheet.dart
  app/lib/features/news/pages/add_news_page.dart
Labels: bug, s-pins, s-calendar, s-news

#2208 Fix push notifications forward for invites
  .changes/2150-fix-push-for-invites.md
  app/lib/router/router.dart
  app/macos/Podfile.lock
Labels: t-ios, f-push-notifications

#2222 Don't block on notification initialization.
  app/lib/config/notifications/init.dart
  app/lib/main.dart
Labels: bug, t-macos, minor

#2232 Device Calendar Sync debugging
  app/.env
  app/lib/config/app_shell.dart
  app/lib/features/calendar_sync/calendar_sync.dart
  app/lib/features/calendar_sync/providers/events_to_sync_provider.dart
  app/lib/features/settings/pages/labs_page.dart
  packages/acter_notifify/lib/matrix.dart
Labels: s-calendar, minor

#2233 Use let extension to remove bang operator from nullable variables
  app/lib/common/actions/redact_content.dart
  app/lib/common/actions/report_content.dart
  app/lib/common/providers/notifiers/sync_notifier.dart
  app/lib/common/providers/room_providers.dart
  app/lib/common/providers/space_providers.dart
  app/lib/common/themes/app_theme.dart
  app/lib/common/toolkit/errors/error_dialog.dart
  app/lib/common/toolkit/errors/inline_error_button.dart
  app/lib/common/utils/utils.dart
  app/lib/common/widgets/acter_icon_picker/acter_icon_widget.dart
  app/lib/common/widgets/acter_icon_picker/picker/acter_icon_picker.dart
Labels: flutter

#2238 Show proper info of subspaces and space chats, hide unaccessible entries.
  app/lib/common/providers/space_providers.dart
  app/lib/features/categories/model/CategoryModelLocal.dart
  app/lib/features/categories/utils/category_utils.dart
  app/lib/features/chat/pages/sub_chats_page.dart
  app/lib/features/spaces/pages/sub_spaces_page.dart
  app/test/features/spaces/spacechats_test.dart
  app/test/features/spaces/subspaces_test.dart
  app/test/helpers/mock_room_providers.dart
  app/test/helpers/mock_space_providers.dart
Labels: bug, flutter, minor

#2221 [smallfix] Miscellaneous fixes
  app/lib/common/providers/network_provider.dart
  app/lib/common/providers/room_providers.dart
  app/lib/common/utils/constants.dart
  app/lib/features/calendar_sync/calendar_sync.dart
  app/lib/features/chat/widgets/emoji/emoji_row.dart
  app/lib/features/files/actions/pick_image.dart
Labels: flutter, minor

#2244 Remove bang operator from nullable variables [3]
  app/lib/common/widgets/acter_video_player.dart
  app/lib/common/widgets/add_button_with_can_permission.dart
  app/lib/common/widgets/blinking_text.dart
  app/lib/common/widgets/default_dialog.dart
  app/lib/common/widgets/emoji_picker_widget.dart
  app/lib/common/widgets/empty_state_widget.dart
  app/lib/common/widgets/html_editor.dart
  app/lib/common/widgets/scrollable_list_tab_scroller.dart
  app/lib/common/widgets/spaces/select_space_form_field.dart
  app/lib/common/widgets/visibility/room_visibility_item.dart
Labels: flutter, minor

#2245 Remove bang operator from nullable variables [4]
  app/lib/common/widgets/sliver_scaffold.dart
  app/lib/features/activities/pages/activities_page.dart
  app/lib/features/attachments/widgets/attachment_container.dart
  app/lib/features/attachments/widgets/attachment_item.dart
  app/lib/features/attachments/widgets/attachment_selection_options.dart
  app/lib/features/attachments/widgets/views/file_view.dart
  app/lib/features/attachments/widgets/views/image_view.dart
  app/lib/features/attachments/widgets/views/video_view.dart
  app/lib/features/auth/pages/forgot_password.dart
  app/lib/features/bug_report/pages/bug_report_page.dart
Labels: flutter, minor

#2250 Refactor L10n
  app/lib/features/chat/widgets/convo_card.dart
  app/lib/l10n/app_ar.arb
  app/lib/l10n/app_de.arb
  app/lib/l10n/app_en.arb
  app/lib/l10n/app_es.arb
  app/lib/l10n/app_fr.arb
  app/lib/l10n/app_pl.arb
  app/lib/l10n/app_sw.arb
  app/lib/l10n/app_ur.arb
Labels: flutter, minor

#2251 Refactor l10n [1]
  app/lib/common/actions/close_room.dart
  app/lib/common/actions/redact_content.dart
  app/lib/common/actions/report_content.dart
  app/lib/common/dialogs/deactivation_confirmation.dart
  app/lib/common/dialogs/logout_confirmation.dart
  app/lib/common/pages/fatal_fail.dart
  app/lib/common/skeletons/general_list_skeleton_widget.dart
  app/lib/common/tutorial_dialogs/bottom_navigation_tutorials/bottom_navigation_tutorials.dart
  app/lib/common/tutorial_dialogs/space_overview_tutorials/create_or_join_space_tutorials.dart
  app/lib/common/tutorial_dialogs/target_focus.dart
Labels: flutter, minor

#2252 Refactor l10n [2]
  app/lib/common/tutorial_dialogs/space_overview_tutorials/space_overview_tutorials.dart
  app/lib/common/utils/utils.dart
  app/lib/common/utils/validation_utils.dart
  app/lib/common/widgets/chat/edit_room_description_sheet.dart
  app/lib/common/widgets/edit_html_description_sheet.dart
  app/lib/common/widgets/edit_plain_description_sheet.dart
  app/lib/common/widgets/edit_title_sheet.dart
  app/lib/common/widgets/icons/tasks_icon.dart
  app/lib/common/widgets/room/room_hierarchy_join_button.dart
  app/lib/common/widgets/room/room_hierarchy_options_menu.dart
Labels: flutter, minor

#2254 Refactor l10n [3]
  app/lib/common/widgets/room/select_room_drawer.dart
  app/lib/common/widgets/spaces/select_space_form_field.dart
  app/lib/common/widgets/visibility/room_visibilty_type.dart
  app/lib/common/widgets/visibility/visibility_chip.dart
  app/lib/features/activities/pages/activities_page.dart
  app/lib/features/activities/widgets/invitation_card.dart
  app/lib/features/attachments/actions/add_edit_link_bottom_sheet.dart
  app/lib/features/attachments/widgets/attachment_item.dart
  app/lib/features/attachments/widgets/attachment_section.dart
  app/lib/features/attachments/widgets/attachment_selection_options.dart
Labels: flutter, minor

#2255 Add Urdu
  .changes/2239-urdu.md
  app/lib/features/settings/model/language_model.dart
  app/lib/l10n/app_en.arb
Labels: translations

#2257 Refactor l10n [4]
  app/lib/features/auth/pages/forgot_password.dart
  app/lib/features/auth/pages/logged_out_screen.dart
  app/lib/features/auth/pages/login_page.dart
  app/lib/features/auth/pages/register_page.dart
  app/lib/features/backups/dialogs/provide_recovery_key_dialog.dart
  app/lib/features/backups/dialogs/show_confirm_disabling.dart
  app/lib/features/backups/dialogs/show_recovery_key.dart
  app/lib/features/backups/widgets/backup_state_widget.dart
  app/lib/features/bug_report/pages/bug_report_page.dart
  app/lib/features/categories/organize_categories_page.dart
Labels: flutter, minor

#2258 Refactor l10n [5]
  app/lib/features/categories/actions/save_categories.dart
  app/lib/features/categories/widgets/add_edit_category.dart
  app/lib/features/categories/widgets/category_header_view.dart
  app/lib/features/chat/actions/create_chat.dart
  app/lib/features/chat/dialogs/encryption_info_drawer.dart
  app/lib/features/chat/pages/room_page.dart
  app/lib/features/chat/pages/room_profile_page.dart
  app/lib/features/chat/pages/sub_chats_page.dart
  app/lib/features/chat/utils.dart
  app/lib/features/chat/widgets/chats_list.dart
Labels: flutter, minor

#2259 Refactor l10n [6]
  app/lib/features/chat/widgets/convo_card.dart
  app/lib/features/chat/widgets/create_chat.dart
  app/lib/features/chat/widgets/custom_input.dart
  app/lib/features/chat/widgets/member_list.dart
  app/lib/features/chat/widgets/message_actions.dart
  app/lib/features/chat/widgets/messages/membership_update.dart
  app/lib/features/chat/widgets/rooms_list.dart
  app/lib/features/chat/widgets/skeletons/members_list_skeleton_widget.dart
  app/lib/features/comments/widgets/comments_list.dart
  app/lib/features/comments/widgets/create_comment.dart
Labels: flutter, minor

#2260 Refactor l10n [6]
  app/lib/features/cross_signing/views/request_cancelled.dart
  app/lib/features/cross_signing/views/request_done.dart
  app/lib/features/cross_signing/views/request_ready.dart
  app/lib/features/cross_signing/views/sas_accepted.dart
  app/lib/features/cross_signing/views/sas_cancelled.dart
  app/lib/features/cross_signing/views/sas_keys_exchanged.dart
  app/lib/features/cross_signing/views/sas_started.dart
  app/lib/features/cross_signing/views/verification_request.dart
  app/lib/features/events/pages/create_event_page.dart
  app/lib/features/events/pages/event_details_page.dart
Labels: flutter, minor

#2261 Refactor l10n [8]
  app/lib/features/events/pages/event_list_page.dart
  app/lib/features/events/utils/events_utils.dart
  app/lib/features/events/widgets/change_date_sheet.dart
  app/lib/features/events/widgets/event_item.dart
  app/lib/features/events/widgets/participants_list.dart
  app/lib/features/events/widgets/skeletons/event_details_skeleton_widget.dart
  app/lib/features/events/widgets/skeletons/event_item_skeleton_widget.dart
  app/lib/features/events/widgets/skeletons/event_list_skeleton_widget.dart
  app/lib/features/home/pages/dashboard.dart
  app/lib/features/home/widgets/my_events.dart
  app/lib/features/home/widgets/my_spaces_section.dart
  app/lib/features/home/widgets/my_tasks.dart
  app/lib/features/home/widgets/sidebar_widget.dart
  app/lib/features/home/widgets/space_chip.dart
  app/lib/features/intro/pages/intro_page.dart
  app/lib/features/intro/pages/intro_profile.dart
  app/lib/features/invite_members/pages/invite_individual_users.dart
  app/lib/features/invite_members/pages/invite_page.dart
  app/lib/features/invite_members/pages/invite_space_members.dart
  app/lib/features/invite_members/pages/share_invite_code.dart
Labels: flutter, minor

#2262 Refactor l10n [9]
  app/lib/features/invite_members/widgets/direct_invite.dart
  app/lib/features/invite_members/widgets/invite_code_ui.dart
  app/lib/features/invite_members/widgets/space_member_invite_card.dart
  app/lib/features/member/dialogs/show_block_user_dialog.dart
  app/lib/features/member/dialogs/show_change_power_level_dialog.dart
  app/lib/features/member/dialogs/show_kick_and_ban_user_dialog.dart
  app/lib/features/member/dialogs/show_kick_user_dialog.dart
  app/lib/features/member/dialogs/show_unblock_user_dialog.dart
  app/lib/features/member/widgets/member_info_drawer.dart
  app/lib/features/member/widgets/message_user_button.dart
  app/lib/features/member/widgets/user_builder.dart
Labels: flutter, minor

#2264 Refactor l10n [11]
  app/lib/common/dialogs/deactivation_confirmation.dart
  app/lib/features/chat/widgets/create_chat.dart
  app/lib/features/chat/widgets/mention_profile_builder.dart
  app/lib/features/news/widgets/news_post_editor/post_attachment_options.dart
  app/lib/features/news/widgets/news_post_editor/select_action_item.dart
  app/lib/features/onboarding/pages/analytics_opt_in_page.dart
  app/lib/features/onboarding/pages/link_email_page.dart
  app/lib/features/onboarding/pages/save_username_page.dart
  app/lib/features/onboarding/pages/upload_avatar_page.dart
  app/lib/features/pins/actions/pin_update_actions.dart
  app/lib/features/pins/actions/report_pin_action.dart
  app/lib/features/pins/pages/create_pin_page.dart
  app/lib/features/pins/pages/pin_details_page.dart
  app/lib/features/pins/pages/pins_list_page.dart
  app/lib/features/pins/widgets/fake_link_attachment_item.dart
Labels: flutter, minor

#2265 Refactor l10n [12]
  app/lib/features/pins/widgets/pin_attachment_options.dart
  app/lib/features/profile/pages/my_profile_page.dart
  app/lib/features/public_room_search/pages/search_public_directory.dart
  app/lib/features/public_room_search/widgets/maybe_direct_room_action_widget.dart
  app/lib/features/public_room_search/widgets/public_room_item.dart
  app/lib/features/public_room_search/widgets/public_room_search.dart
  app/lib/features/public_room_search/widgets/server_selection_field.dart
  app/lib/features/room/widgets/notifications_settings_tile.dart
  app/lib/features/search/pages/quick_jump.dart
  app/lib/features/search/widgets/pins_builder.dart
Labels: flutter, minor

#2267 Refactor l10n [14]
  app/lib/features/space/actions/update_feature_power_level.dart
  app/lib/features/space/dialogs/leave_space.dart
  app/lib/features/space/dialogs/suggested_rooms.dart
  app/lib/features/space/pages/members_page.dart
  app/lib/features/space/pages/space_details_page.dart
  app/lib/features/space/settings/pages/apps_settings_page.dart
  app/lib/features/space/settings/pages/notification_configuration_page.dart
  app/lib/features/space/settings/widgets/space_settings_menu.dart
  app/lib/features/space/sheets/link_room_sheet.dart
  app/lib/features/space/widgets/related/chats_helpers.dart
  app/lib/features/space/widgets/space_sections/about_section.dart
  app/lib/features/space/widgets/space_sections/chats_section.dart
  app/lib/features/space/widgets/space_sections/events_section.dart
  app/lib/features/space/widgets/space_sections/members_section.dart
  app/lib/features/space/widgets/space_sections/news_section.dart
  app/lib/features/space/widgets/space_sections/space_actions_section.dart
  app/lib/features/space/widgets/space_sections/spaces_section.dart
  app/lib/features/space/widgets/space_sections/tasks_section.dart
Labels: flutter, minor

#2268 Refactor l10n [15]
  app/lib/features/space/widgets/space_toolbar.dart
  app/lib/features/spaces/actions/create_space.dart
  app/lib/features/spaces/pages/create_space_page.dart
  app/lib/features/spaces/pages/spaces_page.dart
  app/lib/features/spaces/pages/sub_spaces_page.dart
  app/lib/features/super_invites/dialogs/redeem_dialog.dart
  app/lib/features/super_invites/pages/create.dart
  app/lib/features/super_invites/pages/super_invites.dart
  app/lib/features/super_invites/widgets/redeem_token.dart
  app/lib/features/tasks/actions/update_tasklist.dart
Labels: flutter, minor

#2269 Refactor l10n [16]
  app/lib/features/tasks/pages/task_item_detail_page.dart
  app/lib/features/tasks/pages/task_list_details_page.dart
  app/lib/features/tasks/pages/tasks_list_page.dart
  app/lib/features/tasks/sheets/create_update_task_item.dart
  app/lib/features/tasks/sheets/create_update_task_list.dart
  app/lib/features/tasks/widgets/all_tasks_done.dart
  app/lib/features/tasks/widgets/due_chip.dart
  app/lib/features/tasks/widgets/due_picker.dart
  app/lib/features/tasks/widgets/skeleton/task_item_detail_page_skeleton.dart
  app/lib/features/tasks/widgets/skeleton/task_items_skeleton.dart
Labels: flutter, minor

#2270 Refactor l10n [17]
  app/lib/features/tasks/widgets/empty_task_list.dart
  app/lib/features/tasks/widgets/task_item.dart
  app/lib/features/tasks/widgets/task_items_list_widget.dart
  app/lib/features/tasks/widgets/task_list_item_card.dart
  app/test/features/auth/pages/login_page_test.dart
Labels: flutter, minor

#2272 [smallfix] Miscellaneous fixes
  app/integration_test/support/login.dart
  app/integration_test/support/super_invites.dart
  app/lib/common/widgets/like_button.dart
  app/lib/common/widgets/render_html.dart
  app/lib/features/backups/widgets/backup_state_widget.dart
  app/lib/features/bug_report/pages/bug_report_page.dart
  app/lib/features/categories/organize_categories_page.dart
  app/lib/features/chat/providers/room_list_filter_provider.dart
  app/lib/features/chat/widgets/convo_card.dart
  app/lib/features/comments/widgets/comment.dart
  app/lib/features/public_room_search/pages/search_public_directory.dart
  app/lib/features/space/sheets/link_room_sheet.dart
  app/lib/features/super_invites/pages/super_invites.dart
Labels: flutter, minor

#2249 Remove bang operator from nullable variables [6]
  app/lib/common/utils/utils.dart
  app/lib/features/chat/utils.dart
  app/lib/features/chat/widgets/convo_card.dart
  app/lib/features/chat/widgets/create_chat.dart
  app/lib/features/chat/widgets/custom_input.dart
  app/lib/features/chat/widgets/image_message_builder.dart
  app/lib/features/chat/widgets/video_message_builder.dart
  app/lib/features/cross_signing/widgets/cross_signing.dart
  app/lib/features/events/pages/event_list_page.dart
  app/lib/features/events/providers/notifiers/event_notifiers.dart
  app/lib/features/events/widgets/event_item.dart
  app/lib/features/files/actions/file_share.dart
  app/lib/features/profile/pages/my_profile_page.dart
  app/lib/features/spaces/pages/create_space_page.dart
Labels: flutter

#2277 notificationsCount is not supported on linux and leads to failures
  .changes/2220-destroy-system-tray.md
  .changes/ben-disable-getActiveNotifications-on-linux.md
  packages/acter_notifify/lib/util.dart
Labels: bug, minor, t-linux, f-push-notifications

#2276 Routing-based chat-ng checking
  app/lib/common/utils/routes.dart
  app/lib/common/utils/utils.dart
  app/lib/features/chat/chat-ng/pages/ng_profile_page.dart
  app/lib/features/chat/chat-ng/pages/room_page_ng.dart
  app/lib/features/chat/chat-ng/widgets/chat_input_ng.dart
  app/lib/features/chat/chat-ng/widgets/chat_room_ng.dart
  app/lib/features/chat/widgets/chat_layout_builder.dart
  app/lib/features/chat/widgets/rooms_list.dart
  app/lib/features/chat_ng/widgets/rooms_list.dart
  app/lib/l10n/app_en.arb
  app/lib/router/shell_routers/chat_shell_router.dart
Labels: flutter, infrastructure, s-chat

#2278 fix convo card trailing
  app/lib/features/chat/widgets/convo_card.dart
Labels: bug, s-chat, minor

#2274 Remove bang operator from nullable variables [7]
  app/integration_test/support/chats.dart
  app/integration_test/support/setup.dart
  app/integration_test/support/super_invites.dart
  app/lib/common/providers/space_providers.dart
  app/lib/common/widgets/acter_search_widget.dart
  app/lib/features/bug_report/pages/bug_report_page.dart
  app/lib/features/chat/widgets/chats_list.dart
  app/lib/features/home/widgets/my_events.dart
  app/lib/features/home/widgets/my_spaces_section.dart
Labels: flutter, minor

#2283 [smallfix] Miscellaneous fixing
  app/lib/common/actions/redact_content.dart
  app/lib/common/providers/notifiers/sync_notifier.dart
  app/lib/common/providers/room_providers.dart
  app/lib/common/providers/space_providers.dart
  app/lib/common/toolkit/errors/error_dialog.dart
  app/lib/common/toolkit/errors/inline_error_button.dart
  app/lib/common/widgets/acter_icon_picker/picker/acter_icon_picker.dart
  app/lib/common/widgets/add_button_with_can_permission.dart
  app/lib/common/widgets/avatar/full_screen_avatar_page.dart
  app/lib/common/widgets/emoji_picker_widget.dart
  app/lib/common/widgets/html_editor.dart
  app/lib/common/widgets/room/brief_room_list_entry.dart
  app/lib/common/widgets/room/room_avatar_builder.dart
  app/lib/common/widgets/sliver_scaffold.dart
  app/lib/common/widgets/spaces/select_space_form_field.dart
  app/lib/features/activities/pages/activities_page.dart
  app/lib/features/auth/pages/forgot_password.dart
  app/lib/features/bug_report/pages/bug_report_page.dart
  app/lib/features/categories/actions/save_categories.dart
  app/lib/features/categories/organize_categories_page.dart
  app/lib/features/chat/providers/notifiers/media_chat_notifier.dart
  app/lib/features/chat/widgets/bubble_builder.dart
  app/lib/features/chat/widgets/convo_card.dart
  app/lib/features/chat/widgets/create_chat.dart
  app/lib/features/chat/widgets/custom_input.dart
  app/lib/features/events/pages/create_event_page.dart
  app/lib/features/events/widgets/event_item.dart
  app/lib/features/member/widgets/user_builder.dart
  app/lib/features/pins/pages/create_pin_page.dart
  app/lib/features/public_room_search/widgets/public_room_search.dart
  app/lib/features/space/dialogs/suggested_rooms.dart
  app/lib/features/space/sheets/link_room_sheet.dart
  app/lib/features/tasks/sheets/create_update_task_list.dart
  app/test/common/option_extension_test.dart
Labels: flutter, minor

#2284 [smallfix] Miscellaneous fixing
  app/lib/common/actions/close_room.dart
  app/lib/common/actions/redact_content.dart
  app/lib/common/actions/report_content.dart
  app/lib/common/actions/show_limited_space_list.dart
  app/lib/common/actions/show_parent_space_list.dart
  app/lib/common/dialogs/deactivation_confirmation.dart
  app/lib/common/providers/keyboard_visbility_provider.dart
  app/lib/config/app_shell.dart
  app/lib/config/desktop.dart
  app/lib/config/notifications/init.dart
  app/lib/features/activities/providers/notifiers/invitation_list_notifier.dart
  app/lib/features/bug_report/actions/submit_bug_report.dart
  app/lib/features/bug_report/pages/bug_report_page.dart
  app/lib/features/events/pages/create_event_page.dart
  app/lib/features/events/utils/events_utils.dart
  app/lib/features/events/widgets/change_date_sheet.dart
  app/lib/features/labs/feature_flagger.dart
  app/lib/features/member/widgets/user_builder.dart
  app/lib/features/news/actions/submit_news.dart
  app/lib/features/news/pages/add_news_page.dart
  app/lib/features/news/widgets/news_item_slide/image_slide.dart
  app/lib/features/news/widgets/news_item_slide/news_slide_actions.dart
  app/lib/features/news/widgets/news_item_slide/video_slide.dart
  app/lib/features/pins/actions/pin_update_actions.dart
  app/lib/features/pins/actions/select_pin_attachments.dart
  app/lib/features/pins/pages/create_pin_page.dart
  app/lib/features/pins/pages/pin_details_page.dart
  app/lib/features/pins/providers/notifiers/edit_state_notifier.dart
  app/lib/features/pins/widgets/fake_link_attachment_item.dart
  app/lib/features/pins/widgets/pin_list_item_widget.dart
  app/lib/features/pins/widgets/pin_list_widget.dart
  app/lib/features/room/actions/avatar_upload.dart
  app/lib/features/settings/pages/notifications_page.dart
  app/lib/features/settings/providers/notifiers/devices_notifier.dart
  app/lib/features/space/actions/activate_feature.dart
  app/lib/features/space/actions/set_acter_feature.dart
  app/lib/features/space/actions/set_space_topic.dart
  app/lib/features/space/actions/update_feature_power_level.dart
  app/lib/features/space/dialogs/leave_space.dart
  app/lib/features/space/dialogs/suggested_rooms.dart
  app/lib/features/space/providers/suggested_provider.dart
  app/lib/features/space/widgets/space_info.dart
  app/lib/features/tasks/actions/update_tasklist.dart
  app/lib/features/tasks/widgets/task_item.dart
  app/lib/features/tasks/widgets/task_items_list_widget.dart
  app/lib/features/tasks/widgets/task_list_item_card.dart
  app/lib/router/providers/router_providers.dart
  packages/acter_notifify/lib/acter_notifify.dart
  packages/acter_notifify/lib/matrix.dart
Labels: flutter, minor

#2285 [smallfix] Miscellaneous fixings
  app/lib/common/widgets/sliver_scaffold.dart
  app/lib/features/events/pages/create_event_page.dart
  app/lib/features/events/widgets/event_item.dart
Labels: flutter, minor

#2273 All Space list with search option
  app/lib/features/spaces/pages/space_list_page.dart
  app/lib/features/spaces/pages/spaces_page.dart
  app/lib/features/spaces/providers/space_list_provider.dart
  app/lib/features/spaces/widgets/space_list_empty_state.dart
  app/lib/features/spaces/widgets/space_list_skeleton.dart
  app/lib/features/spaces/widgets/space_list_widget.dart
  app/lib/router/shell_routers/home_shell_router.dart
Labels: flutter

#2271 Refactoring news editor
  .changes/2271-news-page.md
  .github/workflows/check-flutter-unittest.yml
  .github/workflows/check-native.yml
  .github/workflows/check-rust-integration-tests.yml
  app/.gitignore
  app/lib/common/utils/utils.dart
  app/lib/features/news/actions/submit_news.dart
  app/lib/features/news/model/keys.dart
  app/lib/features/news/model/news_references_model.dart
  app/lib/features/news/news_utils/news_utils.dart
  app/lib/features/news/pages/add_news_page.dart
  app/lib/features/news/providers/news_post_editor_providers.dart
  app/lib/l10n/app_en.arb
  app/pubspec.lock
  app/pubspec.yaml
  app/test/features/chat/messages/image_message_test.dart
  app/test/features/news/news_editor_test.dart
  app/test/helpers/mock_chat_providers.dart
  app/test/helpers/mock_event_providers.dart
  app/test/helpers/mock_image_provider.dart
  app/test/helpers/mock_pins_providers.dart
  app/test/helpers/mock_room_providers.dart
  app/test/helpers/mock_space_providers.dart
  app/test/helpers/mock_tasks_providers.dart
  app/test/helpers/mocks.dart
Labels: flutter, s-news

#2290 Fix NDK 27 x84_64 target
  native/acter/build.rs
Labels: minor, dev-breaking

#2291 Additional test and fix for event data updates
  .changes/2291-calendar-sync-event-details.md
  app/lib/features/calendar_sync/calendar_sync.dart
  app/test/features/calendar_sync/calendar_sync_test.dart
Labels: flutter, s-calendar, minor

#2296 Fix double redaction bug
  native/core/src/executor.rs
  native/core/src/models.rs
  native/core/src/models/test.rs
Labels: rust, minor

#2286 Remove bang operator from nullable variables [8]
  app/lib/features/home/widgets/sidebar_widget.dart
  app/lib/features/invite_members/pages/invite_individual_users.dart
  app/lib/features/invite_members/widgets/invite_code_ui.dart
  app/lib/features/member/widgets/member_info_drawer.dart
  app/lib/features/member/widgets/user_builder.dart
  app/lib/features/news/actions/submit_news.dart
  app/lib/features/news/pages/add_news_page.dart
  app/lib/features/news/providers/news_post_editor_providers.dart
  app/lib/features/news/providers/notifiers/news_list_notifier.dart
  app/lib/features/news/widgets/news_item_slide/image_slide.dart
Labels: flutter, minor

#2298 [smallfix] Miscellaneous fixes
  app/lib/features/chat/pages/sub_chats_page.dart
  app/lib/features/spaces/pages/sub_spaces_page.dart
  app/lib/l10n/app_en.arb
  app/lib/router/router.dart
  native/acter/build.rs
  native/core/src/events/settings/space.rs
  native/core/src/executor.rs
  native/file-event-cache/Readme.md
  native/media-cache-wrapper/Readme.md
Labels: flutter, rust, minor

#2300 Remove bang operator from nullable variables [9]
  app/lib/common/utils/utils.dart
  app/lib/features/home/widgets/space_chip.dart
  app/lib/features/news/actions/submit_news.dart
  app/lib/features/news/widgets/news_grid_view.dart
  app/lib/features/news/widgets/news_item_slide/video_slide.dart
  app/lib/features/news/widgets/news_post_editor/news_slide_options.dart
  app/lib/features/news/widgets/news_post_editor/post_attachment_options.dart
  app/lib/features/onboarding/pages/upload_avatar_page.dart
  app/lib/features/pins/pages/create_pin_page.dart
  app/lib/features/pins/pages/pins_list_page.dart
  app/lib/features/pins/providers/notifiers/edit_state_notifier.dart
Labels: flutter, minor

#2302 Remove bang operator from nullable variables [10]
  app/lib/features/pins/widgets/pin_list_widget.dart
  app/lib/features/public_room_search/widgets/maybe_direct_room_action_widget.dart
  app/lib/features/public_room_search/widgets/server_selection_field.dart
  app/lib/features/settings/pages/notifications_page.dart
  app/lib/features/settings/widgets/app_notifications_settings_tile.dart
  app/lib/features/settings/widgets/options_settings_tile.dart
  app/lib/features/settings/widgets/settings_menu.dart
  app/lib/features/space/dialogs/suggested_rooms.dart
  app/lib/features/space/widgets/loading_convo_card.dart
  app/lib/features/space/widgets/space_sections/section_header.dart
  app/lib/features/space/widgets/space_sections/space_actions_section.dart
  app/lib/features/spaces/widgets/space_list_widget.dart
Labels: flutter, minor

#2303 Remove bang operator from nullable variables [11]
  app/lib/features/spaces/pages/create_space_page.dart
  app/lib/features/spaces/pages/space_list_page.dart
  app/lib/features/super_invites/pages/create.dart
  app/lib/features/tasks/pages/tasks_list_page.dart
  app/lib/features/tasks/sheets/create_update_task_item.dart
  app/lib/features/tasks/sheets/create_update_task_list.dart
  app/lib/features/tasks/widgets/due_chip.dart
  app/lib/features/tasks/widgets/due_picker.dart
  app/lib/features/tasks/widgets/task_item.dart
  app/lib/router/router.dart
Labels: flutter, minor

#2304 Testing BookmarkActionWidget
  app/lib/features/bookmarks/widgets/bookmark_action.dart
  app/test/features/bookmarks/bookmark_action_test.dart
  app/test/helpers/mock_bookmarks.dart
Labels: tech-debt, minor

#2299 Auto-updating Event Details via riverpod "utcNowProvider"
  .changes/2299-updating-events.md
  app/lib/common/widgets/event/event_selector_drawer.dart
  app/lib/features/calendar_sync/providers/events_to_sync_provider.dart
  app/lib/features/datetime/providers/notifiers/now_notifier.dart
  app/lib/features/datetime/providers/utc_now_provider.dart
  app/lib/features/events/pages/event_details_page.dart
  app/lib/features/events/pages/event_list_page.dart
  app/lib/features/events/providers/event_providers.dart
  app/lib/features/events/providers/event_type_provider.dart
  app/lib/features/events/widgets/event_date_widget.dart
  app/lib/features/events/widgets/event_item.dart
  app/lib/features/home/widgets/my_events.dart
  app/lib/features/news/pages/add_news_page.dart
  app/lib/features/news/widgets/news_item_slide/news_slide_actions.dart
  app/lib/features/space/widgets/space_sections/events_section.dart
Labels: bug, flutter, s-calendar

#2307 Remove bang operator from nullable variables [12]
  app/lib/features/attachments/providers/notifiers/attachments_notifiers.dart
  app/lib/features/attachments/widgets/views/file_view.dart
  app/lib/features/attachments/widgets/views/image_view.dart
  app/lib/features/attachments/widgets/views/video_view.dart
  app/lib/features/calendar_sync/calendar_sync.dart
  app/lib/features/chat/providers/notifiers/chat_room_notifier.dart
  app/lib/features/chat/widgets/convo_card.dart
  app/lib/features/chat/widgets/custom_input.dart
  app/lib/features/labs/feature_flagger.dart
  app/lib/features/public_room_search/widgets/maybe_direct_room_action_widget.dart
  app/lib/features/tasks/pages/task_item_detail_page.dart
Labels: flutter, minor

#2308 Remove bang operator from nullable variables [13]
  app/lib/features/chat/widgets/emoji/emoji_container.dart
  app/lib/features/cli/commands/settings.dart
  app/lib/features/labs/feature_flagger.dart
  app/lib/router/general_router.dart
  app/lib/router/shell_routers/chat_shell_router.dart
  app/lib/router/shell_routers/home_shell_router.dart
Labels: flutter, minor

#2311 Remove bang operator from nullable variables [14]
  app/lib/common/widgets/html_editor.dart
  app/lib/common/widgets/sliver_scaffold.dart
  app/lib/common/widgets/spaces/select_space_form_field.dart
  app/lib/features/attachments/widgets/attachment_container.dart
  app/lib/features/attachments/widgets/views/file_view.dart
  app/lib/features/auth/pages/forgot_password.dart
  app/lib/features/auth/pages/register_page.dart
  app/lib/features/categories/organize_categories_page.dart
  app/lib/features/categories/widgets/category_header_view.dart
  app/lib/features/chat/dialogs/encryption_info_drawer.dart
Labels: flutter, minor

#2297 Tracking boost views
  .changes/2279-public-news-views-tracking.md
  app/lib/features/news/widgets/news_item/news_side_bar.dart
  app/lib/features/read_receipts/providers/read_receipts.dart
  app/lib/features/read_receipts/widgets/read_counter.dart
  app/pubspec.lock
  app/pubspec.yaml
  app/test/features/read_receipts/read_widget_test.dart
  app/test/helpers/mock_read_receipt_providers.dart
  native/acter/api.rsh
  native/acter/src/api.rs
  native/acter/src/api/client.rs
  native/acter/src/api/client/sync.rs
  native/acter/src/api/convo.rs
  native/acter/src/api/news.rs
  native/acter/src/api/read_receipts.rs
  native/acter/src/api/receipt.rs
  native/acter/src/api/spaces.rs
  native/core/src/events.rs
  native/core/src/events/common.rs
  native/core/src/events/read_receipt.rs
  native/core/src/models.rs
  native/core/src/models/news.rs
  native/core/src/models/read_receipts.rs
  native/test/src/tests.rs
  native/test/src/tests/news.rs
  native/test/src/tests/reaction.rs
  native/test/src/tests/receipt.rs
  native/test/src/utils.rs
  packages/rust_sdk/lib/acter_flutter_sdk_ffi.dart
Labels: s-news

#2312 Remove bang operator from nullable variables [15]
  app/lib/features/chat/pages/room_page.dart
  app/lib/features/chat/pages/room_profile_page.dart
  app/lib/features/chat/widgets/bubble_builder.dart
  app/lib/features/chat/widgets/convo_card.dart
  app/lib/features/chat/widgets/emoji/emoji_container.dart
  app/lib/features/chat/widgets/messages/encrypted_message.dart
  app/lib/features/chat/widgets/messages/membership_update.dart
  app/lib/features/chat/widgets/messages/poll_start_message.dart
  app/lib/features/chat/widgets/messages/simple_state_update.dart
  app/lib/features/chat/widgets/messages/topic.dart
Labels: flutter, minor

#2313 Remove bang operator from nullable variables [15]
  app/lib/features/chat/widgets/create_chat.dart
  app/lib/features/chat/widgets/custom_input.dart
  app/lib/features/chat/widgets/file_message_builder.dart
  app/lib/features/chat/widgets/image_message_builder.dart
  app/lib/features/chat/widgets/message_metadata_builder.dart
  app/lib/features/chat/widgets/rooms_list.dart
  app/lib/features/chat/widgets/text_message_builder.dart
Labels: flutter, minor

#2314 Remove bang operator from nullable variables [16]
  app/lib/features/chat/widgets/video_message_builder.dart
  app/lib/features/chat_ng/widgets/rooms_list.dart
  app/lib/features/comments/widgets/comment.dart
  app/lib/features/comments/widgets/create_comment.dart
  app/lib/features/events/pages/event_details_page.dart
  app/lib/features/events/widgets/event_date_widget.dart
  app/lib/features/events/widgets/event_item.dart
  app/lib/features/home/pages/dashboard.dart
  app/lib/features/home/widgets/badged_icon.dart
  app/lib/features/home/widgets/my_spaces_section.dart
Labels: flutter, minor

#2315 Remove bang operator from nullable variables [17]
  app/lib/features/home/widgets/sidebar_widget.dart
  app/lib/features/home/widgets/space_chip.dart
  app/lib/features/intro/pages/intro_page.dart
  app/lib/features/intro/pages/intro_profile.dart
  app/lib/features/invite_members/pages/invite_page.dart
  app/lib/features/invite_members/widgets/space_member_invite_card.dart
  app/lib/features/main/widgets/bottom_navigation_widget.dart
  app/lib/features/member/widgets/member_info_skeleton.dart
  app/lib/features/member/widgets/member_list_entry.dart
  app/lib/features/member/widgets/user_builder.dart
Labels: flutter, minor

#2319 Remove bang operator from nullable variables [19]
  app/lib/features/pins/pages/pin_details_page.dart
  app/lib/features/pins/widgets/fake_link_attachment_item.dart
  app/lib/features/profile/pages/my_profile_page.dart
  app/lib/features/public_room_search/widgets/public_room_item.dart
  app/lib/features/public_room_search/widgets/public_room_search.dart
  app/lib/features/public_room_search/widgets/server_selection_field.dart
  app/lib/features/room/widgets/notifications_settings_tile.dart
  app/lib/features/settings/pages/email_addresses.dart
  app/lib/features/settings/pages/info_page.dart
  app/lib/features/settings/pages/notifications_page.dart
Labels: flutter, minor

#2320 Remove bang operator from nullable variables [20]
  app/lib/features/settings/pages/sessions_page.dart
  app/lib/features/settings/widgets/email_address_card.dart
  app/lib/features/settings/widgets/options_settings_tile.dart
  app/lib/features/settings/widgets/session_card.dart
  app/lib/features/settings/widgets/settings_menu.dart
  app/lib/features/space/dialogs/suggested_rooms.dart
  app/lib/features/space/pages/space_details_page.dart
  app/lib/features/space/settings/pages/visibility_accessibility_page.dart
  app/lib/features/space/sheets/link_room_sheet.dart
  app/lib/features/space/widgets/space_sections/section_header.dart
Labels: flutter, minor

#2321 Remove bang operator from nullable variables [21]
  app/lib/features/space/widgets/loading_convo_card.dart
  app/lib/features/space/widgets/space_header_profile.dart
  app/lib/features/space/widgets/space_toolbar.dart
  app/lib/features/spaces/pages/create_space_page.dart
  app/lib/features/super_invites/pages/super_invites.dart
  app/lib/features/tasks/pages/task_item_detail_page.dart
  app/lib/features/tasks/pages/task_list_details_page.dart
  app/lib/features/tasks/widgets/all_tasks_done.dart
  app/lib/features/tasks/widgets/due_chip.dart
  app/lib/features/tasks/widgets/empty_task_list.dart
  app/lib/features/tasks/widgets/task_item.dart
Labels: flutter, minor

#2322 Remove bang operator from nullable variables [22]
  app/lib/common/actions/close_room.dart
  app/lib/common/actions/redact_content.dart
  app/lib/common/actions/report_content.dart
  app/lib/common/extensions/options.dart
  app/lib/common/providers/common_providers.dart
  app/lib/common/providers/notifiers/chat_notifiers.dart
  app/lib/common/providers/notifiers/sync_notifier.dart
  app/lib/common/providers/room_providers.dart
  app/lib/common/providers/space_providers.dart
  app/lib/common/themes/app_theme.dart
  app/lib/common/toolkit/errors/error_dialog.dart
  app/lib/common/toolkit/menu_item_widget.dart
  app/lib/features/chat/providers/notifiers/chat_room_notifier.dart
  app/test/common/option_extension_test.dart
Labels: flutter, minor

#2326 Fix bug in type casting of nullable variable
  app/lib/features/chat/widgets/emoji/emoji_container.dart
Labels: bug, flutter

#2327 Delay join by waiting for 5s
  app/lib/features/room/actions/join_room.dart
Labels: bug, flutter, minor

#2323 Bookmark pins and show them at the beginning of our lists
  .changes/2323-bookmark-pins.md
  app/lib/features/pins/pages/pin_details_page.dart
  app/lib/features/pins/providers/pins_provider.dart
  app/test/features/pins/error_pages_test.dart
Labels: flutter, s-pins

#2330 Space group creation fixes
  app/lib/features/chat/pages/sub_chats_page.dart
Labels: minor

#2329 Fix feature flags updating
  app/lib/features/labs/feature_flagger.dart
  app/lib/features/labs/providers/labs_providers.dart
  app/lib/features/labs/providers/notifiers/labs_features.dart
Labels: infrastructure, minor

#2331 Switching from rootNavKey.currentContext! to ProviderContainer
  app/integration_test/support/util.dart
  app/lib/config/notifications/init.dart
  app/lib/config/notifications/util.dart
  app/lib/config/setup.dart
  app/lib/features/calendar_sync/calendar_sync.dart
  app/lib/main.dart
  app/lib/router/shell_routers/chat_shell_router.dart
  app/lib/router/utils.dart
  packages/acter_notifify/lib/acter_notifify.dart
  packages/acter_notifify/lib/matrix.dart
  packages/acter_notifify/lib/ntfy.dart
  packages/acter_notifify/lib/platform/android.dart
  packages/acter_notifify/lib/push.dart
  packages/acter_notifify/pubspec.yaml
Labels: flutter, f-push-notifications

#2333 Promoting DeviceCalendar to always-on-labs
  .changes/2333-calendar-device-sync.md
  app/lib/features/labs/model/labs_features.dart
  app/lib/features/settings/pages/labs_page.dart
Labels: s-calendar, minor

#2336 Two more cases of Sentry logging
  app/lib/common/providers/notifiers/sync_notifier.dart
  app/lib/features/auth/actions/register_action.dart
  app/lib/features/auth/pages/register_page.dart
  app/lib/features/auth/providers/notifiers/auth_notifier.dart
Labels: minor
