Repository acterglobal/a3, pull requests merged in 2024-01, with the labels that each got.

#1275 Workaround to fix Android forgotten session.
  app/packages/rust_sdk/lib/acter_flutter_sdk.dart
Labels: bug, t-android

#1281 Ensure we are building on latest flutter stable
  .github/workflows/demo.yml
  .github/workflows/deploy.yml
  .github/workflows/docs.yml
  .github/workflows/integration_testing.yml
  .github/workflows/native.yml
  .github/workflows/nightly.yml
Labels: build

#1277 Fix up proxyman setup
  Cargo.lock
  app/packages/rust_sdk/lib/acter_flutter_sdk.dart
  native/acter/Cargo.toml
  native/acter/src/api/auth.rs
Labels: bug

#1287 use openssl with 'vendored'-flag for android from now
  Cargo.lock
  native/acter/Cargo.toml
Labels: minor

#1297 Put request and openssl behind a proxyman feature-flag
  Cargo.lock
  native/acter/Cargo.toml
Labels: bug, build, minor

#1295 Minimal UI smoketest for Pins
  Makefile.toml
  app/integration_test/main_test.dart
  app/integration_test/tests/pins.dart
  app/lib/features/pins/sheets/create_pin_sheet.dart
  app/lib/features/search/model/keys.dart
  app/lib/features/search/widgets/quick_actions_builder.dart
  app/lib/features/search/widgets/quick_jump.dart
Labels: minor

#1298 Fix iOS release
  .github/workflows/publish.yml
  app/ios/Flutter/AppFrameworkInfo.plist
  app/ios/Runner/Info.plist
Labels: bug, build, minor

#1306 Fix session reset
  .changes/0834-chat-invites-fixes.md
  .changes/0927-blocking-user.md
  .changes/1231-empty-states.md
  .changes/1304-fix-session.md
  native/acter/src/api/auth.rs
  native/test/src/tests/auth.rs
Labels: minor

#1300 add Updates missing APIs
  app/lib/features/news/widgets/news_item.dart
  app/packages/rust_sdk/lib/acter_flutter_sdk_ffi.dart
  native/acter/api.rsh
  native/acter/src/api.rs
  native/acter/src/api/news.rs
  native/test/src/tests/news.rs
Labels: rust, s-news

#1336 tracing feature for rust (desktop)
  Cargo.lock
  Makefile.toml
  app/packages/rust_sdk/lib/acter_flutter_sdk.dart
  native/acter/Cargo.toml
  native/acter/src/platform/native.rs
Labels: rust, minor

#1337 Setting the HTTP proxy via UI and CLI
  app/lib/features/cli/commands/settings.dart
  app/lib/features/cli/main.dart
  app/lib/features/settings/pages/info_page.dart
  app/packages/rust_sdk/lib/acter_flutter_sdk.dart
Labels: flutter, ci-test-ui-all, minor

#1339 handle history sync for spaces reset at the end to clear the spawn
  native/acter/src/api/client.rs
Labels: rust, minor
