Repository acterglobal/a3, pull requests merged in 2024-03, with the labels that each got.

#1471 Pull to Filter for Chat Rooms
  .changes/1471-pull-to-filter-chats.md
  app/lib/common/providers/chat_providers.dart
  app/lib/common/providers/notifiers/client_pref_notifier.dart
  app/lib/common/providers/room_providers.dart
  app/lib/common/widgets/chat/convo_card.dart
  app/lib/features/chat/models/chat_list_state/chat_list_state.freezed.dart
  app/lib/features/chat/models/room_list_filter_state/room_list_filter_state.dart
  app/lib/features/chat/models/room_list_filter_state/room_list_filter_state.freezed.dart
  app/lib/features/chat/pages/room_profile_page.dart
  app/lib/features/chat/providers/chat_providers.dart
  app/lib/features/chat/providers/room_list_filter_provider.dart
  app/lib/features/chat/widgets/convo_list.dart
  app/lib/features/chat/widgets/rooms_list.dart
  app/lib/features/space/sheets/link_room_sheet.dart
  app/packages/rust_sdk/lib/acter_flutter_sdk_ffi.dart
  native/acter/api.rsh
  native/acter/src/api/convo.rs
Labels: s-chat

#1479 Refactor core::Store
  Cargo.lock
  native/acter/src/platform/native.rs
  native/core/Cargo.toml
  native/core/src/error.rs
  native/core/src/executor.rs
  native/core/src/models/test.rs
  native/core/src/store.rs
Labels: rust

#1457 pin attachments
  .changes/1457-pin-attachments.md
  app/integration_test/tests/pins.dart
  app/integration_test/tests/sub_spaces.dart
  app/ios/Podfile.lock
  app/ios/Runner.xcodeproj/project.pbxproj
  app/lib/common/dialogs/attachment_confirmation.dart
  app/lib/common/providers/attachment_providers.dart
  app/lib/common/providers/notifiers/attachments_notifiers.dart
  app/lib/common/utils/utils.dart
  app/lib/common/widgets/attachment_options.dart
  app/lib/common/widgets/sliver_scaffold.dart
  app/lib/features/chat/widgets/custom_input.dart
  app/lib/features/pins/pages/create_pin_page.dart
  app/lib/features/pins/pin_utils/pin_utils.dart
  app/lib/features/pins/providers/notifiers/edit_state_notifier.dart
  app/lib/features/pins/providers/pins_provider.dart
  app/lib/features/pins/sheets/create_pin_sheet.dart
  app/lib/features/pins/widgets/attachment_handler.dart
  app/lib/features/pins/widgets/image_attachment_preview.dart
  app/lib/features/pins/widgets/pin_item.dart
  app/lib/features/pins/widgets/pin_list_item.dart
  app/lib/features/settings/super_invites/pages/create.dart
  app/lib/features/space/sheets/edit_space_sheet.dart
  app/lib/features/space/sheets/link_room_sheet.dart
  app/lib/features/spaces/sheets/create_space_sheet.dart
  app/lib/features/tasks/dialogs/create_task_list_sheet.dart
  app/lib/router/general_router.dart
  app/macos/Podfile.lock
  app/macos/Runner.xcodeproj/project.pbxproj
  app/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  app/packages/rust_sdk/lib/acter_flutter_sdk_ffi.dart
  app/pubspec.lock
  native/acter/api.rsh
  native/acter/src/api/attachments.rs
  native/core/src/models/attachments.rs
Labels: flutter, rust, s-pins

#1489 Hotfix: white/black screen issue on Apple platforms.
  app/lib/common/utils/logging.dart
  app/packages/rust_sdk/lib/acter_flutter_sdk_ffi.dart
  native/acter/api.rsh
  native/acter/src/api.rs
  native/acter/src/platform/mod.rs
  native/acter/src/platform/native.rs
Labels: bug, flutter, rust, t-ios, t-macos, minor

#1497 Switch to set_custom_no_read for performance improvements
  Cargo.lock
  Cargo.toml
  app/lib/features/chat/widgets/room_avatar.dart
  native/acter/src/api/message.rs
  native/acter/src/api/room.rs
  native/acter/src/api/spaces.rs
  native/core/src/store.rs
  native/media-cache-wrapper/src/lib.rs
Labels: rust, minor

#1505 wait longer before failing to load a chat room
  app/lib/common/providers/chat_providers.dart
Labels: bug, flutter, minor

#1501 Refactor Chat Room Messages
  Cargo.lock
  app/lib/features/activities/providers/notifications_providers.dart
  app/lib/features/activities/providers/notifiers/notifications_list_notifier.dart
  app/lib/features/activities/util.dart
  app/lib/features/activities/widgets/notification_card.dart
  app/lib/features/chat/providers/notifiers/chat_room_notifier.dart
  app/lib/features/home/pages/home_shell.dart
  app/packages/rust_sdk/lib/acter_flutter_sdk_ffi.dart
  native/acter/Cargo.toml
  native/acter/api.rsh
  native/acter/src/api.rs
  native/acter/src/api/client.rs
  native/acter/src/api/convo.rs
  native/acter/src/api/message.rs
  native/acter/src/api/notifications.rs
  native/acter/src/api/push.rs
  native/acter/src/api/room.rs
  native/acter/src/api/stream.rs
Labels: rust

#1508 Members Info box with quick actions
  .changes/1508-member-profiles.md
  app/lib/common/dialogs/block_user_dialog.dart
  app/lib/common/dialogs/member_info_drawer.dart
  app/lib/common/providers/chat_providers.dart
  app/lib/common/toolkit/menu_item_widget.dart
  app/lib/common/widgets/member_list_entry.dart
  app/lib/features/chat/providers/create_chat_providers.dart
  app/lib/features/chat/widgets/avatar_builder.dart
  app/lib/features/chat/widgets/create_chat.dart
  app/lib/features/settings/widgets/settings_menu.dart
Labels: infrastructure

#1495 Miscellaneous refactoring
  app/lib/common/providers/notifiers/reactions_notifiers.dart
  app/lib/common/widgets/like_button.dart
  app/lib/features/news/widgets/news_side_bar.dart
  app/lib/features/onboarding/pages/register_page.dart
  app/packages/rust_sdk/lib/acter_flutter_sdk.dart
  native/acter/src/api/auth.rs
  native/acter/src/api/convo.rs
  native/acter/src/api/room.rs
  native/acter/src/api/search.rs
  native/acter/src/api/spaces.rs
  native/acter/src/api/tasks.rs
  native/acter/src/api/three_pid.rs
  native/acter/src/platform/native.rs
  native/cli/src/action/mock.rs
  native/test/src/tests/tasks.rs
Labels: flutter, rust, minor

#1521 Do not set the language as a local config unless the user explicitly did so
  app/lib/common/utils/language.dart
Labels: bug, minor

#1522 harden the cache clearance code
  app/packages/rust_sdk/lib/acter_flutter_sdk.dart
Labels: t-ios, infrastructure, t-macos, minor

#1523 minor attachment fixes
  app/lib/common/widgets/attachments/post_attachment_selection.dart
Labels: bug, flutter, minor

#1513 Simplified Manager model processing
  .changes/1513-comments.md
  app/lib/common/utils/utils.dart
  app/lib/features/comments/models.dart
  app/lib/features/comments/providers/comments.dart
  app/lib/features/comments/widgets/comment.dart
  app/lib/features/comments/widgets/comments_list.dart
  app/lib/features/comments/widgets/comments_section.dart
  app/lib/features/comments/widgets/create_comment.dart
  app/lib/features/pins/widgets/pin_item.dart
  app/lib/features/settings/pages/labs_page.dart
  app/packages/rust_sdk/lib/acter_flutter_sdk_ffi.dart
  native/acter/api.rsh
  native/acter/src/api/comments.rs
  native/core/src/models/attachments.rs
  native/core/src/models/comments.rs
  native/core/src/models/reactions.rs
  native/core/src/models/rsvp.rs
  native/core/src/store.rs
  native/core/src/util.rs
Labels: rust

#1515 Refactor roomMember Providers, user info drawer
  app/lib/common/dialogs/attachment_confirmation.dart
  app/lib/common/dialogs/attachment_selection.dart
  app/lib/common/dialogs/member_info_drawer.dart
  app/lib/common/models/types.dart
  app/lib/common/providers/chat_providers.dart
  app/lib/common/providers/room_providers.dart
  app/lib/common/providers/space_providers.dart
  app/lib/common/utils/utils.dart
  app/lib/common/widgets/attachments/attachment_draft_item.dart
  app/lib/common/widgets/attachments/post_attachment_selection.dart
  app/lib/common/widgets/member_list_entry.dart
  app/lib/common/widgets/user_chip.dart
  app/lib/features/chat/models/chat_input_state/chat_input_state.dart
  app/lib/features/chat/pages/room_page.dart
  app/lib/features/chat/pages/room_profile_page.dart
  app/lib/features/chat/providers/chat_providers.dart
  app/lib/features/chat/providers/notifiers/chat_input_notifier.dart
  app/lib/features/chat/providers/notifiers/chat_room_notifier.dart
  app/lib/features/chat/providers/notifiers/media_chat_notifier.dart
  app/lib/features/chat/widgets/avatar_builder.dart
  app/lib/features/chat/widgets/bubble_builder.dart
  app/lib/features/chat/widgets/custom_input.dart
  app/lib/features/chat/widgets/emoji_reaction_item.dart
  app/lib/features/chat/widgets/file_message_builder.dart
  app/lib/features/chat/widgets/image_message_builder.dart
  app/lib/features/chat/widgets/member_list.dart
  app/lib/features/chat/widgets/mention_profile_builder.dart
  app/lib/features/chat/widgets/message_metadata_builder.dart
  app/lib/features/chat/widgets/room_avatar.dart
  app/lib/features/chat/widgets/video_message_builder.dart
  app/lib/features/events/pages/event_details_page.dart
  app/lib/features/space/pages/members_page.dart
  app/lib/features/space/widgets/member_avatar.dart
  app/lib/features/space/widgets/space_header_profile.dart
  app/lib/features/tasks/models/tasks.dart
  app/packages/rust_sdk/lib/acter_flutter_sdk_ffi.dart
  native/acter/api.rsh
  native/acter/src/api/room.rs
Labels: infrastructure, s-chat

#1543 more verbose error reporting for fatal error
  app/lib/common/pages/fatal_fail.dart
  app/lib/router/router.dart
  app/pubspec.lock
  app/pubspec.yaml
Labels: t-ios, t-macos, minor

#1539 Implement L10n in cross signing
  app/lib/features/cross_signing/views/request_cancelled.dart
  app/lib/features/cross_signing/views/request_created.dart
  app/lib/features/cross_signing/views/request_done.dart
  app/lib/features/cross_signing/views/request_ready.dart
  app/lib/features/cross_signing/views/sas_accepted.dart
  app/lib/features/cross_signing/views/sas_cancelled.dart
  app/lib/features/cross_signing/views/sas_keys_exchanged.dart
  app/lib/features/cross_signing/views/sas_started.dart
  app/lib/features/cross_signing/views/verification_request.dart
  app/lib/features/settings/widgets/session_card.dart
  app/lib/l10n/app_en.arb
Labels: flutter, minor

#1549 Miscellaneous refactoring
  native/acter/src/api/attachments.rs
  native/acter/src/api/client.rs
  native/acter/src/api/common.rs
  native/acter/src/api/message.rs
  native/acter/src/api/news.rs
  native/acter/src/api/pins.rs
  native/acter/src/api/push.rs
  native/acter/src/api/reactions.rs
  native/acter/src/api/room.rs
  native/acter/src/api/spaces.rs
  native/acter/src/api/typing.rs
  native/acter/src/api/verification.rs
  native/core/src/error.rs
  native/core/src/events/subscription.rs
  native/core/src/models/comments.rs
  native/core/src/models/reactions.rs
Labels: rust, minor

#1533 Implement Kick & ban of users from any room
  .changes/1533-kick-and-ban.md
  app/lib/common/dialogs/member_info_drawer.dart
  app/lib/common/widgets/member_list_entry.dart
  app/lib/features/chat/widgets/avatar_builder.dart
  app/lib/features/chat/widgets/member_list.dart
  app/lib/features/member/dialogs/show_block_user_dialog.dart
  app/lib/features/member/dialogs/show_change_power_level_dialog.dart
  app/lib/features/member/dialogs/show_kick_and_ban_user_dialog.dart
  app/lib/features/member/dialogs/show_kick_user_dialog.dart
  app/lib/features/member/dialogs/show_member_info_drawer.dart
  app/lib/features/member/dialogs/show_unblock_user_dialog.dart
  app/lib/features/member/widgets/member_info_drawer.dart
  app/lib/features/member/widgets/member_info_skeleton.dart
  app/lib/features/member/widgets/member_list_entry.dart
  app/lib/features/member/widgets/message_user_button.dart
  app/lib/features/space/pages/members_page.dart
  app/lib/l10n/app_en.arb
  app/packages/rust_sdk/lib/acter_flutter_sdk_ffi.dart
  native/acter/api.rsh
  native/acter/src/api/room.rs
Labels: infrastructure, s-chat

#1557 Weblate latest
  app/lib/l10n/app_de.arb
  app/lib/l10n/app_en.arb
Labels: minor
