Repository acterglobal/a3, pull requests merged in 2024-04, with the labels that each got.

#1566 1561 for uniffi extension, too
  app/ios/ActerPushServiceExtension/NotificationService.swift
  app/ios/ActerPushServiceExtension/acter.swift
  app/ios/acterFFI/acterFFI.h
  native/acter/src/api/uniffi_api.rs
Labels: build, t-ios, t-macos, minor

#1560 Miscellaneous refactoring
  app/lib/common/providers/notifiers/attachments_notifiers.dart
  app/lib/common/providers/notifiers/chat_notifiers.dart
  app/lib/common/providers/notifiers/notification_settings_notifier.dart
  app/lib/common/providers/notifiers/reactions_notifiers.dart
  app/lib/common/providers/notifiers/room_notifiers.dart
  app/lib/common/providers/notifiers/space_notifiers.dart
  app/lib/common/widgets/html_editor.dart
  app/lib/features/activities/providers/notifiers/invitation_list_notifier.dart
  app/lib/features/bug_report/pages/bug_report_page.dart
  app/lib/features/chat/providers/notifiers/chat_room_notifier.dart
  app/lib/features/comments/providers/comments.dart
  app/lib/features/events/pages/create_edit_event_page.dart
  app/lib/features/home/providers/notifiers/client_notifier.dart
  app/lib/features/home/providers/task_providers.dart
  app/lib/features/member/dialogs/show_change_power_level_dialog.dart
  app/lib/features/news/providers/notifiers/news_list_notifier.dart
  app/lib/features/onboarding/pages/login_page.dart
  app/lib/features/onboarding/pages/register_page.dart
  app/lib/features/pins/pages/create_pin_page.dart
  app/lib/features/pins/widgets/pin_item.dart
  app/lib/features/profile/pages/my_profile_page.dart
  app/lib/features/settings/pages/blocked_users.dart
  app/lib/features/settings/widgets/email_address_card.dart
  app/lib/features/space/settings/pages/apps_settings_page.dart
  app/lib/features/tasks/dialogs/create_task_list_sheet.dart
  app/lib/features/tasks/providers/notifiers.dart
  app/lib/features/tasks/widgets/task_info.dart
  app/lib/features/tasks/widgets/task_list_card.dart
Labels: flutter, minor

#1559 Fix bug that custom event editing failed
  app/lib/features/events/pages/create_edit_event_page.dart
  app/lib/features/events/providers/event_providers.dart
  native/core/src/models/calendar/event.rs
  native/core/src/models/news.rs
  native/core/src/models/pins.rs
  native/core/src/models/tasks/task.rs
  native/core/src/models/tasks/task_list.rs
  native/test/src/tests/calendar.rs
  native/test/src/tests/tasks.rs
Labels: flutter, rust

#1574 Fix 1565
  app/packages/rust_sdk/lib/acter_flutter_sdk.dart
Labels: minor

#1575 Follow up of #1537: Android SDK needs to be 34+ now
  app/android/app/build.gradle
Labels: bug, t-android, minor

#1579 Cleaning up the l10n template file
  app/lib/l10n/app_en.arb
Labels: flutter, minor

#1558 Attachments view
  .changes/1558-attachments-view.md
  app/lib/common/dialogs/attachment_selection.dart
  app/lib/common/models/attachment_media_state/attachment_media_state.dart
  app/lib/common/models/attachment_media_state/attachment_media_state.freezed.dart
  app/lib/common/providers/attachment_providers.dart
  app/lib/common/providers/notifiers/attachments_notifiers.dart
  app/lib/common/widgets/acter_video_player.dart
  app/lib/common/widgets/attachments/attachment_container.dart
  app/lib/common/widgets/attachments/attachment_draft_item.dart
  app/lib/common/widgets/attachments/attachment_item.dart
  app/lib/common/widgets/attachments/views/file_view.dart
  app/lib/common/widgets/attachments/views/image_view.dart
  app/lib/common/widgets/attachments/views/video_view.dart
  app/lib/features/chat/widgets/custom_input.dart
  app/lib/features/pins/widgets/pin_list_item.dart
  app/packages/rust_sdk/lib/acter_flutter_sdk_ffi.dart
  native/acter/api.rsh
  native/acter/src/api/attachments.rs
Labels: flutter, rust

#1576 Improved invitation handling, remove not-joined Spaces from UI
  app/lib/common/models/invitation_profile.dart
  app/lib/features/activities/providers/invitations_providers.dart
  app/lib/features/activities/widgets/invitation_card.dart
  app/lib/features/activities/widgets/invitations_list.dart
  app/lib/l10n/app_en.arb
  app/packages/rust_sdk/lib/acter_flutter_sdk_ffi.dart
  native/acter/api.rsh
  native/acter/src/api/client.rs
  native/acter/src/api/invitation.rs
  native/acter/src/api/profile.rs
  native/acter/src/api/room.rs
  native/test/src/tests/tasks.rs
Labels: infrastructure

#1583 invalidate spaceRelationsOverviewProvider upon our changes to ensure …
  app/lib/features/chat/widgets/create_chat.dart
  app/lib/features/space/sheets/link_room_sheet.dart
  app/lib/features/spaces/sheets/create_space_sheet.dart
Labels: bug, flutter, minor

#1584 Activities : Invitation UI Bug Fixes
  app/lib/features/activities/widgets/invitation_card.dart
Labels: minor

#1581 Refactor chat routing to avoid riverpod states
  app/lib/features/chat/config.dart
  app/lib/features/chat/pages/room_page.dart
  app/lib/features/chat/pages/room_profile_page.dart
  app/lib/features/chat/providers/chat_providers.dart
  app/lib/features/chat/widgets/chat_layout_builder.dart
  app/lib/features/chat/widgets/rooms_list.dart
  app/lib/router/shell_routers/chat_shell_router.dart
Labels: bug, flutter, s-chat

#1589 Fix ci caching issue
  .github/workflows/demo.yml
  .github/workflows/nightly.yml
  .github/workflows/publish.yml
Labels: infrastructure, minor

#1596 reapply logging infrastructure
  app/lib/common/utils/logging.dart
  app/lib/features/home/providers/notifiers/client_notifier.dart
  app/packages/rust_sdk/lib/acter_flutter_sdk_ffi.dart
  native/acter/api.rsh
  native/acter/src/api.rs
  native/acter/src/platform/mod.rs
  native/acter/src/platform/native.rs
Labels: minor

#1591 Chat Input Refactors
  app/lib/common/widgets/emoji_picker_widget.dart
  app/lib/common/widgets/no_internet.dart
  app/lib/features/chat/models/chat_input_state/chat_input_state.dart
  app/lib/features/chat/models/chat_input_state/chat_input_state.freezed.dart
  app/lib/features/chat/pages/room_page.dart
  app/lib/features/chat/providers/chat_providers.dart
  app/lib/features/chat/providers/notifiers/chat_input_notifier.dart
  app/lib/features/chat/providers/notifiers/chat_room_notifier.dart
  app/lib/features/chat/widgets/bubble_builder.dart
  app/lib/features/chat/widgets/custom_input.dart
  app/lib/features/chat/widgets/emoji_row.dart
  app/lib/features/chat/widgets/message_actions.dart
  app/lib/features/chat/widgets/message_metadata_builder.dart
  app/lib/features/onboarding/pages/login_page.dart
  app/lib/features/onboarding/pages/register_page.dart
  app/lib/l10n/app_en.arb
  app/lib/main.dart
  app/pubspec.lock
  app/pubspec.yaml
Labels: bug, flutter, s-chat

#1597 Exclude invited rooms from convos
  native/acter/src/api/client.rs
Labels: bug, rust, s-chat, minor

#1605 Fix accept of invitation in integration test according to PR#1597
  native/test/src/tests/formatted_body.rs
  native/test/src/tests/reaction.rs
  native/test/src/tests/receipt.rs
  native/test/src/tests/reply.rs
  native/test/src/tests/typing.rs
Labels: rust

#1606 Make buttons accessible in fatal fail
  app/lib/common/pages/fatal_fail.dart
Labels: bug, flutter, minor

#1601 Attachments and Comments for Events & Task, Clean up Labs features
  app/lib/common/dialogs/attachment_confirmation.dart
  app/lib/common/dialogs/attachment_selection.dart
  app/lib/common/utils/utils.dart
  app/lib/features/attachments/providers/attachment_providers.dart
  app/lib/features/attachments/providers/notifiers/attachments_notifiers.dart
  app/lib/features/attachments/widgets/attachment_container.dart
  app/lib/features/attachments/widgets/attachment_draft_item.dart
  app/lib/features/attachments/widgets/attachment_item.dart
  app/lib/features/attachments/widgets/attachment_options.dart
  app/lib/features/attachments/widgets/attachment_section.dart
  app/lib/features/attachments/widgets/post_attachment_selection.dart
  app/lib/features/attachments/widgets/views/file_view.dart
  app/lib/features/attachments/widgets/views/image_view.dart
  app/lib/features/attachments/widgets/views/video_view.dart
  app/lib/features/chat/widgets/custom_input.dart
  app/lib/features/events/pages/event_details_page.dart
  app/lib/features/home/pages/dashboard.dart
  app/lib/features/pins/pages/pin_page.dart
  app/lib/features/pins/providers/pins_provider.dart
  app/lib/features/pins/widgets/pin_list_item.dart
  app/lib/features/search/widgets/quick_actions_builder.dart
  app/lib/features/search/widgets/quick_jump.dart
  app/lib/features/settings/pages/labs_page.dart
  app/lib/features/space/providers/space_navbar_provider.dart
  app/lib/features/tasks/pages/task_list_page.dart
  app/lib/features/tasks/widgets/task_info.dart
  app/lib/features/tasks/widgets/task_list_card.dart
  app/packages/rust_sdk/lib/acter_flutter_sdk_ffi.dart
  native/acter/api.rsh
  native/acter/src/api/attachments.rs
  native/acter/src/api/calendar_events.rs
  native/acter/src/api/tasks.rs
  native/core/src/models/calendar/event.rs
  native/core/src/models/tasks/task_list.rs
Labels: s-tasks, s-pins, s-calendar, minor

#1612 fix dart attachments integration tests
  app/integration_test/tests/attachments.dart
  app/lib/features/attachments/widgets/attachment_section.dart
  app/lib/features/pins/pages/pin_page.dart
  docs/content/docs/dev/testing.md
Labels: bug, minor

#1611 Ensure we publish the release correctly
  .github/workflows/publish.yml
  app/flatpak/build-flatpak.sh
Labels: infrastructure, minor

#1616 autogenerate flatpak release versions
  .github/workflows/publish.yml
  app/flatpak/add_release_info.sh
  app/flatpak/build-flatpak.sh
  app/flatpak/global.acter.a3.desktop
  app/flatpak/global.acter.a3.metainfo_header.xml
  app/flatpak/global.acter.a3.metainfo_versions.xml
Labels: infrastructure, minor

#1609 Fix accept of invitation in integration test according to PR#1597
  native/acter/src/api/attachments.rs
  native/acter/src/api/push.rs
  native/acter/src/api/reactions.rs
  native/acter/src/api/stream.rs
  native/cli/src/action/mock.rs
  native/test/src/tests/calendar.rs
  native/test/src/tests/formatted_body.rs
  native/test/src/tests/msg_edit.rs
  native/test/src/tests/news.rs
  native/test/src/tests/onboarding.rs
  native/test/src/tests/pins.rs
  native/test/src/tests/reaction.rs
  native/test/src/tests/receipt.rs
  native/test/src/tests/redact.rs
  native/test/src/tests/reply.rs
  native/test/src/tests/rsvp.rs
  native/test/src/tests/spaces.rs
  native/test/src/tests/super_invites.rs
  native/test/src/tests/tasks.rs
  native/test/src/tests/templates.rs
  native/test/src/tests/typing.rs
Labels: minor

#1617 Share event as ical
  .changes/1617-ical-share.md
  Cargo.lock
  Cargo.toml
  app/lib/common/widgets/event/event_selector_drawer.dart
  app/lib/features/events/model/keys.dart
  app/lib/features/events/pages/event_details_page.dart
  app/lib/features/events/pages/events_page.dart
  app/lib/features/events/widgets/calendar_widget.dart
  app/lib/features/events/widgets/event_item.dart
  app/lib/features/events/widgets/events_list.dart
  app/lib/features/news/pages/add_news_page.dart
  app/lib/features/news/widgets/news_item.dart
  app/lib/features/space/pages/events_page.dart
  app/lib/features/space/widgets/events_card.dart
  app/lib/l10n/app_en.arb
  app/packages/rust_sdk/lib/acter_flutter_sdk_ffi.dart
  native/acter/Cargo.toml
  native/acter/api.rsh
  native/acter/src/api/calendar_events.rs
  native/core/Cargo.toml
  native/core/src/models/calendar/event.rs
Labels: s-calendar

#1580 Replace customSnackBar with EasyLoading
  app/lib/common/dialogs/attachment_confirmation.dart
  app/lib/common/dialogs/deactivation_confirmation.dart
  app/lib/common/pages/fatal_fail.dart
  app/lib/common/snackbars/custom_msg.dart
  app/lib/common/utils/rooms.dart
  app/lib/common/widgets/chat/convo_card.dart
  app/lib/common/widgets/redact_content.dart
  app/lib/common/widgets/report_content.dart
  app/lib/features/activities/widgets/invitation_card.dart
  app/lib/features/attachments/widgets/attachment_section.dart
  app/lib/features/attachments/widgets/post_attachment_selection.dart
  app/lib/features/bug_report/pages/bug_report_page.dart
  app/lib/features/chat/pages/room_profile_page.dart
  app/lib/features/chat/widgets/bubble_builder.dart
  app/lib/features/chat/widgets/create_chat.dart
  app/lib/features/chat/widgets/custom_input.dart
  app/lib/features/chat/widgets/message_actions.dart
  app/lib/features/chat/widgets/message_metadata_builder.dart
  app/lib/features/comments/widgets/create_comment.dart
  app/lib/features/events/pages/create_edit_event_page.dart
  app/lib/features/events/pages/event_details_page.dart
  app/lib/features/home/widgets/my_tasks.dart
  app/lib/features/member/dialogs/show_block_user_dialog.dart
  app/lib/features/member/dialogs/show_kick_and_ban_user_dialog.dart
  app/lib/features/member/dialogs/show_kick_user_dialog.dart
  app/lib/features/member/dialogs/show_unblock_user_dialog.dart
  app/lib/features/member/widgets/member_info_drawer.dart
  app/lib/features/news/pages/add_news_page.dart
  app/lib/features/onboarding/pages/login_page.dart
  app/lib/features/onboarding/pages/register_page.dart
  app/lib/features/onboarding/providers/notifiers/auth_notifier.dart
  app/lib/features/pins/pages/create_pin_page.dart
  app/lib/features/pins/providers/notifiers/edit_state_notifier.dart
  app/lib/features/profile/pages/my_profile_page.dart
  app/lib/features/room/widgets/notifications_settings_tile.dart
  app/lib/features/settings/pages/blocked_users.dart
  app/lib/features/settings/pages/email_addresses.dart
  app/lib/features/settings/pages/notifications_page.dart
  app/lib/features/settings/super_invites/pages/create.dart
  app/lib/features/settings/super_invites/widgets/redeem_token.dart
  app/lib/features/settings/widgets/email_address_card.dart
  app/lib/features/settings/widgets/labs_notifications_settings_tile.dart
  app/lib/features/space/settings/pages/apps_settings_page.dart
  app/lib/features/space/sheets/edit_space_sheet.dart
  app/lib/features/space/widgets/non_acter_space_card.dart
  app/lib/features/spaces/pages/join_space.dart
  app/lib/features/spaces/sheets/create_space_sheet.dart
  app/lib/features/tasks/dialogs/create_task_list_sheet.dart
  app/lib/features/tasks/widgets/due_chip.dart
  app/lib/features/tasks/widgets/task_info.dart
  app/lib/features/tasks/widgets/task_list_card.dart
  app/lib/l10n/app_en.arb
  app/lib/main.dart
  app/pubspec.lock
Labels: flutter, minor

#1630 Improve description for clear log in github workflow
  native/test/src/tests/news.rs
  native/test/src/tests/reaction.rs
Labels: rust, minor

#1629 Fix ios 15 security platform exception
  Makefile.toml
  app/packages/rust_sdk/lib/acter_flutter_sdk.dart
Labels: t-ios, minor

#1634 Fix the extension the ical event is stored under as ics to make it open in regular apps
  app/lib/features/events/pages/event_details_page.dart
Labels: bug, s-calendar, minor

#1534 Backup Recovery Key Support
  .github/workflows/deploy.yml
  .github/workflows/docs.yml
  .github/workflows/integration_testing.yml
  .github/workflows/native.yml
  .github/workflows/styles.yml
  Cargo.lock
  Cargo.toml
  app/lib/common/utils/routes.dart
  app/lib/common/utils/utils.dart
  app/lib/features/activities/pages/activities_page.dart
  app/lib/features/backups/dialogs/provide_recovery_key_dialog.dart
  app/lib/features/backups/dialogs/show_confirm_disabling.dart
  app/lib/features/backups/dialogs/show_recovery_key.dart
  app/lib/features/backups/providers/backup_manager_provider.dart
  app/lib/features/backups/providers/backup_state_providers.dart
  app/lib/features/backups/providers/notifiers/backup_state_notifier.dart
  app/lib/features/backups/types.dart
  app/lib/features/backups/widgets/backup_state_widget.dart
  app/lib/features/settings/pages/backup_page.dart
  app/lib/features/settings/pages/labs_page.dart
  app/lib/features/settings/widgets/settings_menu.dart
  app/lib/l10n/app_en.arb
  app/lib/router/shell_routers/home_shell_router.dart
  app/packages/rust_sdk/lib/acter_flutter_sdk_ffi.dart
  native/acter/Cargo.toml
  native/acter/api.rsh
  native/acter/src/api.rs
  native/acter/src/api/attachments.rs
  native/acter/src/api/backup.rs
  native/acter/src/api/client.rs
  native/acter/src/api/message.rs
  native/acter/src/api/news.rs
  native/acter/src/api/stream.rs
  native/cli/Cargo.toml
  native/core/Cargo.toml
  native/core/src/events/calendar.rs
  native/core/src/events/common/labels.rs
  native/core/src/events/news.rs
  native/core/src/events/pins.rs
  native/core/src/events/tasks.rs
  native/core/src/executor.rs
  native/core/src/models.rs
  native/core/src/store.rs
  native/test/src/tests/reaction.rs
  native/test/src/utils.rs
  native/tui/Cargo.toml
  rust-toolchain
Labels: e2ee, privacy & security

#1639 Update ahash dependency to fix nightly build error
  Cargo.lock
Labels: dependencies, minor

#1640 Syncing translations ahead of weekly release.
  app/lib/l10n/app_de.arb
  app/lib/l10n/app_en.arb
  app/lib/l10n/app_pl.arb
  app/lib/l10n/app_pt.arb
Labels: minor, translations

#1648 Several chat state related fixes
  .changes/1648-chat-fixes.md
  app/lib/common/providers/room_providers.dart
  app/lib/features/chat/models/chat_input_state/chat_input_state.dart
  app/lib/features/chat/models/chat_input_state/chat_input_state.freezed.dart
  app/lib/features/chat/providers/chat_providers.dart
  app/lib/features/chat/providers/notifiers/chat_input_notifier.dart
  app/lib/features/chat/widgets/bubble_builder.dart
  app/lib/features/chat/widgets/custom_input.dart
  app/lib/features/chat/widgets/message_actions.dart
  app/lib/l10n/app_en.arb
Labels: flutter

#1653 Minor chat fixes
  app/lib/common/notifications/util.dart
  app/lib/features/chat/providers/notifiers/chat_input_notifier.dart
  app/lib/features/chat/utils.dart
  app/lib/features/chat/widgets/text_message_builder.dart
  app/lib/features/member/dialogs/show_member_info_drawer.dart
  app/lib/features/member/widgets/message_user_button.dart
  app/test/features/chat/chat_message_test.dart
Labels: bug, flutter

#1651 Upgrading to Flutter 3.19
  .github/workflows/demo.yml
  .github/workflows/deploy.yml
  .github/workflows/docs.yml
  .github/workflows/integration_testing.yml
  .github/workflows/native.yml
  .github/workflows/nightly.yml
  .github/workflows/publish.yml
  .github/workflows/styles.yml
  app/lib/common/themes/chat_theme.dart
  app/lib/common/widgets/chat/convo_card.dart
  app/lib/features/chat/pages/room_profile_page.dart
  app/lib/features/chat/widgets/create_chat.dart
  app/lib/features/comments/widgets/create_comment.dart
  app/lib/features/events/pages/create_edit_event_page.dart
  app/lib/features/pins/pages/create_pin_page.dart
  app/lib/features/settings/super_invites/pages/create.dart
  app/lib/features/settings/super_invites/widgets/redeem_token.dart
  app/lib/features/space/sheets/edit_space_sheet.dart
  app/lib/features/space/sheets/link_room_sheet.dart
  app/lib/features/tasks/widgets/task_info.dart
  app/pubspec.lock
  app/pubspec.yaml
Labels: flutter, minor

#1659 Reworking the Space and Chat routing, including Spacebar navigation, for resilience and better UX
  app/lib/common/notifications/util.dart
  app/lib/common/widgets/spaces/space_hierarchy_card.dart
  app/lib/features/chat/utils.dart
  app/lib/features/home/widgets/sidebar_widget.dart
  app/lib/features/member/widgets/message_user_button.dart
  app/lib/features/news/widgets/news_item.dart
  app/lib/features/news/widgets/news_side_bar.dart
  app/lib/features/search/model/util.dart
  app/lib/features/search/pages/quick_jump.dart
  app/lib/features/search/pages/search.dart
  app/lib/features/search/widgets/pins_builder.dart
  app/lib/features/search/widgets/quick_actions_builder.dart
  app/lib/features/search/widgets/quick_jump.dart
  app/lib/features/search/widgets/spaces_builder.dart
  app/lib/features/space/dialogs/leave_space.dart
  app/lib/features/space/pages/chats_page.dart
  app/lib/features/space/providers/space_navbar_provider.dart
  app/lib/features/space/sheets/edit_space_sheet.dart
  app/lib/features/space/widgets/chats_card.dart
  app/lib/features/space/widgets/space_header_profile.dart
  app/lib/features/space/widgets/space_toolbar.dart
  app/lib/features/space/widgets/top_nav.dart
  app/lib/features/spaces/pages/join_space.dart
  app/lib/features/spaces/sheets/create_space_sheet.dart
  app/lib/l10n/app_en.arb
  app/lib/router/router.dart
  app/lib/router/utils.dart
Labels: flutter, infrastructure, s-space

#1667 Update matrix sdk
  Cargo.lock
  Cargo.toml
Labels: rust, minor

#1672 Revert "Update matrix sdk"
  Cargo.lock
  Cargo.toml
Labels: minor

#1674 Upgrade to latest matrix rust sdk to prevent running into the deadlock
  Cargo.lock
  Cargo.toml
Labels: rust, minor

#1677 Update to latst translation data from weblate
  .changes/1677-adding-polish.md
  app/lib/features/settings/model/language_model.dart
  app/lib/l10n/app_da.arb
  app/lib/l10n/app_de.arb
  app/lib/l10n/app_pl.arb
Labels: translations

#1681 Fixes QuickJump and Desktop Navbar routing issues.
  app/lib/features/home/widgets/sidebar_widget.dart
  app/lib/features/search/widgets/quick_jump.dart
Labels: bug, flutter

#1692 Harden invite handling code
  app/lib/features/activities/widgets/invitation_card.dart
  app/lib/l10n/app_en.arb
  app/pubspec.lock
Labels: flutter, minor

#1693 Expose DeviceId/its digest for debugging
  app/lib/features/settings/pages/info_page.dart
  app/lib/l10n/app_en.arb
Labels: flutter, minor
