Repository acterglobal/a3, pull requests merged in 2024-12, with the labels that each got.

#2392 Accepting and forwarding to some object links
  app/lib/features/chat/utils.dart
  app/lib/features/chat/widgets/pill_builder.dart
  app/lib/features/chat/widgets/text_message_builder.dart
  app/lib/features/deep_linking/actions/forward_to_object.dart
  app/lib/features/deep_linking/actions/handle_deep_link_uri.dart
Labels: flutter

#2397 Enforce singleton in release only
  app/linux/CMakeLists.txt
  app/linux/my_application.cc
  app/windows/runner/main.cpp
Labels: t-desktop, build-demo, t-linux, merge post release only

#2408 directly open the selection for the due date
  app/lib/features/tasks/actions/create_task.dart
  app/test/features/tasks/tasks_adding_test.dart
Labels: s-tasks

#2394 External Linking facilities
  .github/workflows/check-rust-integration-tests.yml
  Cargo.lock
  app/lib/features/attachments/widgets/attachment_item.dart
  app/lib/features/attachments/widgets/msg_content_attachment_item.dart
  app/lib/features/attachments/widgets/reference_attachment_item.dart
  app/lib/features/attachments/widgets/views/file_view.dart
  app/lib/features/attachments/widgets/views/image_view.dart
  app/lib/features/attachments/widgets/views/video_view.dart
  native/acter/api.rsh
  native/acter/src/api.rs
  native/acter/src/api/attachments.rs
  native/acter/src/api/calendar_events.rs
  native/acter/src/api/common.rs
  native/acter/src/api/deep_linking.rs
  native/acter/src/api/news.rs
  native/acter/src/api/pins.rs
  native/acter/src/api/tasks.rs
  native/core/src/events/attachments.rs
  native/core/src/events/common.rs
  native/core/src/events/common/object_reference.rs
  native/core/src/lib.rs
  native/core/src/share_link.rs
  native/test/Cargo.toml
  native/test/src/tests/calendar.rs
  native/test/src/tests/pins.rs
  native/test/src/tests/tasks.rs
  native/test/src/tests/thumbnail.rs
  packages/rust_sdk/lib/acter_flutter_sdk_ffi.dart
  util/test_server/.config/acter-synapse-ci/Dockerfile
  util/test_server/.config/acter-synapse-ci/ci-start.sh
  util/test_server/.config/nginx.conf
  util/test_server/docker-compose.yml
Labels: merge post release only

#2414 Disable chatNG in nightly and dev builds
  app/lib/features/labs/model/labs_features.dart
Labels: minor

#2412 Simplify custom event handler into single callback
  native/acter/src/api/client.rs
  native/acter/src/api/client/sync.rs
  native/acter/src/api/spaces.rs
  native/core/src/events.rs
  native/core/src/models.rs
Labels: rust

#2420 Keep the extension of the original file when none was given
  .changes/2420-keep-file-extension.md
  app/lib/features/files/actions/download_file.dart
Labels: bug, flutter

#2421 Update to latest matrix-rust-sdk
  Cargo.lock
  Cargo.toml
  app/ios/Podfile.lock
  app/macos/Podfile.lock
  native/acter/Cargo.toml
  native/acter/src/api/auth.rs
  native/acter/src/api/client.rs
  native/acter/src/platform/native.rs
  native/core/Cargo.toml
  native/file-event-cache/Cargo.toml
  native/file-event-cache/src/lib.rs
  native/file-event-cache/src/queued.rs
  rust-toolchain
Labels: rust, build-demo

#2434 Don't constrain bottom sheet size of change date
  .changes/682.md
  app/lib/features/events/widgets/change_date_sheet.dart
Labels: bug, minor

#2433 Show the user instead of the room in the invite code sharing text
  .changes/minor-fixing-inite-code-naming.md
  app/lib/features/invite_members/pages/share_invite_code.dart
Labels: bug, flutter, c-super-invites

#2432 Fixing range-error when closing room with parents
  .changes/2432-range-error-in-closing-rooms.md
  app/lib/common/actions/close_room.dart
Labels: bug, flutter, minor

#2431 Support cancelling failed messages again
  .changes/2431-cancelling-pending.md
  app/lib/features/chat/widgets/message_metadata_builder.dart
  native/acter/api.rsh
  native/acter/src/api/message.rs
  packages/rust_sdk/lib/acter_flutter_sdk_ffi.dart
Labels: bug, s-chat, minor

#2411 Wrap receiver in broadcast so that receiver can be called multiple times
  app/lib/features/cross_signing/widgets/cross_signing.dart
  app/lib/features/main/app_shell.dart
  app/lib/features/settings/providers/notifiers/devices_notifier.dart
  native/acter/api.rsh
  native/acter/src/api/device.rs
  native/acter/src/api/verification.rs
  native/test/src/tests/verification.rs
  packages/rust_sdk/lib/acter_flutter_sdk_ffi.dart
Labels: rust, merge post release only

#2437 Mac also misses BadgeAppPlus support. Skip it
  packages/acter_notifify/lib/util.dart
Labels: t-desktop, t-macos, minor

#2435 Restore Desktop Window position and size on start
  .changes/2435-restoring-windows.md
  app/lib/config/desktop.dart
  app/linux/my_application.cc
  app/macos/Runner/MainFlutterWindow.swift
  app/pubspec.lock
  app/pubspec.yaml
  app/windows/runner/win32_window.cpp
Labels: flutter, t-desktop

#2439 Disable notification non-show due to URL check
  packages/acter_notifify/lib/acter_notifify.dart
Labels: minor

#2458 Miscellaneous fixes
  native/acter/src/api/account.rs
  native/acter/src/api/attachments.rs
  native/acter/src/api/auth.rs
  native/acter/src/api/backup.rs
  native/acter/src/api/bookmarks.rs
  native/acter/src/api/calendar_events.rs
  native/acter/src/api/client.rs
  native/acter/src/api/comments.rs
  native/acter/src/api/common.rs
  native/acter/src/api/convo.rs
Labels: rust, minor

#2459 Miscellaneous fixes
  native/acter/src/api/deep_linking.rs
  native/acter/src/api/device.rs
  native/acter/src/api/invitation.rs
  native/acter/src/api/message.rs
  native/acter/src/api/news.rs
  native/acter/src/api/pins.rs
  native/acter/src/api/profile.rs
  native/acter/src/api/push.rs
  native/acter/src/api/reactions.rs
  native/acter/src/api/read_receipts.rs
Labels: rust, minor

#2460 Miscellaneous fixes
  native/acter/src/api/client/sync.rs
  native/acter/src/api/room.rs
  native/acter/src/api/rsvp.rs
  native/acter/src/api/search.rs
  native/acter/src/api/settings/space.rs
  native/acter/src/api/spaces.rs
  native/acter/src/api/stories.rs
  native/acter/src/api/stream.rs
  native/acter/src/api/tasks.rs
  native/acter/src/api/typing.rs
Labels: rust, minor

#2461 Miscellaneous fixes
  native/acter/src/api/spaces/categories.rs
  native/core/src/events.rs
  native/core/src/events/common/object_reference.rs
  native/core/src/events/read_receipt.rs
  native/core/src/spaces.rs
  native/core/src/store.rs
  native/core/src/templates.rs
  native/file-event-cache/src/lib.rs
  native/file-event-cache/src/queued.rs
Labels: rust, minor

#2455 Make Invitations more obvious and cleaner
  app/lib/common/themes/colors/color_scheme.dart
  app/lib/common/utils/routes.dart
  app/lib/features/activities/pages/activities_page.dart
  app/lib/features/activities/providers/activities_providers.dart
  app/lib/features/home/pages/dashboard.dart
  app/lib/features/home/widgets/important_activities_section.dart
  app/lib/features/invitations/pages/invites_page.dart
  app/lib/features/invitations/providers/invitations_providers.dart
  app/lib/features/invitations/providers/notifiers/invitation_list_notifier.dart
  app/lib/features/invitations/widgets/has_invites_tile.dart
  app/lib/features/invitations/widgets/invitation_card.dart
  app/lib/l10n/app_en.arb
  app/lib/router/shell_routers/activities_shell_router.dart
Labels: flutter, s-chat, smooth UX, f-push-notifications

#2466 Improve notification params
  packages/acter_notifify/lib/platform/android.dart
  packages/acter_notifify/lib/platform/darwin.dart
Labels: minor, f-push-notifications

#2471 Submit Exceptions logged to Sentry
  app/lib/common/utils/logging.dart
  app/lib/features/auth/actions/register_action.dart
Labels: flutter, infrastructure, minor
