Repository acterglobal/a3, pull requests merged in 2024-09, with the labels that each got.

#2134 Windows path separator is different from other platform's one
  app/lib/common/utils/utils.dart
  app/lib/features/attachments/actions/handle_selected_attachments.dart
  app/lib/features/attachments/widgets/attachment_item.dart
  app/lib/features/attachments/widgets/attachment_selection_options.dart
  app/lib/features/chat/providers/notifiers/media_chat_notifier.dart
  app/lib/features/chat/widgets/file_message_builder.dart
  app/lib/features/news/news_utils/news_utils.dart
  app/lib/features/pins/actions/select_pin_attachments.dart
Labels: flutter, minor

#2133 Fix default app permissions
  .changes/2131-backwards-compat-settings.md
  native/acter/api.rsh
  native/acter/src/api.rs
  native/acter/src/api/settings.rs
  native/acter/src/api/settings/space.rs
  native/core/src/events/settings.rs
  native/core/src/events/settings/space.rs
  native/core/src/spaces.rs
  packages/rust_sdk/lib/acter_flutter_sdk_ffi.dart
Labels: rust

#2135 Fix editing unmodifiable map problem
  app/lib/features/bug_report/actions/open_bug_report.dart
Labels: bug, minor

#2139 Text capitalization for chat input
  app/lib/features/chat/widgets/custom_input.dart
Labels: s-chat, smooth UX, minor

#2119 Chat Input Mention fixes
  .changes/2021-mentions-fixes.md
  app/lib/features/chat/utils.dart
  app/lib/features/chat/widgets/custom_input.dart
  packages/acter_trigger_auto_complete/lib/src/acter_trigger_autocomplete.dart
  packages/acter_trigger_auto_complete/lib/src/acter_trigger_autocomplete_controller.dart
Labels: bug, s-chat

#2140 Improve usage of map
  app/lib/features/calendar_sync/calendar_sync.dart
  app/lib/features/chat/pages/room_page.dart
  app/lib/features/chat/providers/notifiers/chat_room_notifier.dart
  app/lib/features/chat/widgets/bubble_builder.dart
  app/lib/features/chat/widgets/emoji/emoji_container.dart
  app/lib/features/chat/widgets/message_metadata_builder.dart
  app/lib/features/chat/widgets/messages/location_message.dart
  app/lib/features/chat/widgets/messages/sticker_message.dart
  app/lib/features/chat/widgets/text_message_builder.dart
Labels: flutter, minor

#2154 Show Sidebar from mediumLargeAndUp, not only from large (which is larger)
  app/lib/config/app_shell.dart
Labels: bug, flutter, t-desktop, minor

#2156 Suggested User for Invite & Chat creation
  .changes/2156-suggested-users.md
  app/lib/common/providers/room_providers.dart
  app/lib/common/widgets/user_builder.dart
  app/lib/features/activities/providers/invitations_providers.dart
  app/lib/features/chat/widgets/create_chat.dart
  app/lib/features/invite_members/pages/invite_individual_users.dart
  app/lib/features/invite_members/pages/invite_pending.dart
  app/lib/features/invite_members/providers/invite_providers.dart
  app/lib/features/invite_members/widgets/direct_invite.dart
  app/lib/features/member/providers/invite_providers.dart
  app/lib/features/member/widgets/user_builder.dart
  app/lib/features/member/widgets/user_search_results.dart
  app/lib/features/member/widgets/user_search_text_field.dart
  app/lib/l10n/app_en.arb
  native/acter/api.rsh
  native/acter/src/api/invitation.rs
  native/acter/src/api/profile.rs
  packages/rust_sdk/lib/acter_flutter_sdk_ffi.dart
Labels: s-chat, s-space

#2157 Activate swahili
  .changes/adding-swahili.md
  app/lib/features/settings/model/language_model.dart
  app/lib/l10n/app_en.arb
  app/lib/l10n/app_sw.arb
Labels: minor, translations

#2143 Acter Icon Picker implementation and Integrate it with Pin & TaskList
  .changes/2143-acter-icon.md
  app/lib/common/widgets/acter_icon_picker/acter_icon_widget.dart
  app/lib/common/widgets/acter_icon_picker/model/acter_icons.dart
  app/lib/common/widgets/acter_icon_picker/model/color_data.dart
  app/lib/common/widgets/acter_icon_picker/picker/acter_icon_picker.dart
  app/lib/features/pins/actions/edit_pin_actions.dart
  app/lib/features/pins/actions/pin_update_actions.dart
  app/lib/features/pins/pages/create_pin_page.dart
  app/lib/features/pins/pages/pin_details_page.dart
  app/lib/features/pins/widgets/fake_link_attachment_item.dart
  app/lib/features/pins/widgets/pin_icon.dart
  app/lib/features/pins/widgets/pin_list_item_widget.dart
  app/lib/features/tasks/actions/update_tasklist.dart
  app/lib/features/tasks/pages/task_list_details_page.dart
  app/lib/features/tasks/sheets/create_update_task_list.dart
  app/lib/features/tasks/widgets/task_list_item_card.dart
  app/lib/l10n/app_en.arb
  app/test/helpers/mock_pins_providers.dart
  app/test/helpers/mock_tasks_providers.dart
  native/core/src/events/common/rendering.rs
Labels: smooth UX

#2164 Remove id from category
  native/acter/api.rsh
  native/acter/src/api/categories.rs
  native/acter/src/api/common.rs
  native/acter/src/api/news.rs
  native/acter/src/api/pins.rs
  native/acter/src/api/tasks.rs
  native/acter/src/lib.rs
  native/core/src/events/common/categories.rs
  native/test/src/tests/categories.rs
  packages/rust_sdk/lib/acter_flutter_sdk_ffi.dart
Labels: rust, minor

#2166 Bookmarked spaces first
  .changes/2166-bookmarked-spaces-first.md
  app/lib/common/providers/space_providers.dart
  app/lib/common/widgets/room/select_room_drawer.dart
  app/lib/features/home/pages/dashboard.dart
  app/lib/features/home/widgets/sidebar_widget.dart
  app/lib/features/search/providers/spaces.dart
  app/lib/features/search/widgets/pins_builder.dart
  app/lib/features/search/widgets/spaces_builder.dart
  app/lib/features/spaces/pages/spaces_page.dart
Labels: flutter

#2167 Event: Copy to new
  .changes/2167-copy-event-as-new.md
  app/lib/features/events/pages/create_event_page.dart
  app/lib/features/events/pages/event_details_page.dart
  app/lib/l10n/app_en.arb
  app/lib/router/shell_routers/home_shell_router.dart
Labels: s-calendar

#2170 Fix iOS building for ```cargo-make```
  native/acter/src/api/uniffi_api.rs
Labels: bug, rust, build-demo, minor

#2165 Add update action from space view
  .changes/2156-updates-from-spaces.md
  app/lib/features/home/widgets/in_dashboard.dart
  app/lib/features/news/pages/add_news_page.dart
  app/lib/features/news/pages/news_page.dart
  app/lib/features/news/providers/news_post_editor_providers.dart
  app/lib/features/space/widgets/space_sections/space_actions_section.dart
  app/lib/router/general_router.dart
Labels: s-space

#2173 fix #2172: space settings back navigation
  app/lib/features/space/settings/widgets/space_settings_menu.dart
Labels: flutter, minor

#2174 Add ability to configure suggestion for joined chats
  .changes/2169-suggested-chats.md
  app/lib/common/providers/space_providers.dart
  app/lib/features/space/pages/chats_page.dart
  app/lib/features/space/widgets/related/chats_helpers.dart
  app/lib/features/space/widgets/space_sections/chats_section.dart
Labels: bug, flutter, s-space

#2177 Miscellaneous fixes
  app/lib/common/widgets/chat/convo_hierarchy_card.dart
  app/lib/common/widgets/input_text_field.dart
  app/lib/common/widgets/spaces/select_space_form_field.dart
  app/lib/common/widgets/spaces/space_hierarchy_card.dart
  app/lib/features/activities/widgets/invitation_card.dart
  app/lib/features/attachments/actions/add_edit_link_bottom_sheet.dart
  app/lib/features/auth/pages/forgot_password.dart
  app/lib/features/auth/pages/login_page.dart
  app/lib/features/auth/pages/register_page.dart
  app/lib/features/backups/dialogs/provide_recovery_key_dialog.dart
  app/lib/features/bug_report/pages/bug_report_page.dart
  app/lib/features/events/pages/create_event_page.dart
  app/lib/features/events/pages/event_details_page.dart
  app/lib/features/events/widgets/change_date_sheet.dart
  app/lib/features/member/dialogs/show_change_power_level_dialog.dart
  app/lib/features/member/widgets/user_builder.dart
  app/lib/features/pins/pages/create_pin_page.dart
  app/lib/features/pins/pages/pin_details_page.dart
  app/lib/features/settings/pages/blocked_users.dart
  app/lib/features/settings/pages/change_password.dart
  app/lib/features/space/actions/activate_feature.dart
  app/lib/features/space/actions/update_feature_power_level.dart
  app/lib/features/super_invites/pages/create.dart
  app/lib/features/tasks/sheets/create_update_task_item.dart
  app/lib/features/tasks/sheets/create_update_task_list.dart
  app/lib/features/tasks/widgets/task_items_list_widget.dart
Labels: flutter, minor

#2175 Unify Chat and Space Cards
  .changes/2175-unified-rooms-cards.md
  app/integration_test/support/chats.dart
  app/lib/common/actions/show_limited_space_list.dart
  app/lib/common/actions/show_parent_space_list.dart
  app/lib/common/widgets/chat/convo_with_avatar_card.dart
  app/lib/common/widgets/room/room_card.dart
  app/lib/common/widgets/room/room_hierarchy_card.dart
  app/lib/common/widgets/room/room_with_profile_card.dart
  app/lib/common/widgets/spaces/space_hierarchy_card.dart
  app/lib/features/chat/widgets/chats_list.dart
  app/lib/features/chat/widgets/convo_card.dart
  app/lib/features/home/widgets/my_spaces_section.dart
  app/lib/features/public_room_search/widgets/maybe_direct_room_action_widget.dart
  app/lib/features/space/dialogs/suggested_rooms.dart
  app/lib/features/space/pages/chats_page.dart
  app/lib/features/space/widgets/loading_convo_card.dart
  app/lib/features/space/widgets/related/chats_helpers.dart
  app/lib/features/space/widgets/related/spaces_helpers.dart
  app/lib/features/space/widgets/space_header_profile.dart
  app/lib/features/space/widgets/space_info.dart
  app/lib/features/space/widgets/space_sections/spaces_section.dart
  app/lib/features/spaces/pages/spaces_page.dart
  app/lib/features/super_invites/pages/create.dart
  app/lib/features/super_invites/pages/super_invites.dart
  app/lib/features/super_invites/widgets/to_join_room.dart
  app/test/features/chat/chat_listing_search_test.dart
  app/test/features/spaces/error_pages_test.dart
Labels: bug, flutter, smooth UX

#2176 Show suggested rooms on overview
  .changes/2176-show-suggested.md
  app/lib/common/providers/space_providers.dart
  app/lib/common/widgets/room/room_hierarchy_card.dart
  app/lib/features/space/dialogs/suggested_rooms.dart
  app/lib/features/space/pages/chats_page.dart
  app/lib/features/space/providers/suggested_provider.dart
  app/lib/features/space/widgets/related/chats_helpers.dart
  app/lib/features/space/widgets/related/spaces_helpers.dart
  app/lib/features/space/widgets/space_sections/chats_section.dart
  app/lib/features/space/widgets/space_sections/spaces_section.dart
  app/lib/l10n/app_en.arb
Labels: flutter, smooth UX, s-space

#2181 Remove old widget
  app/lib/common/widgets/expandable_text.dart
Labels: flutter, minor

#2183 Check storage permission on Android <= 10 when picking an image/avatar
  .changes/2182-pick-android-avatar.md
  app/lib/common/utils/utils.dart
  app/lib/features/chat/widgets/create_chat.dart
  app/lib/features/files/actions/pick_avatar.dart
  app/lib/features/files/actions/pick_image.dart
  app/lib/features/onboarding/pages/upload_avatar_page.dart
  app/lib/features/pins/actions/select_pin_attachments.dart
  app/lib/features/pins/widgets/pin_attachment_options.dart
  app/lib/features/profile/pages/my_profile_page.dart
  app/lib/features/spaces/pages/create_space_page.dart
  app/lib/l10n/app_en.arb
  app/pubspec.lock
  app/pubspec.yaml
Labels: flutter, minor

#2184 [smallfix] Apply let extension to nullable variables
  app/lib/features/chat/widgets/create_chat.dart
  app/lib/features/events/pages/create_event_page.dart
  app/lib/features/news/pages/add_news_page.dart
  app/lib/features/news/providers/news_post_editor_providers.dart
  app/lib/features/pins/pages/create_pin_page.dart
  app/lib/features/public_room_search/widgets/public_room_search.dart
  app/lib/features/tasks/sheets/create_update_task_list.dart
  app/lib/main.dart
Labels: flutter, minor

#2189 [smallfix] Miscellaneous fixes
  app/lib/common/providers/common_providers.dart
  app/lib/common/providers/room_providers.dart
  app/lib/common/providers/space_providers.dart
  app/lib/common/themes/app_theme.dart
  app/lib/common/utils/utils.dart
  app/lib/common/widgets/acter_icon_picker/acter_icon_widget.dart
  app/lib/common/widgets/edit_html_description_sheet.dart
  app/lib/common/widgets/room/room_hierarchy_join_button.dart
  app/lib/common/widgets/visibility/visibility_chip.dart
  app/lib/features/attachments/actions/handle_selected_attachments.dart
  app/lib/features/attachments/widgets/attachment_section.dart
  app/lib/features/attachments/widgets/attachment_selection_options.dart
  app/lib/features/backups/types.dart
  app/lib/features/backups/widgets/backup_state_widget.dart
  app/lib/features/chat/models/room_list_filter_state/room_list_filter_state.dart
  app/lib/features/chat/pages/room_page.dart
  app/lib/features/chat/providers/notifiers/chat_room_notifier.dart
  app/lib/features/chat/utils.dart
  app/lib/features/chat/widgets/convo_card.dart
  app/lib/features/chat/widgets/custom_input.dart
  app/lib/features/chat/widgets/emoji/emoji_container.dart
  app/lib/features/chat/widgets/emoji/emoji_row.dart
  app/lib/features/chat/widgets/file_message_builder.dart
  app/lib/features/chat/widgets/message_metadata_builder.dart
  app/lib/features/chat/widgets/rooms_list.dart
  app/lib/features/cli/commands/backup-and-reset.dart
  app/lib/features/cli/commands/info.dart
  app/lib/features/events/pages/event_details_page.dart
  app/lib/features/events/pages/event_list_page.dart
  app/lib/features/events/providers/notifiers/rsvp_notifier.dart
  app/lib/features/events/widgets/event_item.dart
  app/lib/features/home/widgets/badged_icon.dart
  app/lib/features/member/widgets/user_builder.dart
  app/lib/features/news/pages/add_news_page.dart
  app/lib/features/news/widgets/news_item.dart
  app/lib/features/news/widgets/news_post_editor/news_slide_options.dart
  app/lib/features/pins/pages/pins_list_page.dart
  app/lib/features/pins/providers/pins_provider.dart
  app/lib/features/profile/pages/my_profile_page.dart
  app/lib/features/search/providers/pins.dart
  app/lib/features/search/providers/spaces.dart
  app/lib/features/settings/pages/language_select_page.dart
  app/lib/features/settings/widgets/settings_section_with_title_actions.dart
  app/lib/features/space/dialogs/suggested_rooms.dart
  app/lib/features/space/settings/pages/apps_settings_page.dart
  app/lib/features/space/settings/pages/visibility_accessibility_page.dart
  app/lib/features/space/sheets/link_room_sheet.dart
  app/lib/features/spaces/pages/create_space_page.dart
  app/lib/features/super_invites/pages/create.dart
  app/lib/features/super_invites/providers/super_invites_providers.dart
  app/lib/features/tasks/pages/tasks_list_page.dart
  app/lib/features/tasks/providers/tasklists_providers.dart
  app/lib/features/tasks/widgets/task_items_list_widget.dart
  app/lib/features/tasks/widgets/task_list_item_card.dart
Labels: flutter, minor

#2190 [smallfix] Miscellaneous fixes
  app/lib/common/providers/room_providers.dart
  app/lib/common/utils/utils.dart
  app/lib/features/bookmarks/providers/bookmarks_provider.dart
  app/lib/features/chat/providers/notifiers/chat_room_notifier.dart
  app/lib/features/member/widgets/user_builder.dart
  app/lib/features/super_invites/pages/create.dart
  app/lib/features/super_invites/pages/super_invites.dart
  app/lib/features/super_invites/providers/super_invites_providers.dart
  app/lib/features/tasks/pages/task_item_detail_page.dart
  app/lib/features/tasks/widgets/task_item.dart
Labels: flutter, minor

#2198 [smallfix] Miscellaneous fixes
  app/lib/common/providers/notifiers/chat_notifiers.dart
  app/lib/common/providers/notifiers/notification_settings_notifier.dart
  app/lib/common/providers/notifiers/relations_notifier.dart
  app/lib/common/providers/notifiers/room_notifiers.dart
  app/lib/common/providers/notifiers/space_notifiers.dart
  app/lib/features/attachments/providers/notifiers/attachments_notifiers.dart
  app/lib/features/bookmarks/providers/notifiers.dart
  app/lib/features/comments/providers/comments.dart
  app/lib/features/events/providers/notifiers/event_notifiers.dart
  app/lib/features/events/providers/notifiers/rsvp_notifier.dart
  app/lib/features/home/providers/task_providers.dart
  app/lib/features/news/providers/notifiers/news_list_notifier.dart
  app/lib/features/pins/pages/pins_list_page.dart
  app/lib/features/pins/providers/notifiers/pins_notifiers.dart
  app/lib/features/settings/providers/notifications_mode_provider.dart
  app/lib/features/settings/providers/notifiers/app_settings_notifier.dart
  app/lib/features/settings/providers/notifiers/devices_notifier.dart
  app/lib/features/settings/providers/notifiers/labs_features.dart
  app/lib/features/tasks/providers/notifiers.dart
Labels: flutter

#2200 refactor of html editor bug fix
  app/lib/common/widgets/edit_html_description_sheet.dart
  app/lib/common/widgets/html_editor.dart
  app/lib/features/comments/widgets/create_comment.dart
  app/lib/features/events/pages/create_event_page.dart
  app/lib/features/news/pages/add_news_page.dart
  app/lib/features/tasks/sheets/create_update_task_list.dart
Labels: bug, flutter

#2196 Upgrade flutter dependencies
  app/ios/Podfile.lock
  app/ios/Runner.xcodeproj/project.pbxproj
  app/macos/Podfile.lock
  app/pubspec.lock
  app/pubspec.yaml
  packages/acter_trigger_auto_complete/example/pubspec.lock
  packages/shake_detector/example/pubspec.lock
  util/conv_test_man/pubspec.lock
Labels: flutter, dependencies, build-demo, merge post release only

#2201 iOS notifications improvements
  app/ios/Podfile.lock
  app/lib/features/settings/pages/email_addresses.dart
  app/lib/features/settings/pages/notifications_page.dart
  app/lib/l10n/app_en.arb
  app/pubspec.lock
  native/acter/src/api/push.rs
  packages/acter_notifify/lib/local.dart
  packages/acter_notifify/lib/platform/darwin.dart
  packages/acter_notifify/lib/util.dart
  packages/acter_notifify/pubspec.yaml
Labels: build-demo, f-push-notifications, merge post release only

#2199 Thumbnail api for msg draft
  .changes/2199-thumbnail-api.md
  native/acter/api.rsh
  native/acter/src/api/attachments.rs
  native/acter/src/api/stream/msg_draft.rs
  native/core/src/events/attachments.rs
  native/test/src/tests.rs
  native/test/src/tests/blurhash.rs
  native/test/src/tests/thumbnail.rs
  packages/rust_sdk/lib/acter_flutter_sdk_ffi.dart
Labels: rust
