Repository acterglobal/a3, pull requests merged in 2025-06, with the labels that each got.

#3075 update goldens
  app/test/features/chat_ng/chat_room_page/goldens_images/chat_room_page.png
  app/test/features/chat_ng/dialogs/goldens/message_actions_other_long.png
  app/test/features/chat_ng/dialogs/goldens/message_actions_other_medium.png
  app/test/features/chat_ng/dialogs/goldens/message_actions_other_short.png
  app/test/features/chat_ng/dialogs/goldens/message_actions_own_long.png
  app/test/features/chat_ng/dialogs/goldens/message_actions_own_medium.png
  app/test/features/chat_ng/dialogs/goldens/message_actions_own_short.png
Labels: minor

#3080 Chain the builder & draft methods sequentially in rust test
  native/test/src/tests/activities/likes.rs
  native/test/src/tests/categories.rs
  native/test/src/tests/news.rs
  native/test/src/tests/notifications/comments.rs
  native/test/src/tests/notifications/event.rs
  native/test/src/tests/notifications/news.rs
  native/test/src/tests/notifications/pins.rs
  native/test/src/tests/notifications/tasks.rs
  native/test/src/tests/spaces.rs
  native/test/src/tests/stories.rs
  native/test/src/tests/tasks.rs
Labels: rust, minor

#3082 Refactor string comparison in rust test
  Cargo.lock
  native/test/Cargo.toml
  native/test/src/tests/activities/comments.rs
  native/test/src/tests/activities/space.rs
  native/test/src/tests/activities/status.rs
  native/test/src/tests/auth.rs
  native/test/src/tests/backup.rs
  native/test/src/tests/bookmarks.rs
  native/test/src/tests/calendar.rs
  native/test/src/tests/invitation.rs
  native/test/src/tests/media_msg/blurhash.rs
  native/test/src/tests/media_msg/download.rs
  native/test/src/tests/media_msg/thumbnail.rs
  native/test/src/tests/msg_edit.rs
  native/test/src/tests/notifications/attachments.rs
  native/test/src/tests/notifications/pins.rs
  native/test/src/tests/notifications/tasks.rs
  native/test/src/tests/pins.rs
  native/test/src/tests/reaction.rs
  native/test/src/tests/redact.rs
  native/test/src/tests/ref_details.rs
  native/test/src/tests/reply.rs
  native/test/src/tests/room_updates.rs
  native/test/src/tests/spaces.rs
  native/test/src/tests/stories.rs
  native/test/src/tests/tasks.rs
  native/test/src/utils.rs
Labels: rust, minor

#3083 [smallfix] Miscellaneous fixes
  native/test/src/tests/activities/likes.rs
  native/test/src/tests/formatted_body.rs
  native/test/src/tests/reaction.rs
  native/test/src/tests/reply.rs
  native/test/src/tests/spaces.rs
  native/test/src/tests/typing.rs
  native/test/src/utils.rs
Labels: rust, minor

#3030 [smallfix] Miscellaneous fixes
  native/acter/api.rsh
  native/acter/src/api/convo.rs
  native/core/src/events/common/categories.rs
  native/core/src/spaces.rs
  native/core/src/spaces/permissions.rs
  native/test/src/tests/categories.rs
  native/test/src/tests/pins.rs
  native/test/src/tests/spaces.rs
  native/test/src/tests/super_invites.rs
  packages/rust_sdk/lib/acter_flutter_sdk_ffi.dart
Labels: rust

#3096 Fix message with emoji rendering issue
  app/lib/features/chat_ng/utils.dart
  app/test/features/chat_ng/utils_test.dart
Labels: minor

#3105 fixing rust CI
  .github/workflows/check-native.yml
  .github/workflows/check-rust-integration-tests.yml
  app/pubspec.lock
  packages/rust_sdk/lib/acter_flutter_sdk_ffi.dart
Labels: build, minor

#3108 Don't reset draft if it is empty or just a line break
  app/lib/features/chat_ng/widgets/chat_editor/chat_editor.dart
  app/test/features/chat_ng/widgets/chat_editor/chat_editor_test.dart
Labels: s-chat, minor, c-html-editor

#3109 Editor editable fix
  app/lib/common/toolkit/html_editor/html_editor.dart
  app/test/toolkit/html_editor/editor_state_helpers_test.dart
Labels: bug, minor, c-html-editor

#3115 desktop setup onboarding UI width adjusted.
  .changes/3115-desktop-setup-UI-change.md
  app/lib/features/desktop_setup/pages/desktop_setup_page.dart
Labels: minor

#3117 beta version tag removed from activity screen
  .changes/3117-beta-tag-removed-from-activities.md
  app/lib/features/activities/widgets/space_activities_section/space_activities_section_widget.dart
Labels: flutter, minor

#3134 a3 flutter update (3.32.4)
  .github/workflows/build-app.yml
  .github/workflows/build-docs.yml
  .github/workflows/check-flutter-integration-tests.yml
  .github/workflows/check-flutter-unittest.yml
  .github/workflows/check-native.yml
  .github/workflows/check-styles.yml
  app/lib/common/providers/chat_providers.dart
  app/lib/common/themes/acter_theme.dart
  app/lib/common/themes/components/card_theme.dart
  app/lib/common/themes/components/dialog_theme.dart
  app/lib/common/utils/utils.dart
  app/lib/features/chat/pages/room_page.dart
  app/lib/features/chat/providers/notifiers/chat_room_notifier.dart
  app/lib/features/chat/providers/notifiers/media_chat_notifier.dart
  app/pubspec.lock
  app/pubspec.yaml
  app/test/features/chat/custom_input_test.dart
  app/test/features/chat/messages/image_message_test.dart
  app/test/features/chat_ng/messages/chat_message_test.dart
Labels: dev-breaking

#3088 Chain the draft & builder methods sequentially
  app/lib/features/attachments/actions/handle_selected_attachments.dart
  app/lib/features/chat/widgets/custom_input.dart
  app/lib/features/chat_ng/actions/attachment_upload_action.dart
  app/lib/features/comments/actions/submit_comment.dart
  app/lib/features/events/actions/save_event_locations.dart
  app/lib/features/events/pages/create_event_page.dart
  app/lib/features/events/pages/event_details_page.dart
  app/lib/features/events/utils/events_utils.dart
  app/lib/features/events/widgets/change_date_sheet.dart
  app/lib/features/news/actions/make_image_slide.dart
  app/lib/features/news/actions/make_text_slide.dart
  app/lib/features/news/actions/make_video_slide.dart
  app/lib/features/pins/actions/pin_update_actions.dart
  app/lib/features/tasks/actions/update_tasklist.dart
  app/lib/features/tasks/pages/task_item_detail_page.dart
  app/lib/features/tasks/pages/task_list_details_page.dart
  app/lib/features/tasks/sheets/create_update_task_list.dart
  app/lib/features/tasks/widgets/due_chip.dart
  app/test/features/events/pages/create_event_page_test.dart
  native/acter/api.rsh
  native/acter/src/api/calendar_events.rs
  native/acter/src/api/news.rs
  native/acter/src/api/stories.rs
  native/acter/src/api/tasks.rs
  native/acter/src/api/timeline/msg_content.rs
  native/acter/src/api/timeline/msg_draft.rs
  native/acter/src/api/timeline/stream.rs
  native/test/src/tests/activities/attachments.rs
  native/test/src/tests/calendar.rs
  native/test/src/tests/fixtures/sample-3s.mp3
  native/test/src/tests/media_msg/blurhash.rs
  native/test/src/tests/media_msg/download.rs
  native/test/src/tests/media_msg/thumbnail.rs
  native/test/src/tests/mention.rs
  native/test/src/tests/news.rs
  native/test/src/tests/notifications/attachments.rs
  native/test/src/tests/notifications/event.rs
  native/test/src/tests/notifications/news.rs
  native/test/src/tests/pins.rs
  native/test/src/tests/stories.rs
  native/test/src/tests/sync.rs
  native/test/src/tests/tasks.rs
  native/test/src/tests/url_previews.rs
  native/test/src/utils.rs
  packages/rust_sdk/lib/acter_flutter_sdk_ffi.dart
Labels: rust, minor
