Repository acterglobal/a3, pull requests merged in 2025-05, with the labels that each got.

#2905 Extend activity to cover the room state change events
  native/acter/api.rsh
  native/acter/src/api/activities.rs
  native/core/src/activities.rs
  native/test/src/tests/activities/mod.rs
  native/test/src/tests/activities/policy_rule_room.rs
  native/test/src/tests/activities/policy_rule_server.rs
  native/test/src/tests/activities/policy_rule_user.rs
  native/test/src/tests/activities/room_avatar.rs
  native/test/src/tests/activities/room_create.rs
  native/test/src/tests/activities/room_encryption.rs
  native/test/src/tests/activities/room_guest_access.rs
  native/test/src/tests/activities/room_history_visibility.rs
  native/test/src/tests/activities/room_join_rules.rs
  native/test/src/tests/activities/room_name.rs
  native/test/src/tests/activities/room_pinned_events.rs
  native/test/src/tests/activities/room_power_levels.rs
  native/test/src/tests/activities/room_server_acl.rs
  native/test/src/tests/activities/room_tombstone.rs
  native/test/src/tests/activities/room_topic.rs
  native/test/src/tests/activities/space_child.rs
  native/test/src/tests/activities/space_parent.rs
  native/test/src/tests/activities/status.rs
  native/test/src/tests/room/room_tombstone.rs
  packages/rust_sdk/lib/acter_flutter_sdk_ffi.dart
Labels: rust, minor

#2927 Fix calendar sync to make the apple review happy
  app/lib/features/calendar_sync/actions/calendar_sync_actions.dart
  app/lib/features/calendar_sync/calendar_sync_permission_page.dart
  app/lib/features/notifications/pages/notification_permission_page.dart
  app/lib/features/settings/pages/calendar_settings_page.dart
  app/lib/l10n/app_en.arb
  app/test/features/calendar_sync/calendar_sync_permission_page_test.dart
Labels: minor

#2810 always show the overview section, regardless of whether we have a topic
  app/lib/features/space/providers/space_navbar_provider.dart
  app/test/features/spaces/provider/space_navabar_provider_test.dart
Labels: flutter, minor, s-space

#2939 fix text not visible after adding mentions
  .changes/2939-chat-ng-mention-fix.md
  app/lib/common/widgets/html_editor/html_editor.dart
Labels: bug, minor

#2943 Weblate latest
  app/lib/l10n/app_de.arb
  app/lib/l10n/app_en.arb
Labels: translations

#2787 UniFFI Next
  .github/workflows/check-native.yml
  Cargo.lock
  Cargo.toml
  Makefile.toml
  app/lib/common/providers/common_providers.dart
  app/lib/features/home/providers/client_providers.dart
  native/acter/Cargo.toml
  native/acter/build.rs
  native/acter/ffi_bindings_extra.dart
  native/acter/src/api.rs
  native/acter/src/api_next/client.rs
  native/acter/src/api_next/error.rs
  native/acter/src/api_next/mod.rs
  native/acter/src/api_next/notification.rs
  native/acter/src/api_next/support.rs
  native/acter/src/lib.rs
  native/acter/uniffi.toml
  native/core/Cargo.toml
  native/file-event-cache/Cargo.toml
  packages/rust_sdk/analysis_options.yaml
  packages/rust_sdk/lib/acter.dart
  packages/rust_sdk/lib/acter_flutter_sdk.dart
  packages/rust_sdk/lib/acter_flutter_sdk_ffi.dart
  util/sari/Cargo.toml
  util/sari/src/commands/build.rs
  util/sari/src/commands/mod.rs
  util/sari/src/main.rs
Labels: build-demo, merge post release only, dev-breaking

#2947 enable event cache
  .changes/event-cache.md
  native/acter/src/api/auth.rs
Labels: minor

#2949 Preload activities data
  .changes/preloading.md
  app/lib/features/activities/providers/activities_providers.dart
  app/lib/features/main/app_shell.dart
Labels: flutter

#2953 Fixed minor bug related to null check
  app/lib/features/chat_ng/widgets/events/replied_to_event.dart
Labels: minor

#2954 [smallfix] Update l10n for activity about room state change
  app/lib/features/activities/widgets/space_activities_section/item_widgets/type_widgets/roomAvatar.dart
  app/lib/features/activities/widgets/space_activities_section/item_widgets/type_widgets/roomName.dart
  app/lib/features/activities/widgets/space_activities_section/item_widgets/type_widgets/roomTopic.dart
  app/lib/l10n/app_de.arb
  app/lib/l10n/app_en.arb
  app/test/features/activity/item_widgets/activity_space_item_widget_test.dart
  app/test/features/activity/mock_data/mock_activity.dart
  app/test/features/activity/mock_data/mock_membership_change.dart
  app/test/features/activity/mock_data/mock_room_avatar_change.dart
  app/test/features/activity/mock_data/mock_room_name_change.dart
  app/test/features/activity/mock_data/mock_room_topic_change.dart
Labels: flutter, minor

#2964 Disable download on unsupported targets
  app/lib/features/files/actions/file_share.dart
Labels: bug, minor

#2955 Updating labs features
  app/lib/features/activities/widgets/security_and_privacy_section/security_and_privacy_section_widget.dart
  app/lib/features/backups/widgets/backup_state_widget.dart
  app/lib/features/labs/feature_flagger.dart
  app/lib/features/labs/model/labs_features.dart
  app/lib/features/labs/providers/labs_providers.dart
  app/lib/features/settings/pages/labs_page.dart
  app/lib/features/settings/widgets/settings_menu.dart
  app/test/features/search/chat_list_widget_test.dart
  app/test/helpers/shared_prefs.dart
  app/test/lib/features/labs/providers/labs_providers_test.dart
  packages/rust_sdk/lib/acter.dart
  packages/rust_sdk/lib/acter_flutter_sdk.dart
Labels: flutter, minor

#2967 Weblate latest
  app/lib/l10n/app_de.arb
  app/lib/l10n/app_en.arb
Labels: minor, translations

#2968 Increased swipeSensitivity so that we can ignore false swipe event during message scroll
  app/lib/features/chat_ng/widgets/events/message_event_item.dart
Labels: minor

#2973 Improve sentry logging
  .github/workflows/build-app.yml
  app/lib/features/labs/providers/labs_providers.dart
  app/lib/main.dart
  app/pubspec.lock
  app/pubspec.yaml
Labels: minor

#2969 Adding greatness to Reply Message Builder UI
  .changes/2969-reply-bubble-ui-improvement.md
  app/lib/features/chat_ng/utils.dart
  app/lib/features/chat_ng/widgets/chat_bubble.dart
  app/lib/features/chat_ng/widgets/events/replied_to_event.dart
  app/lib/features/chat_ng/widgets/replied_to_preview.dart
  app/lib/features/chat_ui_showcase/mocks/convo/timeline/mock_timeline_event_item.dart
  app/lib/features/chat_ui_showcase/mocks/showcase/data/general_usecases.dart
  app/lib/features/chat_ui_showcase/mocks/user/mock_user.dart
  app/test/features/chat_ng/widgets/chat_room/chat_event_messages/golden_chat_event_reply_message_event_test.dart
  app/test/features/chat_ng/widgets/chat_room/chat_event_messages/goldens_images/chat_event_reply_message_event.png
  app/test/features/chat_ng/widgets/chat_room/chat_event_messages/replied_to_preview_test.dart
Labels: bug, s-chat

#2966 Update matrix sdk and other dependencies
  Cargo.lock
  Cargo.toml
  native/acter/Cargo.toml
  native/acter/src/api/auth.rs
  native/acter/src/api/timeline/msg_draft.rs
  native/cli/Cargo.toml
  native/core/Cargo.toml
  native/file-event-cache/Cargo.toml
  native/file-event-cache/src/lib.rs
  native/test/src/tests/activities/room_server_acl.rs
  native/test/src/tests/activities/room_tombstone.rs
  native/tui/Cargo.toml
  native/tui/src/config.rs
  native/tui/src/main.rs
  native/tui/src/ui.rs
  packages/rust_sdk/lib/acter.dart
  util/sari/Cargo.toml
Labels: dependencies, build-demo, minor, merge post release only

#2977 [smallfix] Miscellaneous fixes
  native/core/src/activities.rs
  native/test/src/tests/activities/calendar.rs
  native/test/src/tests/activities/comments.rs
  native/test/src/tests/activities/tasks.rs
  native/test/src/tests/calendar.rs
  native/test/src/tests/news.rs
  native/test/src/tests/notifications/event.rs
  native/test/src/tests/notifications/tasks.rs
  native/test/src/tests/pins.rs
  native/test/src/tests/rsvp.rs
  native/test/src/tests/stories.rs
  native/test/src/tests/templates.rs
  native/test/src/tests/thumbnail.rs
  packages/rust_sdk/lib/acter.dart
  packages/rust_sdk/lib/acter_flutter_sdk_ffi.dart
Labels: rust, minor

#2982 be more expressive when sharing, informing users what happens via sections
  app/lib/features/share/action/share_space_object_action.dart
  app/lib/features/share/widgets/external_share_options.dart
  app/lib/l10n/app_en.arb
Labels: bug, flutter, smooth UX

#2991 Update dependency to fix compilation error from github ci
  app/pubspec.lock
  app/pubspec.yaml
Labels: flutter, dependencies

#2986 Update chat-swipe-sensitivity based on the platform
  app/lib/features/chat_ng/widgets/events/message_event_item.dart
Labels: minor

#2983 [smallfix] Miscellaneous fixes
  native/test/src/tests/activities/comments.rs
  native/test/src/tests/tasks.rs
Labels: rust, minor

#2996 auto-expanding inner HTML editor
  .changes/meta-901-fix.md
  app/lib/common/widgets/html_editor/html_editor.dart
  app/lib/features/chat_ng/utils.dart
  app/lib/features/chat_ng/widgets/chat_editor/chat_editor.dart
  app/lib/features/chat_ng/widgets/chat_editor/chat_editor_loading.dart
  app/pubspec.lock
  app/pubspec.yaml
  app/test/features/chat_ng/widgets/chat_editor/editor_height-auto-scroll_test.dart
Labels: bug, s-chat, c-html-editor

#2999 [smallfix] Refactor the string manipulation
  native/acter/build.rs
  native/acter/src/api/attachments.rs
  native/acter/src/api/client.rs
  native/acter/src/api/comments.rs
  native/acter/src/api/common.rs
  native/acter/src/api/convo.rs
  native/acter/src/api/device.rs
  native/acter/src/api/invitations/object_manager.rs
  native/acter/src/api/news.rs
  native/acter/src/api/profile.rs
  native/acter/src/api/push/notification_item.rs
  native/acter/src/api/push/notification_settings.rs
  native/acter/src/api/room.rs
  native/acter/src/api/room/preview.rs
  native/acter/src/api/search.rs
  native/acter/src/api/stories.rs
  native/acter/src/api/tasks.rs
  native/acter/src/api/timeline/item.rs
  native/acter/src/api/utils.rs
  native/acter/src/api/verification.rs
  native/acter/src/platform/native.rs
  native/cli/src/action/execute.rs
  native/core/src/activities.rs
  native/core/src/events/calendar.rs
  native/core/src/events/common/labels.rs
  native/core/src/events/common/object_reference.rs
  native/core/src/events/pins.rs
  native/core/src/events/tasks.rs
  native/core/src/executor.rs
  native/core/src/models/attachments.rs
  native/core/src/models/calendar/event.rs
  native/core/src/models/comments.rs
  native/core/src/models/invites.rs
  native/core/src/models/news.rs
  native/core/src/models/pins.rs
  native/core/src/models/reactions.rs
  native/core/src/models/read_receipts.rs
  native/core/src/models/rsvp.rs
  native/core/src/models/status/mod.rs
  native/core/src/models/stories.rs
  native/core/src/models/tasks/task.rs
  native/core/src/models/tasks/task_list.rs
  native/core/src/spaces.rs
  native/core/src/store.rs
  native/core/src/templates.rs
  native/core/src/templates/values.rs
  native/test/src/tests/tasks.rs
Labels: rust, minor

#3011 Fixed broken chat show case page
  app/lib/features/chat_ui_showcase/mocks/convo/timeline/mock_timeline_event_item.dart
  packages/rust_sdk/lib/acter.dart
  packages/rust_sdk/lib/acter_flutter_sdk_ffi.dart
Labels: minor

#3022 Switch to latest preditable-order uniffi-dart-gen
  Cargo.lock
  packages/rust_sdk/lib/acter.dart
Labels: minor

#3005 Implement the missed test case from codecov
  native/acter/api.rsh
  native/acter/src/api.rs
  native/acter/src/api/comments.rs
  native/acter/src/api/room.rs
  native/test/src/tests.rs
  native/test/src/tests/attachment.rs
  native/test/src/tests/calendar.rs
  native/test/src/tests/formatted_body.rs
  native/test/src/tests/media_msg/blurhash.rs
  native/test/src/tests/media_msg/download.rs
  native/test/src/tests/media_msg/mod.rs
  native/test/src/tests/media_msg/thumbnail.rs
  native/test/src/tests/msg_draft.rs
  native/test/src/tests/redact.rs
  native/test/src/tests/reply.rs
  native/test/src/tests/room_updates.rs
  native/test/src/tests/tasks.rs
  native/test/src/utils.rs
  packages/rust_sdk/lib/acter_flutter_sdk_ffi.dart
Labels: rust

#3037 Hardening room join
  app/lib/common/providers/chat_providers.dart
  app/lib/common/providers/notifiers/chat_notifiers.dart
  app/lib/common/providers/space_providers.dart
  app/lib/common/widgets/room/room_hierarchy_join_button.dart
  app/lib/features/chat/actions/create_chat.dart
  app/lib/features/chat/pages/room_profile_page.dart
  app/lib/features/chat/pages/sub_chats_page.dart
  app/lib/features/chat/providers/chat_providers.dart
  app/lib/features/invite_members/pages/invite_space_members.dart
  app/lib/features/invite_members/providers/other_spaces_for_invite_members.dart
  app/lib/features/link_room/actions/unlink_child_room.dart
  app/lib/features/link_room/widgets/link_room_trailing.dart
  app/lib/features/onboarding/actions/recommended_space_actions.dart
  app/lib/features/preview/widgets/room_preview.dart
  app/lib/features/public_room_search/pages/search_public_directory.dart
  app/lib/features/public_room_search/widgets/maybe_direct_room_action_widget.dart
  app/lib/features/room/actions/join_room.dart
  app/lib/features/space/dialogs/leave_space.dart
  app/lib/features/space/dialogs/suggested_rooms.dart
  app/lib/features/space/providers/notifiers/relations_notifier.dart
  app/lib/features/space/providers/space_navbar_provider.dart
  app/lib/features/space/providers/suggested_provider.dart
  app/lib/features/space/widgets/related/chats_helpers.dart
  app/lib/features/space/widgets/related/spaces_helpers.dart
  app/lib/features/space/widgets/space_sections/other_chats_section.dart
  app/lib/features/space/widgets/space_sections/other_sub_spaces_section.dart
  app/lib/features/space/widgets/space_sections/suggested_chats_section.dart
  app/lib/features/space/widgets/space_sections/suggested_spaces_section.dart
  app/lib/features/spaces/actions/create_space.dart
  app/lib/features/spaces/pages/sub_spaces_page.dart
  app/lib/features/spaces/providers/space_list_provider.dart
  app/lib/l10n/app_en.arb
  app/test/common/providers/space_providers_test.dart
  app/test/features/invite_members/providers/other_spaces_for_invite_members_test.dart
  app/test/features/room/actions/join_room_test.dart
  app/test/features/space/pages/space_details_page_test.dart
  app/test/features/spaces/other_chats_section_test.dart
  app/test/features/spaces/other_spaces_section_test.dart
  app/test/features/spaces/provider/space_navabar_provider_test.dart
  app/test/features/spaces/spacechats_test.dart
  app/test/features/spaces/suggested_chats_section_test.dart
  app/test/features/spaces/suggested_spaces_section_test.dart
  app/test/helpers/mock_space_providers.dart
Labels: flutter, c-super-invites, merge post release only

#3045 remove context as chat bubble params
  app/lib/features/chat_ng/widgets/chat_bubble.dart
  app/lib/features/chat_ng/widgets/events/chat_event.dart
  app/lib/features/chat_ng/widgets/events/message_event_item.dart
  app/macos/Podfile.lock
  app/test/features/chat_ng/dialogs/message_actions_test.dart
  app/test/features/chat_ng/widgets/chat_bubble_test.dart
Labels: flutter, tech-debt, minor
