Repository acterglobal/a3, pull requests merged in 2025-03, with the labels that each got.

#2660 Fix encryption backup
  .changes/26660-encryption-backup-fix.md
  native/acter/src/api/auth.rs
  native/acter/src/api/backup.rs
  native/acter/src/testing.rs
  native/test/src/tests.rs
  native/test/src/tests/backup.rs
Labels: bug, rust, privacy & security, c-verifications

#2663 Se, mor: Dansk!
  .changes/2663-danish.md
  app/lib/features/settings/model/language_model.dart
  app/lib/l10n/app_da.arb
  app/lib/l10n/app_de.arb
Labels: flutter, translations

#2666 Read Markers
  .changes/read-markers.md
  app/lib/features/chat/pages/room_page.dart
  app/lib/features/chat/providers/chat_providers.dart
  app/lib/features/chat/widgets/convo_card.dart
  app/lib/features/chat_ng/widgets/chat_messages.dart
  native/acter/api.rsh
  native/acter/src/api/stream.rs
  packages/rust_sdk/lib/acter_flutter_sdk_ffi.dart
Labels: s-chat

#2652 Chat Message URL Previews Rust Support
  Cargo.lock
  Cargo.toml
  native/acter/Cargo.toml
  native/acter/api.rsh
  native/acter/src/api.rs
  native/acter/src/api/client.rs
  native/acter/src/api/client/url_preview.rs
  native/acter/src/api/common.rs
  native/acter/src/api/deep_linking.rs
  native/acter/src/api/stream.rs
  native/acter/src/api/stream/msg_draft.rs
  native/test/src/tests.rs
  native/test/src/tests/url_previews.rs
  native/test/src/utils.rs
  packages/rust_sdk/lib/acter_flutter_sdk_ffi.dart
Labels: rust

#2665 Minor cleaning up
  app/integration_test/main_test.dart
  app/integration_test/support/appstart.dart
  app/integration_test/support/chats.dart
  app/integration_test/support/login.dart
  app/integration_test/support/mail.dart
  app/integration_test/support/setup.dart
  app/integration_test/support/spaces.dart
  app/integration_test/support/super_invites.dart
  app/integration_test/support/util.dart
  app/integration_test/tests/attachments.dart
  app/integration_test/tests/auth.dart
  app/integration_test/tests/bug_reporter.dart
  app/integration_test/tests/events.dart
  app/integration_test/tests/pins.dart
  app/integration_test/tests/smoke.dart
  app/integration_test/tests/sub_spaces.dart
  app/integration_test/tests/super_invites.dart
  app/integration_test/tests/tasks.dart
  app/integration_test/tests/updates.dart
  app/lib/common/widgets/user_display_name_widget.dart
  app/lib/common/widgets/user_id_widget.dart
  app/lib/features/comments/widgets/comment_item_widget.dart
  app/lib/features/comments/widgets/time_ago_widget.dart
  app/lib/l10n/app_ar.arb
  app/lib/l10n/app_da.arb
  app/lib/l10n/app_de.arb
  app/lib/l10n/app_en.arb
  app/lib/l10n/app_es.arb
  app/lib/l10n/app_fr.arb
  app/lib/l10n/app_pl.arb
  app/lib/l10n/app_sw.arb
  app/lib/l10n/app_ur.arb
  app/pubspec.lock
  app/pubspec.yaml
  app/snap/gui/app_icon.desktop
  app/snap/gui/app_icon.png
Labels: flutter, build-demo, minor

#2672 Properly inline chat mention
  .changes/2672-inlined-mentions.md
  app/lib/common/toolkit/buttons/user_chip.dart
Labels: flutter, s-chat, minor

#2674 [Chat-NG]: fix desktop auto-focus set to field initially and after sending message
  .changes/2674-fix-autofocus-chat-editor.md
  app/lib/common/widgets/edit_html_description_sheet.dart
  app/lib/common/widgets/html_editor/html_editor.dart
  app/lib/features/chat_ng/widgets/chat_editor/chat_editor.dart
  app/lib/features/events/pages/create_event_page.dart
  app/lib/features/news/pages/add_news/add_news_page.dart
  app/lib/features/tasks/sheets/create_update_task_list.dart
  packages/acter_trigger_auto_complete/example/pubspec.lock
  packages/shake_detector/example/pubspec.lock
  util/conv_test_man/pubspec.lock
Labels: bug, flutter

#2677 add name and subtype for attachment activities
  .github/workflows/build-docs.yml
  native/acter/api.rsh
  native/core/src/activities.rs
  native/test/src/tests/activities/attachments.rs
  native/test/src/tests/activities/calendar.rs
  native/test/src/tests/activities/mod.rs
  packages/rust_sdk/lib/acter_flutter_sdk_ffi.dart
Labels: rust

#2671 [ci build] Build using the iOS Sdk 18.1 as required by AppStore
  app/ios/Runner.xcodeproj/project.pbxproj
Labels: build, t-ios, build-demo, minor, merge post release only

#2682 Fix compilation issue of Android
  Cargo.lock
  native/acter/Cargo.toml
Labels: build, dependencies, minor

#2684 post flutter upgrade fixes for apple
  app/ios/Podfile.lock
  app/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  app/macos/Podfile.lock
  app/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  packages/rust_sdk/lib/acter_flutter_sdk_ffi.dart
Labels: build, t-ios, t-macos

#2679 [chat-ng] Show username on first message, condense message group
  .changes/2679-condensed-chat-ng.md
  app/lib/features/chat_ng/providers/chat_room_messages_provider.dart
  app/lib/features/chat_ng/widgets/chat_bubble.dart
  app/lib/features/chat_ng/widgets/chat_messages.dart
  app/lib/features/chat_ng/widgets/events/chat_event.dart
  app/lib/features/chat_ng/widgets/events/chat_event_item.dart
  app/lib/features/chat_ng/widgets/events/message_event_item.dart
  app/lib/features/chat_ng/widgets/events/text_message_event.dart
  app/test/features/chat_ng/messages/chat_message_test.dart
Labels: s-chat, smooth UX

#2689 Fix object notifications
  .changes/2689-object-notifications.md
  packages/acter_notifify/lib/platform/android.dart
Labels: bug, flutter, t-android, minor, f-push-notifications

#2703 Test cases added related to room.
  app/test/features/room/room_avatar_builder_widget_test.dart
  app/test/features/room/room_card_widget_test.dart
  app/test/features/room/room_profile_header_widget_test.dart
  app/test/features/room/room_with_profile_card_widget_test.dart
  app/test/helpers/mock_room_providers.dart
Labels: tech-debt, minor

#2705 Fix Linux & iOS build
  .github/workflows/build-app.yml
  app/pubspec.lock
  app/pubspec.yaml
Labels: build, build-demo

#2697 Improving User Task Assignment UI & UX
  .changes/2697-assignments.md
  app/lib/common/toolkit/buttons/user_chip.dart
  app/lib/features/tasks/pages/task_item_detail_page.dart
  app/lib/features/tasks/widgets/due_picker.dart
  app/lib/features/tasks/widgets/task_item.dart
  app/lib/l10n/app_en.arb
Labels: flutter, s-tasks, smooth UX

#2706 Upgrade matrix rust sdk
  Cargo.lock
  Cargo.toml
  native/acter/Cargo.toml
  native/acter/api.rsh
  native/acter/src/api/auth.rs
  native/acter/src/api/room.rs
  native/acter/src/api/stream/msg_draft.rs
  native/file-event-cache/src/lib.rs
  native/file-event-cache/src/queued.rs
  native/test/Cargo.toml
  native/tui/Cargo.toml
  util/mr_minutes/Cargo.toml
Labels: build, dependencies, build-demo, minor

#2696 Fixup Room Visibility
  .changes/2595-room-join-rules.md
  Makefile.toml
  app/lib/common/providers/room_providers.dart
  app/lib/common/widgets/room/room_with_profile_card.dart
  app/lib/common/widgets/visibility/room_visibilty_type.dart
  app/lib/features/chat/pages/room_profile_page.dart
  app/lib/features/room/join_rule/join_rule_chip.dart
  app/lib/features/room/join_rule/room_join_rule_item.dart
  app/lib/features/room/join_rule/room_join_rule_selector.dart
  app/lib/features/room/join_rule/room_join_rule_type.dart
  app/lib/features/room/model/room_join_rule.dart
  app/lib/features/room/model/room_visibility.dart
  app/lib/features/space/settings/pages/visibility_accessibility_page.dart
  app/lib/features/space/widgets/space_info.dart
  app/lib/features/spaces/actions/create_space.dart
  app/lib/features/spaces/pages/create_space_page.dart
  app/test/features/link_room/link_room_page_test.dart
  app/test/features/link_room/link_room_trailing_test.dart
  app/test/features/spaces/error_pages_test.dart
  app/test/features/spaces/subspaces_test.dart
  app/test/features/spaces/utils.dart
  native/acter/api.rsh
  native/core/src/spaces.rs
  native/test/src/tests/spaces.rs
  packages/rust_sdk/lib/acter_flutter_sdk_ffi.dart
Labels: bug

#2711 [Chat-NG]: add reply swipe
  .changes/2711-reply-swipe-chat-ng.md
  app/lib/features/chat_ng/widgets/events/message_event_item.dart
Labels: flutter, minor

#2717 Fixup weblate translations
  .github/nextest-config.toml
  app/lib/l10n/app_ar.arb
  app/lib/l10n/app_da.arb
  app/lib/l10n/app_de.arb
  app/lib/l10n/app_en.arb
  app/lib/l10n/app_es.arb
  app/lib/l10n/app_fr.arb
  app/lib/l10n/app_sw.arb
  app/lib/l10n/app_ur.arb
Labels: translations

#2718 Sending State for Chat-ng
  .changes/2718-chatng-send-state.md
  app/lib/common/toolkit/widgets/pulsating_icon.dart
  app/lib/features/chat_ng/providers/chat_room_messages_provider.dart
  app/lib/features/chat_ng/widgets/events/chat_event.dart
  app/lib/features/chat_ng/widgets/events/chat_event_item.dart
  app/lib/features/chat_ng/widgets/events/message_event_item.dart
  app/lib/features/chat_ng/widgets/sending_error_dialog.dart
  app/lib/features/chat_ng/widgets/sending_state_widget.dart
  app/lib/l10n/app_en.arb
  app/test/common/toolkit/widgets/pulsating_icon_test.dart
  app/test/features/chat_ng/widgets/chat_event_item_test.dart
  app/test/features/chat_ng/widgets/message_event_item_sending_state_test.dart
  app/test/features/chat_ng/widgets/sending_state_widget_test.dart
  app/test/features/tasks/tasks_adding_test.dart
Labels: s-chat

#2719 Fix comment notifications
  .changes/2719-fix-comments-notifcations.md
  packages/acter_notifify/lib/processing/attachment.dart
  packages/acter_notifify/lib/processing/comment.dart
  packages/acter_notifify/lib/processing/description.dart
  packages/acter_notifify/lib/processing/event.dart
  packages/acter_notifify/lib/processing/object_creation.dart
  packages/acter_notifify/lib/processing/object_other_changes.dart
  packages/acter_notifify/lib/processing/object_redaction.dart
  packages/acter_notifify/lib/processing/reaction.dart
  packages/acter_notifify/lib/processing/references.dart
  packages/acter_notifify/lib/processing/task_item.dart
  packages/acter_notifify/lib/processing/task_list.dart
  packages/acter_notifify/lib/processing/title_change.dart
  packages/acter_notifify/lib/processing/utils.dart
  packages/acter_notifify/test/comment_notification_test.dart
  packages/acter_notifify/test/mock_data/mock_object.dart
Labels: f-push-notifications

#2724 Fix live event
  app/lib/features/events/providers/event_type_provider.dart
  app/test/features/events/event_providers_test.dart
  app/test/helpers/mock_event_providers.dart
Labels: bug, s-calendar, minor

#2730 switch to a device_calendar with event color fix
  app/pubspec.lock
  app/pubspec.yaml
Labels: bug, s-calendar, t-android

#2733 Fix parsing of https://app.acter.global/ URI's generated by the server
  app/lib/features/deep_linking/parse_acter_uri.dart
  app/test/features/deep_linking/parse_acter_uri_test.dart
Labels: bug, flutter, minor

#2738 Bump to latest device_calendar develop for android device fixes
  .changes/2738-android-caldendar-sync.md
  app/pubspec.lock
  app/pubspec.yaml
Labels: t-android, dependencies, minor

#2720 task invitations notifications
  native/acter/api.rsh
  native/acter/src/api.rs
  native/acter/src/api/activities.rs
  native/acter/src/api/invitations.rs
  native/acter/src/api/push/client.rs
  native/acter/src/api/push/notification_item.rs
  native/acter/src/api/tasks.rs
  native/core/src/activities.rs
  native/core/src/activities/object.rs
  native/core/src/events.rs
  native/core/src/events/explicit_invites.rs
  native/core/src/models.rs
  native/core/src/models/any.rs
  native/core/src/models/capabilities.rs
  native/core/src/models/conversion.rs
  native/core/src/models/invites.rs
  native/core/src/models/tasks/task.rs
  native/core/src/referencing.rs
  native/test/src/tests/tasks.rs
  native/test/src/tests/tasks/invitations.rs
  packages/acter_notifify/lib/model/push_styles.dart
  packages/acter_notifify/lib/processing/object_invitation.dart
  packages/acter_notifify/lib/util.dart
  packages/acter_notifify/test/invitations_notification_test.dart
  packages/rust_sdk/lib/acter_flutter_sdk.dart
  packages/rust_sdk/lib/acter_flutter_sdk_ffi.dart
Labels: s-tasks, f-push-notifications, merge post release only

#2742 Implement encryption backup key storage
  native/acter/api.rsh
  native/acter/src/api/backup.rs
  native/acter/src/api/common.rs
  native/core/src/store.rs
  native/test/src/tests/backup.rs
  packages/rust_sdk/lib/acter_flutter_sdk_ffi.dart
Labels: rust, e2ee

#2744 [simplefix] Rename SyncAnyActerEvent to AnySyncActerEvent
  native/acter/src/api/client/sync.rs
  native/acter/src/api/push/notification_item.rs
  native/core/src/events.rs
Labels: rust, minor

#2743 Task invite accpeting & declining
  native/acter/src/api/invitations.rs
  native/core/src/models/invites.rs
  native/core/src/models/tasks/task.rs
  native/test/src/tests/tasks/invitations.rs
Labels: rust

#2760 no settings should lead to Ok(None) not error.
  .changes/2760.md
  native/acter/src/api/settings/space.rs
Labels: bug, minor

#2769 Add workaround to allow for deprecation on linux builds
  app/linux/CMakeLists.txt
Labels: minor, t-linux
