Repository acterglobal/a3, pull requests merged in 2025-01, with the labels that each got.

#2476 Widget Testing Enhancement : PinListWidget and PinItemWidget
  app/lib/features/pins/widgets/pin_list_item_widget.dart
  app/test/features/pins/pin_item_test.dart
  app/test/features/pins/pin_list_widget_test.dart
  app/test/helpers/mock_pins_providers.dart
Labels: minor

#2482 Fixes : Chat opening twice on click of notification
  .changes/2482-chat-notification.md
  packages/acter_notifify/lib/push.dart
Labels: merge post release only

#2468 Boost Comments and Like Notifications
  .changes/2468-comment-notifications.md
  .github/workflows/check-flutter-unittest.yml
  .github/workflows/check-native.yml
  Cargo.lock
  Cargo.toml
  app/lib/common/providers/common_providers.dart
  app/lib/common/widgets/default_bottom_sheet.dart
  app/lib/features/comments/actions/submit_comment.dart
  app/lib/features/comments/types.dart
  app/lib/features/comments/widgets/add_comment_widget.dart
  app/lib/features/comments/widgets/comments_section_widget.dart
  app/lib/features/labs/model/labs_features.dart
  app/lib/features/news/actions/submit_news.dart
  app/lib/features/news/widgets/news_item/news_side_bar.dart
  app/lib/features/notifications/actions/autosubscribe.dart
  app/lib/features/notifications/actions/subscribe_object_push.dart
  app/lib/features/notifications/actions/unsubscribe_object_push.dart
  app/lib/features/notifications/actions/update_autosubscribe.dart
  app/lib/features/notifications/pages/notifications_page.dart
  app/lib/features/notifications/providers/notification_settings_providers.dart
  app/lib/features/notifications/providers/notifiers/notification_settings_notifier.dart
  app/lib/features/notifications/providers/object_notifications_settings_provider.dart
  app/lib/features/notifications/types.dart
  app/lib/features/notifications/widgets/labs_notifications_settings_tile.dart
  app/lib/features/notifications/widgets/object_notification_status.dart
  app/lib/features/settings/pages/labs_page.dart
  app/lib/features/settings/providers/notifications_mode_provider.dart
  app/lib/features/settings/widgets/app_notifications_settings_tile.dart
  app/lib/l10n/app_en.arb
  app/lib/router/shell_routers/home_shell_router.dart
  native/acter/Cargo.toml
  native/acter/api.rsh
  native/acter/src/api.rs
  native/acter/src/api/push.rs
  native/acter/src/api/push/client.rs
  native/acter/src/api/push/notification_item.rs
  native/acter/src/api/push/notification_settings.rs
  native/acter/src/api/push/pusher.rs
  native/acter/src/api/settings/user.rs
  native/core/Cargo.toml
  native/core/src/events/settings/user.rs
  native/core/src/models.rs
  native/test/Cargo.toml
  native/test/src/tests.rs
  native/test/src/tests/notifications.rs
  native/test/src/tests/notifications/comments.rs
  native/test/src/tests/notifications/likes.rs
  native/test/src/tests/notifications/news.rs
  native/test/src/utils.rs
  packages/acter_notifify/lib/matrix.dart
  packages/acter_notifify/lib/platform/android.dart
  packages/acter_notifify/lib/platform/darwin.dart
  packages/acter_notifify/lib/platform/windows.dart
  packages/acter_notifify/lib/util.dart
  packages/acter_notifify/pubspec.yaml
  packages/acter_notifify/test/acter_notifify_test.dart
  packages/rust_sdk/lib/acter_flutter_sdk_ffi.dart
Labels: f-push-notifications, merge post release only

#2494 TaskItem and TaskListItem widget testing
  app/lib/common/providers/room_providers.dart
  app/test/features/tasks/task_item_test.dart
  app/test/features/tasks/task_list_item_card_test.dart
  app/test/helpers/mock_tasks_providers.dart
Labels: minor

#2496 Fixing notification support for iOS build
  Makefile.toml
  native/acter/src/api/uniffi_api.rs
Labels: t-ios, ci-build-ios, build-demo, minor

#2505 Fix rust docs
  native/core/src/events/calendar.rs
  native/core/src/util.rs
Labels: documentation, minor

#2503 Fix too many calendars on Android
  .changes/2503-fix-calendar-on-android.md
  app/android/app/build.gradle
  app/android/app/proguard-rules.pro
  app/android/gradle.properties
  app/lib/features/calendar_sync/calendar_sync.dart
Labels: s-calendar, t-android, ci-build-android, build-demo, merge post release only

#2506 Acter Icon and Acter Icon Picker widget testing
  app/lib/common/widgets/acter_icon_picker/picker/acter_icon_picker.dart
  app/test/common/widgets/acter_icon_picker_widget_test.dart
  app/test/common/widgets/acter_icon_widget_test.dart
Labels: minor

#2512 fix flutter unit tests
  app/lib/features/chat_ng/widgets/reactions/reaction_detail_sheet.dart
  app/test/features/chat_ng/reactions/reactions_test.dart
  app/test/helpers/mock_chat_providers.dart
Labels: s-chat, minor

#2518 Acter Icon Widget : Fixes Unit test failure
  app/test/common/widgets/acter_icon_widget_test.dart
Labels: minor

#2515 [Rust] Proper typed for internal indizes and subscription keys
  app/lib/common/providers/common_providers.dart
  app/lib/common/providers/notifiers/chat_notifiers.dart
  app/lib/common/providers/notifiers/room_notifiers.dart
  app/lib/common/providers/notifiers/space_notifiers.dart
  app/lib/features/bookmarks/providers/notifiers.dart
  app/lib/features/events/providers/notifiers/event_notifiers.dart
  app/lib/features/events/providers/notifiers/participants_notifier.dart
  app/lib/features/events/providers/notifiers/rsvp_notifier.dart
  app/lib/features/news/providers/notifiers/news_list_notifier.dart
  app/lib/features/pins/providers/notifiers/pins_notifiers.dart
  app/lib/features/tasks/providers/notifiers.dart
  app/test/helpers/mock_a3sdk.dart
  native/acter/api.rsh
  native/acter/src/api/account.rs
  native/acter/src/api/attachments.rs
  native/acter/src/api/calendar_events.rs
  native/acter/src/api/client.rs
  native/acter/src/api/client/sync.rs
  native/acter/src/api/convo.rs
  native/acter/src/api/news.rs
  native/acter/src/api/pins.rs
  native/acter/src/api/push/notification_item.rs
  native/acter/src/api/read_receipts.rs
  native/acter/src/api/rsvp.rs
  native/acter/src/api/spaces.rs
  native/acter/src/api/stories.rs
  native/acter/src/api/tasks.rs
  native/core/src/events/settings.rs
  native/core/src/executor.rs
  native/core/src/lib.rs
  native/core/src/models.rs
  native/core/src/models/attachments.rs
  native/core/src/models/calendar.rs
  native/core/src/models/calendar/event.rs
  native/core/src/models/comments.rs
  native/core/src/models/news.rs
  native/core/src/models/pins.rs
  native/core/src/models/reactions.rs
  native/core/src/models/read_receipts.rs
  native/core/src/models/rsvp.rs
  native/core/src/models/stories.rs
  native/core/src/models/tasks.rs
  native/core/src/models/tasks/task.rs
  native/core/src/models/tasks/task_list.rs
  native/core/src/models/test.rs
  native/core/src/referencing.rs
  native/core/src/statics.rs
  native/core/src/store.rs
  native/test/src/tests/spaces.rs
  native/test/src/tests/tasks.rs
  packages/rust_sdk/lib/acter_flutter_sdk_ffi.dart
Labels: tech-debt

#2519 news is still a valid name to serialize the index from
  native/core/src/referencing.rs
Labels: bug, s-news, minor

#2520 [Rust] Observable Sorted Indizes for Stored Models
  Cargo.lock
  native/acter/src/api/news.rs
  native/acter/src/api/rsvp.rs
  native/acter/src/api/stories.rs
  native/core/Cargo.toml
  native/core/src/models.rs
  native/core/src/models/calendar/event.rs
  native/core/src/models/rsvp.rs
  native/core/src/models/test.rs
  native/core/src/store.rs
  native/core/src/store/index.rs
Labels: rust

#2528 Solved weird Listview scrolling.
  .changes/2528-listview-scroll-behavior.md
  app/lib/features/events/widgets/event_list_widget.dart
Labels: minor

#2530 Selective calendar sync
  .changes/2530-selected-cal-sync.md
  app/lib/features/calendar_sync/actions/set_room_sync_preference.dart
  app/lib/features/calendar_sync/providers/events_to_sync_provider.dart
  app/lib/features/datetime/providers/notifiers/now_notifier.dart
  app/lib/features/room/providers/notifiers/user_settings_notifier.dart
  app/lib/features/room/providers/user_settings_provider.dart
  app/lib/features/space/actions/has_seen_suggested.dart
  app/lib/features/space/providers/suggested_provider.dart
  app/lib/features/space/settings/widgets/space_settings_menu.dart
  app/lib/l10n/app_en.arb
  app/test/features/calendar_sync/calendar_sync_test.dart
  app/test/helpers/mock_a3sdk.dart
  app/test/helpers/mock_event_providers.dart
  app/test/helpers/mock_room_providers.dart
  native/acter/api.rsh
  native/acter/src/api.rs
  native/acter/src/api/client.rs
  native/acter/src/api/client/sync.rs
  native/acter/src/api/room.rs
  native/acter/src/api/room/account_data.rs
  native/acter/src/api/room/subscription.rs
  native/core/src/client.rs
  native/core/src/events/room.rs
  native/core/src/referencing.rs
  native/test/src/tests.rs
  native/test/src/tests/room/mod.rs
  native/test/src/tests/room/user_settings.rs
  packages/rust_sdk/lib/acter_flutter_sdk_ffi.dart
Labels: s-calendar, merge post release only

#2542 Solve supper invite code error.
  .changes/2542-supper-invite-bug.md
  app/lib/features/super_invites/pages/create.dart
Labels: bug, minor

#2539 Implement rust notifications for creation, title and description change of major objects
  native/acter/src/api/push/notification_item.rs
  native/test/src/tests/notifications.rs
  native/test/src/tests/notifications/attachments.rs
  native/test/src/tests/notifications/event.rs
  native/test/src/tests/notifications/mod.rs
  native/test/src/tests/notifications/pins.rs
  native/test/src/tests/notifications/references.rs
  native/test/src/tests/notifications/tasks.rs
Labels: rust, f-push-notifications
